
import java.util.*;
import java.util.function.*;

public class Test06 {

    public static void main(String[] args) {
        Comparator<String> comp = (a, b) -> b.compareTo(a);

        List<List<String>> seznami = List.of(
            List.of("yqymaqldzcal", "bfu", "yedndtvpcug", "dbilqhyhlvfuobvf", "xwiuqzcrcacmmbwdk", "dtggwbmjgot", "vpwbrelgnfebdhg", "fhbwpnejyaeu", "uytuyirybdwy", "fnueqipyvthkgaypb", "uaic", "hazjjxmuvnv", "thraxvn", "klbtvkkjwbshrgjanxqv", "seawctqduymyj", "ogdtbnzil", "rrhhtpilpiqbwpben", "rn", "okqizruooqnqj", "rtlnvsqfyekkjjhnfu", "lhgu", "tfclpbvtaidyg", "indezxpgbiakigzcai", "tvblgdmmuww", "gzqz", "utftuvmhopzssypisnn", "fkkei", "vgdiokcfjey", "facthbgyjdgywebkmmtp", "wlyiytcfmlnvtmpiqz", "dnfsykkuninv", "yclyzsqutqpdqaij", "bkuuicro", "yprvwrpp", "alikogavuktlus"),
            List.of("bdbgqslmafzpul"),
            List.of("zwpjecipjafkfydnna", "anlnrfwbsaqd", "zrafxxaftjyydbaegl", "ayxhsgrbq", "zjcbtnfbolmaub", "bdlosfpyvnwpbhlrhzxv", "zewyaufdgxxyvzqpevbd", "bkyk", "ynfifkguockpbm", "bpiprepeinmusvqfll", "xxczscfihxewxafya", "cbkltipcmnpiala", "xkppznpasy", "domxedxgvjjbjrrlt", "xfidtchvitkvngcce", "dsinbdll", "wxehqtflwosesuoe", "elwnnljkbbwyuxdhundw", "wnof", "fdibvprnzoidh", "vtpfgqgdhndzfqay", "godxdetmtgbocpnp", "veuxjksaeg", "hewu", "ufcqtmmoc", "hrapemxkjlcagbswuqe", "spg", "ilk", "sfiosp", "jgarmof", "scvrw", "jzzy", "rwtwhlh", "kuguqsumztn", "ruxwewscalquvplk", "lbjwad", "rqspittgvqmecqy", "ln", "qtcmjtkc", "lyzzbahmsczygdzkela", "pzepqgtuoqmshrmyrvi", "mqaorgnx", "ppbeom", "nomuciiowwii", "pjhnri", "nuoxlxlvsnf", "ontfurssqtmsgrfxm", "ojanlvulhqzfoaa", "obdzwzdci", "osqyvcplnhccpd", "npxrtpsgenfojpx", "pjrkyxuovymtpxotixvt", "nggqnuk", "punafydnfwcpd", "mowdkgcjb", "qgkwreyccepazpg", "lpdy", "rgelqwuldaupbw", "lmikay", "rrefitms", "kyocjbiqbzbi", "ruytiwdteop", "khheq", "sbxcesrupbj", "jtvezifmbgklafpgeq", "scyaocnejytpnxcdhbwx", "iqpm", "sltnhshvmncsidgvl", "id", "tqxwf", "hlcecmhsnkhfqnrwbaqc", "uugyezygu", "gvlm", "vlwecckqbcufelhfgm", "fv", "wn", "fcffw", "wvcbz", "dwavnodl", "xbsgifxfhuojmk", "dpwaxaln", "xgjxqhnrbpd", "cdmfmjopwlcwmneumh", "xncwodrkq", "bumfmkopy", "xxexhvqmpu", "bpiko", "zbjcaoilnrpkgvy", "bfm", "ziypjafghxw", "baebmdhzbuytahwwxi", "zorvptig", "aymigo", "zwchssfddhfvfylser", "alhlr"),
            List.of("ruhvbpt", "bxozuubwsgdnaoyrdd", "jvzjykrxayleyszjnvi", "grx", "jrtxduiclzaee", "ibfvvdbepdi", "czwlxlnkoavygvsoqav", "ncfiiuzt", "a", "vkvxlrajrmzubyu"),
            List.of("vpnj", "bdihubbmcbjlepqlx", "zijj", "biubmqw", "gyemcmavehzezeqg", "ko", "djzqorcogybyxtysva", "kodrxashrkupnju", "dezntr", "llzd", "apafutmqlqookytgmet"),
            List.of("lmrougdagbhtfp", "imdcv", "kugujpqsrxauorfexsgq", "whfvfohlbujxdf", "grbmjn"),
            List.of("zlr", "bamwmfilwqrr", "zay", "bcwakygsgiedyrbp", "yedndtvpcug", "dfeidwqivnhsuyssg", "xxuwizmyzhestolw", "djtlmuexdnavnullosb", "xvsguvwgt", "dlrzsxxrusirb", "wvfflfaxianrgsrhyp", "dxyxrawlqkwilpcf", "wobz", "eapgglhmunvwa", "vznyzxhsirchbvsrws", "edjwynmrmxeh", "vvstfzg", "emaghnpjmhs", "vndlfm", "fagmwqcmlazrssvyb", "uwgtkmjkfajxdhuiuy", "fvxtsc", "tfkcrqcnugeee", "gqbpadgj", "sdbzlthly", "guwpzhkp", "rucd", "hnhlezmoqjsut", "rqwtmvsjinleep", "ianecygba", "ptshknthtjbbkdyqyffm", "ixcfftryxvdzschoa", "ocmxeeabo", "jiluskvpptbdoqcuz", "ngkzcxkyyrjjfpi", "joyt", "mmgq", "kfycath", "kxrnswpvclhebaxmyj", "kshmeeco", "jmnpksoogflz", "mkjieytlj", "iuweecjyeixusgf", "nb", "ipolo", "oosiefyj", "ibrtyiarrdbsorocbyu", "otsozxl", "hzgmlru", "pu", "haasum", "qc", "gtaztuvp", "qgntvydzksgive", "glk", "qt", "gfkjooekueiyor", "troizernhitzveclkmb", "gcezpxcxdksskea", "tsmiuogstvsnen", "fjyap", "tvoq", "emrwrxvyo", "txhfiodl", "egedbltkozxsbydu", "urbmglyhmgev", "dcvclbgneyuf", "vqxdhndzlnegfgfzopvp", "cwzlibprdpal", "vrpefea", "bpiprepeinmusvqfll", "wqoqeesjwfitmga", "bgyrdbopjbcadkn", "xrusrf", "bgonj", "yepgjabykubd", "bbcebklwbujpezfmxj", "yotnfpgqusdkeypqcf", "akequt", "ze"),
            List.of("zptfkthxtvmknms", "acnoorgcq", "ypdq", "apppjyd", "wybehx", "bqdilox", "ocgdddzjlurjnn", "brvopahkxrn", "vr", "cpganqgywcsl", "vhzsjvfvlvks", "db", "uhmucbfzsykgshojl", "ddxpblemexfydoe", "txxeifnulap", "dpklmpe", "teqlgeetubqo", "eqxj", "sulaxpprsdntjphpiic", "fbqtsfdwvivvq", "sfzixridqunyuik", "frcxdp", "sbvrhuibovrmw", "fyktworonvxitgt", "rt", "gebzcyfurqg", "qut", "hjgtyptvkxhcmo", "pzrg", "hlstcisnrqk", "pwcmzhhnfsuarrvjkag", "hugmfxmakswbonf", "olmasajudmagluayy", "ijiaou", "wpoyoldlmcicaxpgkevu", "iuphvuy", "ntzeleymzestdfaamr", "jlwcjaslnnxp", "noyhtox", "jvwcwxrrbrriehkvkg", "nehpxv", "lcalrpmlmbvtt", "mly", "lsklcsbmnnpshpdkmia", "lwtdexoyuqlhhryxuo", "mgalonuu", "lscdavavmkxflt", "mypbgldveqsdvonwwn", "kq", "neuoqe", "jqzlurhtkmrkai", "npcikpbhoa", "jkbjrognuocfabyqblo", "nykcvcirvevjuobzmbe", "ijzeobmydexleq", "ojtbovzbftc", "iclgtgd", "pusfnvapavwowdz", "hnkynctdkpzrzen", "pxydl", "hjoaffubzuvtrssyvun", "quonxfgdvbv", "gmedi", "rbuioiodsdimdpue", "gdtnqnxnqix", "rtsuhdevnidtwug", "frkqcmgpuvviwhxqv", "sdrcopnsqptasyfkncs", "fpphlogq", "stksqllkdi", "evuamwvgq", "sy", "ecnrwrckjxurkhd", "tmxxnyzmoxowmnvqqkxp", "dokpcutvv", "uabihxeieartzgs", "dbnuyuffnjdelqmhjybu", "uvgaajvttiyrl", "ctq", "vpmxylnyhip", "ciyhcqmpxadquhwfs", "wbvjtcg", "brjxmqsmngsqn", "wttvnudvexlehasyepo", "awohgophehzxptz", "ydknfk", "amim", "yykjxmpjqjcheplqbymn"),
            List.of("zunfogawklxcau", "gqs", "ygdalm", "nksvjxukqinksx", "w", "orfbbfnndfgiwfuhy", "nmirtmyxkkgmsks", "trspptaw", "iibkbyen", "yjw"),
            List.of("xwyrrqo", "cmafpamwafjrluigwpsl", "wldqhln", "crmvecuk", "vxwizpxwpxqql", "dixadilwlsrxbdx", "vbixpzfklpnrnzok", "dzlyhmzqsrapmdafl", "tkyj", "eadpelqe", "svdksmfciutsqxq", "fbv", "rwwzspf", "fvcfffuahbpkza", "roonbtrigrpubfjess", "gfdnowgkdqxikvqwsvsl", "rgzicerp", "gzs", "rbksxveddopyrikegdz", "halc", "qdyuphypctdemdfarxs", "ifewrup", "ontfurssqtmsgrfxm", "ilopgplhntzzqfyrdcw", "nvztv", "jiovowanbtkgdpdrfiae", "npnoqtqqkbxorghkcyj", "kvomsaqoxltrlobod", "nltfnviwejseaabvn", "kwbxlnmxlbjtykmug", "mkjlsim", "mbkhyc", "kpynydpohowdg", "pbcl", "kmdwppymnqrrvvnllwtc", "pcctavfwkh", "kfycath", "pukeclhkzmtvq", "ibz", "pyqtkrrgvxlg", "hoqabufbzg", "qavdppzjwvcudxqffaok", "hlcecmhsnkhfqnrwbaqc", "qthaoczstlydci", "hivgmboh", "rdlcxqklwlauskulln", "fqhyfzfjfgnkqipbouun", "rrechfvlmb", "ekrmyghweggraqwlfb", "rtmn", "dvkcasqyul", "szanaemctblrcom", "ctfstvgn", "tiziirchrevo", "byoagzwtpyitngv", "tzwaewbmramiiyujanx", "bepyzvrpwf", "uyvdsg", "ayclj", "vuaiasjyyidtnnyblp", "aybbxe", "vy", "arpegxwmhqwcafc", "xirodzidrtarft")
        );

        for (List<String> seznam: seznami) {
            System.out.println(Cetrta.alternirajoceMonotono(seznam, comp));
        }
    }
}
