
import java.util.*;
import java.util.function.*;

public class Test15 {

    public static void main(String[] args) {
        Comparator<String> comp = (a, b) -> a.compareTo(b);

        List<List<String>> seznami = List.of(
            List.of("bjsqtmekxyylv", "vsijaelpzocnt", "npadhjfaxnmubnqb", "mcrtpn", "quwldryklumrgizyaaxc", "loxoveaicczyxigmaj", "uilskyikbkfhmuurc", "hbah", "yidwjziypv"),
            List.of("baca", "zchwec", "cqrttoorckjjh", "yidwjziypv", "cudasddnzhoowufszi", "xyujmosovrdofeodbtgk", "efhllgfxqtnyifyfusmt", "xuugsfwruunaep", "exzomsmimkmihkmm", "xp", "gep", "wx", "heuulapai", "wnh", "hxzdyb", "wjlqzthdemwzybjkmc", "ifjigkpooohlrr", "vrjwzqvjnwovwcxc", "jdjpuyifekhegvfcbxf", "uxvtihiuhq", "jkzgqltebazbmkvlbpgc", "uhd", "juecrn", "tvywkdxscbbbikp", "kfvasuaykfksxbn", "sqywrpmjeirjprhob", "laloctzrce", "rvke", "ortcqgcpnnxo", "put", "pkdoset", "pqolmwrfhckrsixtls", "psojqryegqhk", "pdvxpczzsydntsyugjay", "rkdzwmqop", "nhehgpfsioyptdvpmshb", "sbvrhuibovrmw", "kgkscbawfl", "tpjzcmnupjcuxs", "kedkbwsh", "ubeluohssl", "jrgqrf", "uilskyikbkfhmuurc", "jhyoqmmjvwhzjt", "vmxrwbgbepekocznblvc", "ihdrslkxaiyfts", "vsijaelpzocnt", "hyzarzskftshwrhnie", "wlahzupnyxx", "hqpsnrqaytsfghufaix", "wtxoecjwgidykpzqpoyo", "gpdpuumnz", "wzvwahqz", "fi", "xtd", "ekdftpxebfo", "xvzljnypshytoqu", "drpexdmkedbhb", "ydvefxzoilypq", "ctjxchdbdgifqdsj", "ytqyzmusayeyjq", "chtzcrfikmdzw", "zzrxwjngwrsrcfosdu"),
            List.of("asbz", "zbxtrctectv", "chzgawcjwyqlwgdx", "ytqyzmusayeyjq", "dccfiflowp", "ylrmbrvbkwqzxhf", "drpexdmkedbhb", "yidwjziypv", "efhllgfxqtnyifyfusmt", "xyujmosovrdofeodbtgk", "ekdftpxebfo", "wx", "gpdpuumnz", "vutopkopdthabrckt", "hdv", "uhd", "jrgqrf", "tpjzcmnupjcuxs", "jucbk", "slamwxmfaloiu", "jucbk", "slamwxmfaloiu", "laloctzrce", "sbvrhuibovrmw", "mcrtpn", "rqpsyqngcla", "mrfrgpzzegvbd", "rfewdwy", "pbc", "rfewdwy", "psojqryegqhk", "pqolmwrfhckrsixtls", "psojqryegqhk", "pdvxpczzsydntsyugjay", "psojqryegqhk", "ofafsounesqcze", "put", "ofafsounesqcze", "tvywkdxscbbbikp", "npadhjfaxnmubnqb", "ukhqbdgzqidxstmq", "mcrtpn", "vmxrwbgbepekocznblvc", "jucbk", "wlahzupnyxx", "jrgqrf", "wtxoecjwgidykpzqpoyo", "hyzarzskftshwrhnie", "wtxoecjwgidykpzqpoyo", "hxzdyb", "wx", "gpdpuumnz", "wzvwahqz", "drpexdmkedbhb", "xyujmosovrdofeodbtgk", "dkap", "ydvefxzoilypq", "bjsqtmekxyylv", "ylrmbrvbkwqzxhf", "asbz", "zvrdggvblcqhcyenpdnh"),
            List.of("pkdoset"),
            List.of("exzomsmimkmihkmm", "zchwec", "hqpsnrqaytsfghufaix", "ydvefxzoilypq", "ifjigkpooohlrr", "wnh", "jhyoqmmjvwhzjt", "vrjwzqvjnwovwcxc", "jrgqrf", "tpjzcmnupjcuxs", "mttsaespvuy", "sbvrhuibovrmw", "npadhjfaxnmubnqb", "rfewdwy", "rfewdwy", "quwldryklumrgizyaaxc", "sqywrpmjeirjprhob", "psojqryegqhk", "tvywkdxscbbbikp", "nvxwhsa", "uxvtihiuhq", "jhyoqmmjvwhzjt", "uxvtihiuhq", "hqpsnrqaytsfghufaix", "vmxrwbgbepekocznblvc", "exzomsmimkmihkmm", "vutopkopdthabrckt", "chzgawcjwyqlwgdx", "vutopkopdthabrckt", "edmbyyoateykys", "wnh", "baca"),
            List.of("cudasddnzhoowufszi", "zvrdggvblcqhcyenpdnh", "dkap", "zbxtrctectv", "efhllgfxqtnyifyfusmt", "wtxoecjwgidykpzqpoyo", "exzomsmimkmihkmm", "vo", "gep", "vmxrwbgbepekocznblvc", "ifjigkpooohlrr", "tdaekeepymhjupjksft", "jhyoqmmjvwhzjt", "tdaekeepymhjupjksft", "jrgqrf", "skzwccwbldwxgfy", "kedkbwsh", "sbvrhuibovrmw", "kfvasuaykfksxbn", "rqpsyqngcla", "kfvasuaykfksxbn", "rkdzwmqop", "loxoveaicczyxigmaj", "nyza", "mcrtpn", "nyza", "nyza", "nxtotx", "pbc", "nvxwhsa", "pkdoset", "mrfrgpzzegvbd", "pkdoset", "loxoveaicczyxigmaj", "pqolmwrfhckrsixtls", "loxoveaicczyxigmaj", "rfewdwy", "loxoveaicczyxigmaj", "rqpsyqngcla", "loxoveaicczyxigmaj", "slamwxmfaloiu", "kfvasuaykfksxbn", "tpjzcmnupjcuxs", "jdjpuyifekhegvfcbxf", "uilskyikbkfhmuurc", "hyzarzskftshwrhnie", "uzuwqwjt", "hyxidpvwxmxr", "vmxrwbgbepekocznblvc", "hxzdyb", "vrjwzqvjnwovwcxc", "hqpsnrqaytsfghufaix", "vrjwzqvjnwovwcxc", "hqpsnrqaytsfghufaix", "vsijaelpzocnt", "hdv", "wjlqzthdemwzybjkmc", "gpdpuumnz", "wtxoecjwgidykpzqpoyo", "gep", "xp", "fi", "xsjrbreeqznouivyufz", "exzomsmimkmihkmm", "yidwjziypv", "exzomsmimkmihkmm", "ytqyzmusayeyjq", "ekdftpxebfo", "zbxtrctectv", "ekdftpxebfo", "zchwec", "drpexdmkedbhb", "zzrxwjngwrsrcfosdu", "cudasddnzhoowufszi", "zzrxwjngwrsrcfosdu", "asbz"),
            List.of("asbz", "zzrxwjngwrsrcfosdu", "cmlynatt", "zbxtrctectv", "drpexdmkedbhb", "xyujmosovrdofeodbtgk", "exzomsmimkmihkmm", "xtd", "gep", "xp", "hqpsnrqaytsfghufaix", "wjlqzthdemwzybjkmc", "hyzarzskftshwrhnie", "vrjwzqvjnwovwcxc", "ihdrslkxaiyfts", "uzuwqwjt", "jhyoqmmjvwhzjt", "ukhqbdgzqidxstmq", "kfvasuaykfksxbn", "ubbrimlbjgjyrvze", "mrfrgpzzegvbd", "tpjzcmnupjcuxs", "ofafsounesqcze", "rqpsyqngcla", "pqolmwrfhckrsixtls", "quwldryklumrgizyaaxc", "put", "psojqryegqhk", "rfewdwy", "pkdoset", "slamwxmfaloiu", "nvxwhsa", "tvywkdxscbbbikp", "loxoveaicczyxigmaj", "uilskyikbkfhmuurc", "jkzgqltebazbmkvlbpgc", "uxvtihiuhq", "jdjpuyifekhegvfcbxf", "vo", "iacwkygbjctlpujiun", "vsijaelpzocnt", "hyxidpvwxmxr", "wx", "hdv", "xsjrbreeqznouivyufz", "fi", "xvzljnypshytoqu", "ekdftpxebfo", "ytqyzmusayeyjq", "cudasddnzhoowufszi", "zvrdggvblcqhcyenpdnh", "bjsqtmekxyylv"),
            List.of("cmlynatt", "jrgqrf", "hxzdyb", "nyza", "wtxoecjwgidykpzqpoyo", "ihdrslkxaiyfts", "pkdoset", "exzomsmimkmihkmm", "xyujmosovrdofeodbtgk"),
            List.of("baca", "zchwec", "cmlynatt", "yidwjziypv", "drpexdmkedbhb", "xyujmosovrdofeodbtgk", "exzomsmimkmihkmm", "xtd", "gpdpuumnz", "wzvwahqz", "hdv", "uxvtihiuhq", "hxzdyb", "uhd", "ihdrslkxaiyfts", "tvywkdxscbbbikp", "loxoveaicczyxigmaj", "sqywrpmjeirjprhob", "jucbk", "skzwccwbldwxgfy", "kgkscbawfl", "rkdzwmqop", "mttsaespvuy", "ofafsounesqcze", "nvxwhsa", "npadhjfaxnmubnqb", "ortcqgcpnnxo", "jhyoqmmjvwhzjt", "rqpsyqngcla", "kfvasuaykfksxbn", "slamwxmfaloiu", "jrgqrf", "tdaekeepymhjupjksft", "jdjpuyifekhegvfcbxf", "ubeluohssl", "hyxidpvwxmxr", "uilskyikbkfhmuurc", "hqpsnrqaytsfghufaix", "wx", "hbah", "xp", "fi", "xuugsfwruunaep", "edmbyyoateykys", "ydvefxzoilypq", "dkap", "zbxtrctectv", "bjsqtmekxyylv", "zvrdggvblcqhcyenpdnh"),
            List.of("jdjpuyifekhegvfcbxf", "ytqyzmusayeyjq", "mcrtpn", "wtxoecjwgidykpzqpoyo", "put", "uilskyikbkfhmuurc", "ubeluohssl", "rkdzwmqop", "xuugsfwruunaep")
        );

        for (List<String> seznam: seznami) {
            System.out.println(Cetrta.alternirajoceMonotono(seznam, comp));
        }
    }
}
