
import java.util.*;

public class Test42 {

    public static void main(String[] args) {
        List<List<String>> seznami = new ArrayList<>();

        seznami.add(List.of("MJ", "ekBhJOS", "PgacVw", "2LM", "W", "t", "O", "PgacVw", "kj8u", "pMchSSg", "ekBhJOS", "kxusj", "yndPue5", "VdNXICj", "lY", "Luw2__", "SpUyp", "n5X", "Luw2__", "O", "7SaurEa", "ePdAfl", "k2EGG7q", "Rcs", "GX", "kt", "DW", "CttvWyu", "kj8u", "Df", "jqIaRmy", "ANMLQ", "hv", "ePdAfl", "__PGVW", "ys", "t", "GIl", "CttvWyu", "k2EGG7q", "Rcs", "yndPue5", "iqXg", "ANMLQ", "ekBhJOS", "lY", "kt", "VjA", "kj8u", "8_", "W", "8_", "ePdAfl", "Df", "W", "Df", "VdNXICj", "kxusj", "SpUyp", "CttvWyu", "hv", "4L", "kt", "VjA", "4L", "kt", "kj8u", "VdNXICj", "iBHHP6", "kxusj", "kxusj", "4L", "ys", "UH", "CttvWyu", "O", "5V55BdB", "5V55BdB", "GX", "yT5E38O", "nM_VP", "G4ItsC", "4L", "5V55BdB", "igsXG_1", "MJ", "n5X", "__PGVW", "__PGVW", "LN", "GX", "yT5E38O", "kt", "4_AB", "yT5E38O", "kj8u", "hv", "kt", "kxusj", "ePdAfl", "Luw2__", "4_AB", "kxusj", "igsXG_1", "G4ItsC", "jqIaRmy", "k2EGG7q", "PgacVw", "pMchSSg", "PgacVw", "GIl", "LN", "igsXG_1", "5V55BdB", "n5X", "jqIaRmy", "Luw2__", "kt", "kxusj", "PgacVw"));
        seznami.add(List.of("XpPE", "XpPE", "5V55BdB", "W", "P", "Egp", "ePdAfl", "Qac", "44MV2", "nM_VP", "XpPE", "CttvWyu", "ePdAfl", "SbuEbc", "h", "iBHHP6", "2LM", "piY", "t2", "aW4", "b", "jO", "Gq2Eq2F", "kNSoJr", "GX", "yndPue5", "qR", "PgacVw", "0fWlG6", "4QB5Oy0", "VKaJ0", "bggWawT", "0fWlG6", "rMd", "qR", "VjA", "W", "iqXg", "6VF", "7SaurEa", "5V55BdB", "igsXG_1", "iqXg", "Luw2__", "Mn", "bggWawT", "qoO", "t", "44MV2", "VdNXICj", "t2", "DVOn", "3x", "4L", "O", "VjA", "oERtsU", "MJ", "piY", "4L", "2LM", "b", "pMchSSg", "VdNXICj", "xl", "XmDie", "fiPD", "UH", "Df", "lY", "44MV2", "5V55BdB", "yT5E38O", "megQ1", "rMd", "eIH", "WBp3h", "k2EGG7q", "pMchSSg", "G4ItsC", "h", "n5X", "fWOo5eP", "igsXG_1", "pUd", "Y_X48", "jqIaRmy", "n5X", "t2", "SbuEbc", "E7Lc0Hj", "iBHHP6", "igsXG_1", "fiPD", "P", "Df", "6VF", "oERtsU", "yndPue5", "ePdAfl", "Y_X48", "pMchSSg", "pMchSSg", "fiPD", "bggWawT", "Gq2Eq2F", "xl", "3x", "kNSoJr", "Gq2Eq2F", "DW", "G4ItsC", "jO", "2LM", "yndPue5", "1wBBQ", "Mn", "W", "44MV2", "4QB5Oy0", "7SaurEa", "DW", "BgTN", "xBUu", "Mn", "hv", "3x", "lY", "hv", "5V55BdB", "6VF", "T6bD", "XmDie", "aW4", "ekBhJOS", "ML", "aW4", "WBp3h", "megQ1", "iBHHP6", "GX", "pMchSSg", "W", "fWOo5eP", "evEWsmA", "Qac", "jO", "jO", "pMchSSg", "MJ", "MJ", "VKaJ0", "kj8u", "pUd", "ePdAfl", "aW4", "fiPD", "megQ1", "megQ1", "eIH", "4L", "n5X", "ekBhJOS", "kj8u", "WBp3h", "cxXQSqt", "T6bD", "1wBBQ", "qR", "Mdq4v", "kj8u", "oERtsU", "qoO", "Rcs", "rMd", "oERtsU", "jO", "t", "jqIaRmy", "iBHHP6", "Mdq4v", "WBp3h", "Y_X48", "kj8u", "3x", "evEWsmA", "kNSoJr", "LN", "PgacVw", "qoO", "G4ItsC", "yT5E38O", "fiPD", "yT5E38O", "Egp", "fWOo5eP", "Luw2__", "cxXQSqt", "4L", "ys", "6VF", "7SaurEa", "Gq2Eq2F", "Y_X48", "P", "LN", "xBUu", "PgacVw", "k2EGG7q", "hv", "u0", "T6bD", "iBHHP6", "4QB5Oy0", "1wBBQ", "UH", "igsXG_1", "aW4", "yT5E38O", "igsXG_1", "GX", "VjA", "piY", "xBUu", "megQ1", "jqIaRmy", "oERtsU", "VKaJ0", "ANMLQ", "ML", "lY"));
        seznami.add(List.of("4_AB", "BgTN", "5hRal", "5hRal", "8_", "ys", "piY", "G4ItsC", "ys", "megQ1", "VdNXICj", "jO", "4QB5Oy0", "jqIaRmy", "sFXLhq", "LN", "cxXQSqt", "1wBBQ", "JWX1", "G4ItsC", "1wBBQ", "fWOo5eP", "1wBBQ", "4_AB", "jO", "3R7h", "piY", "megQ1", "SbuEbc", "DVOn", "4L", "UH", "pXytJ", "SbuEbc", "0fWlG6", "qoO", "Luw2__", "8_", "k2EGG7q", "UH", "pXytJ", "4QB5Oy0", "3R7h", "44MV2", "JWX1", "megQ1", "Q_tr0Y", "DVOn", "Q_tr0Y", "PVgSP", "4_AB", "4_AB", "sFXLhq", "jqIaRmy", "__PGVW", "fWOo5eP", "P", "1wBBQ", "pXytJ", "piY", "BgTN", "ML", "GX", "sFXLhq", "fWOo5eP", "3R7h", "Luw2__", "aW4", "G4ItsC", "MJ", "qoO", "0fWlG6", "G4ItsC", "5hRal", "ys", "5hRal", "8_", "44MV2", "pXytJ", "1wBBQ", "0fWlG6", "2LM", "xl", "h", "h", "cxXQSqt", "k2EGG7q", "k2EGG7q", "GX", "UH", "5hRal", "JWX1"));
        seznami.add(List.of("CttvWyu", "4L", "fWOo5eP", "xl", "pXytJ", "fiPD", "DVOn", "eIH", "fiPD", "DVOn", "DVOn", "fWOo5eP", "SbuEbc", "ePdAfl", "CttvWyu", "Egp", "4L", "pXytJ", "fiPD", "4HT5", "MJ", "GIl", "SbuEbc", "4HT5", "ePdAfl", "aW4", "CttvWyu", "4L", "Egp", "4HT5"));
        seznami.add(List.of("evEWsmA", "URY", "VjA", "ePdAfl", "pMchSSg", "4HT5", "jO", "ML", "7SaurEa", "E7Lc0Hj", "qR", "Y_X48", "iBHHP6", "Rcs", "kt", "5hRal", "GX", "fWOo5eP", "jqIaRmy", "rMd", "ANMLQ", "Egp", "kNSoJr", "Luw2__", "LN", "sFXLhq", "3R7h", "__PGVW", "lY", "3R7h", "3x", "PgacVw", "Rcs", "Egp", "xBUu", "T6bD", "DVOn", "pXytJ", "PgacVw", "h", "VjA", "h", "yT5E38O", "eIH", "4QB5Oy0", "fWOo5eP", "W", "piY", "kt", "Mn", "Gq2Eq2F", "eIH", "Mn", "PgacVw", "k2EGG7q", "Df", "Q_tr0Y", "1wBBQ", "VKaJ0", "cxXQSqt", "5V55BdB", "fWOo5eP", "xBUu", "ePdAfl", "Rcs", "_r7", "6VF", "P", "6VF", "Q_tr0Y", "oERtsU", "44MV2", "4HT5", "hv", "VdNXICj", "iqXg", "jqIaRmy", "7SaurEa", "oERtsU", "4QB5Oy0", "piY", "Qac", "LN", "4L", "SpUyp", "qoO", "oERtsU", "URY", "rMd", "kxusj", "ekBhJOS", "DW", "5V55BdB", "b", "n5X", "yT5E38O", "O", "yndPue5", "SbuEbc", "ePdAfl", "ys", "b", "eIH", "5hRal", "aW4", "qoO", "megQ1", "cxXQSqt", "4_AB", "xl", "Egp", "Gq2Eq2F", "PVgSP", "pUd", "JWX1", "XmDie", "BgTN", "CttvWyu", "t", "xBUu", "DVOn", "ePdAfl", "VdNXICj", "URY", "kxusj", "G4ItsC", "Luw2__", "E7Lc0Hj", "UH", "Qac", "8_", "kj8u", "OE2nG", "pMchSSg", "fiPD", "qR", "2LM", "0fWlG6", "igsXG_1", "SpUyp", "4QB5Oy0", "MJ", "1wBBQ", "nM_VP", "LN", "t", "u0", "4QB5Oy0", "kxusj", "n5X"));
        seznami.add(List.of("XmDie", "Egp", "ys", "oERtsU", "VKaJ0", "oERtsU", "u0", "xBUu", "u0", "Df", "Q_tr0Y", "iBHHP6", "VKaJ0", "u0", "iBHHP6", "XmDie", "VKaJ0", "Egp", "aW4", "ML", "aW4", "W", "Df", "Q_tr0Y", "GX", "xBUu", "oERtsU", "cxXQSqt", "ys", "oERtsU", "aW4", "ML", "Egp", "GX", "Y_X48", "u0", "Df", "VKaJ0", "XmDie", "Df", "oERtsU", "xBUu", "xBUu", "GX", "aW4", "ys", "aW4"));
        seznami.add(List.of("ML", "CttvWyu", "T6bD", "2LM", "t", "CttvWyu", "WBp3h", "SbuEbc", "b", "t", "2LM", "VdNXICj", "cxXQSqt", "t2", "PVgSP", "3x", "pUd", "evEWsmA", "pUd", "Rcs", "t2", "P", "megQ1", "PVgSP", "megQ1", "7SaurEa", "megQ1", "3x", "u0", "eIH", "oERtsU", "PgacVw", "3R7h", "jO", "oERtsU", "Gq2Eq2F", "xBUu", "GIl", "t2", "jO", "n5X", "3R7h", "yT5E38O", "t2", "qoO", "rMd", "W", "hv", "oERtsU", "kNSoJr", "b", "3x", "OE2nG", "rMd", "ANMLQ", "n5X", "GIl", "hv", "2LM", "jO", "LN", "XpPE", "W", "LN", "WBp3h", "cxXQSqt", "CttvWyu", "GIl", "VdNXICj", "eIH", "P", "2LM", "GIl", "3R7h", "WBp3h", "LN", "oERtsU", "CttvWyu", "XpPE", "LN", "VdNXICj", "SbuEbc", "megQ1", "Rcs", "b", "LN", "xBUu", "u0", "XpPE", "evEWsmA", "GIl", "2LM", "PVgSP", "t2", "t", "ANMLQ", "Gq2Eq2F", "eIH", "n5X", "XpPE", "yT5E38O", "3x", "T6bD", "ANMLQ"));
        seznami.add(List.of("kNSoJr", "Qac", "SbuEbc", "0fWlG6", "iBHHP6", "SbuEbc", "VKaJ0", "jO", "iBHHP6", "iBHHP6", "VKaJ0", "pMchSSg", "jO", "sFXLhq", "Qac", "ys", "cxXQSqt", "VKaJ0", "VKaJ0", "kNSoJr", "ys", "SbuEbc", "SbuEbc", "cxXQSqt", "sFXLhq"));
        seznami.add(List.of("jO", "UH", "XpPE", "Mdq4v", "3x", "jO", "UH", "Rcs", "oERtsU", "GIl", "yndPue5", "bggWawT", "Gq2Eq2F", "Df", "bggWawT", "u0", "VjA", "CttvWyu", "Df", "XpPE", "bggWawT", "Df", "3x", "_r7", "ekBhJOS", "jO", "0fWlG6", "3x", "Df", "VjA", "VjA", "n5X", "4_AB", "3x", "bggWawT", "0fWlG6", "3x", "4_AB", "n5X", "n5X", "yndPue5", "Df", "nM_VP", "bggWawT", "ePdAfl", "bggWawT", "ePdAfl", "qR", "3x", "PgacVw"));
        seznami.add(List.of("nM_VP", "pMchSSg", "4L", "kNSoJr", "jqIaRmy", "7SaurEa", "W", "aW4", "T6bD", "W", "qR", "4QB5Oy0", "iqXg", "rMd", "Df", "kNSoJr", "ys", "igsXG_1", "7SaurEa", "kNSoJr", "ys", "Luw2__", "2LM", "Df", "MJ", "pMchSSg", "megQ1", "t", "0fWlG6", "eIH", "n5X", "nM_VP", "W", "Luw2__", "t2", "UH", "GIl", "ys", "pUd", "kj8u", "h", "SbuEbc", "XmDie", "MJ", "oERtsU", "Gq2Eq2F", "BgTN", "CttvWyu", "44MV2", "44MV2", "3R7h", "kxusj", "h", "ys", "0fWlG6", "xl", "5V55BdB", "fiPD", "jqIaRmy", "Gq2Eq2F", "Q_tr0Y", "kNSoJr", "5V55BdB", "Q_tr0Y", "DVOn", "iqXg", "G4ItsC", "VdNXICj", "8_", "W", "Q_tr0Y", "4QB5Oy0", "VdNXICj", "pUd", "3R7h", "eIH", "kNSoJr", "n5X", "lY", "UH", "pUd", "kj8u", "iqXg", "yndPue5", "PgacVw", "XmDie", "CttvWyu", "PgacVw", "kxusj", "BgTN", "t2", "MJ", "xl"));
        seznami.add(List.of("4QB5Oy0", "BgTN", "8_", "DVOn", "rMd", "BgTN", "DVOn", "4QB5Oy0", "4QB5Oy0", "8_", "Luw2__", "8_", "Luw2__", "rMd", "BgTN", "BgTN", "8_", "4QB5Oy0"));
        seznami.add(List.of("oERtsU", "ekBhJOS", "kt", "Df", "piY", "qoO", "UH", "XpPE", "XpPE", "BgTN", "XpPE", "SbuEbc", "hv", "xBUu", "PgacVw", "SpUyp", "E7Lc0Hj", "4_AB", "Rcs", "CttvWyu", "4_AB", "WBp3h", "b", "URY", "h", "pMchSSg", "bggWawT", "xBUu", "VKaJ0", "qR", "4_AB", "b", "W", "t", "Luw2__", "6VF", "yndPue5", "WBp3h", "fWOo5eP", "yndPue5", "xBUu", "rMd", "yT5E38O", "URY", "pXytJ", "5V55BdB", "eIH", "fWOo5eP", "ekBhJOS", "UH", "Gq2Eq2F", "fiPD", "eIH", "URY", "kNSoJr", "5V55BdB", "Mdq4v", "3R7h", "piY", "E7Lc0Hj", "PVgSP", "Egp", "PgacVw", "eIH", "b", "aW4", "jqIaRmy", "_r7", "GIl", "pXytJ", "CttvWyu", "URY", "DVOn", "UH", "t2", "4_AB", "SbuEbc", "JWX1", "n5X", "oERtsU", "XpPE", "yndPue5", "cxXQSqt", "jqIaRmy", "Luw2__", "b", "hv", "qR", "Rcs", "fiPD", "__PGVW", "0fWlG6", "megQ1", "XpPE", "pXytJ", "Mdq4v", "5hRal", "kt", "t", "E7Lc0Hj", "GX", "ekBhJOS", "evEWsmA", "bggWawT", "4_AB", "E7Lc0Hj", "qoO", "O", "Luw2__", "3x", "kNSoJr", "ANMLQ", "cxXQSqt", "Df", "VKaJ0", "ML", "t2", "pMchSSg", "CttvWyu", "oERtsU", "pMchSSg", "pMchSSg", "fWOo5eP", "kNSoJr", "pMchSSg", "_r7", "kNSoJr", "E7Lc0Hj", "igsXG_1", "yndPue5", "1wBBQ", "xBUu", "nM_VP", "jO", "u0", "LN", "BgTN", "b", "piY", "oERtsU", "oERtsU", "megQ1", "jqIaRmy", "PgacVw", "h", "LN", "Q_tr0Y", "Egp", "fiPD", "ANMLQ", "LN", "nM_VP", "evEWsmA", "SpUyp", "b", "kxusj", "E7Lc0Hj", "pMchSSg", "b", "ANMLQ", "Q_tr0Y", "piY", "6VF", "bggWawT", "h", "eIH"));
        seznami.add(List.of("jqIaRmy", "jO", "VdNXICj", "ekBhJOS", "VKaJ0", "SbuEbc", "W", "GX", "aW4", "VKaJ0", "O", "aW4", "P", "Luw2__", "P", "UH", "kt", "ys", "Egp", "bggWawT", "Egp", "bggWawT", "kt", "Df", "44MV2", "VKaJ0", "n5X", "O", "Df", "XpPE", "bggWawT", "jqIaRmy", "Egp", "GX", "pMchSSg", "44MV2", "bggWawT", "MJ", "4_AB", "GIl", "pMchSSg", "Luw2__"));
        seznami.add(List.of("DVOn", "aW4", "G4ItsC", "T6bD", "Mdq4v", "Mdq4v", "aW4", "b", "XmDie", "SpUyp", "XmDie", "b", "ekBhJOS", "qR", "2LM", "DVOn", "ekBhJOS", "GX", "6VF", "2LM", "DVOn", "8_", "4L", "6VF", "2LM", "megQ1", "piY", "ePdAfl", "piY", "oERtsU", "megQ1", "GX", "oERtsU", "2LM", "oERtsU", "8_", "8_", "ekBhJOS", "T6bD", "SpUyp", "ePdAfl", "DVOn", "SpUyp", "megQ1"));
        seznami.add(List.of("DW", "ePdAfl", "yndPue5", "u0", "P", "cxXQSqt", "evEWsmA", "Luw2__", "qR", "fiPD", "44MV2", "UH", "fiPD", "5V55BdB", "T6bD", "fiPD", "jO", "VdNXICj", "eIH", "E7Lc0Hj", "BgTN", "P", "jqIaRmy", "h", "cxXQSqt", "hv", "aW4", "kt", "Rcs", "2LM", "4L", "LN", "qoO", "Mn", "igsXG_1", "ys", "_r7", "kt", "jO", "fiPD", "CttvWyu", "Qac", "UH", "8_", "4_AB", "Rcs", "O", "URY", "Gq2Eq2F", "44MV2", "bggWawT", "Q_tr0Y", "ML", "44MV2", "Egp", "UH", "Mdq4v", "0fWlG6", "eIH", "eIH", "h", "qR", "O", "XpPE", "8_", "T6bD", "kt", "lY", "ys", "Luw2__", "sFXLhq", "GX", "megQ1", "ML", "Egp", "URY", "Egp", "yndPue5", "3R7h", "pMchSSg", "u0", "ANMLQ", "6VF", "u0", "PVgSP", "GIl", "WBp3h", "URY", "fWOo5eP", "xBUu", "4QB5Oy0", "CttvWyu", "5V55BdB", "t2", "3x", "kt", "yT5E38O", "kj8u", "5hRal", "jO", "qoO", "O", "5V55BdB", "E7Lc0Hj", "T6bD", "5hRal", "t2", "XmDie", "qoO", "nM_VP", "t", "2LM", "5V55BdB", "qoO", "ePdAfl", "pUd", "xBUu", "k2EGG7q", "lY", "GX", "5V55BdB", "fiPD", "44MV2", "PgacVw", "u0", "pUd", "t2", "qR", "4QB5Oy0", "xBUu", "yndPue5", "Q_tr0Y", "t", "__PGVW", "GX", "3x", "kt", "yT5E38O", "O", "kj8u", "44MV2", "VdNXICj", "PgacVw", "Qac", "fWOo5eP", "piY", "ys", "jqIaRmy", "t2", "3x", "fiPD", "2LM"));
        seznami.add(List.of("qR", "Q_tr0Y", "fiPD", "kj8u", "ANMLQ", "ekBhJOS", "JWX1", "4_AB", "7SaurEa", "_r7", "kj8u", "2LM", "4_AB", "T6bD", "n5X", "lY", "XpPE", "4QB5Oy0", "pXytJ", "t", "hv", "4_AB", "PgacVw", "fiPD", "7SaurEa", "SpUyp", "qR", "44MV2", "SpUyp", "fiPD", "_r7", "PVgSP", "XmDie", "yndPue5", "OE2nG", "iqXg", "XmDie", "__PGVW", "nM_VP", "piY", "MJ", "bggWawT", "CttvWyu", "44MV2", "DVOn", "lY", "BgTN", "Mdq4v", "k2EGG7q", "CttvWyu", "VKaJ0", "Mn", "__PGVW", "4HT5", "VjA", "Egp", "Luw2__", "O", "PgacVw", "4_AB", "yndPue5", "4L", "t", "Rcs", "cxXQSqt", "WBp3h", "xBUu", "iBHHP6", "XpPE", "sFXLhq", "DW", "P", "ePdAfl", "VKaJ0", "T6bD", "4L", "PgacVw", "Qac", "7SaurEa", "Q_tr0Y", "sFXLhq", "Mdq4v", "igsXG_1", "cxXQSqt", "BgTN", "OE2nG", "XmDie", "u0", "1wBBQ", "t2", "kj8u", "SbuEbc", "yT5E38O", "Egp", "cxXQSqt", "PgacVw", "7SaurEa", "cxXQSqt", "P", "u0", "lY", "__PGVW", "G4ItsC", "2LM", "UH", "jO", "rMd", "sFXLhq", "URY", "jqIaRmy", "UH", "evEWsmA", "fWOo5eP", "0fWlG6", "qoO", "megQ1", "5hRal", "PVgSP", "JWX1", "cxXQSqt", "ePdAfl", "ys", "6VF", "5hRal", "T6bD", "__PGVW", "lY", "LN", "5V55BdB", "Y_X48", "UH", "kNSoJr", "fiPD", "ekBhJOS", "oERtsU", "oERtsU", "jO", "kxusj", "_r7", "8_", "DVOn", "GX", "SbuEbc", "nM_VP", "DVOn", "0fWlG6", "igsXG_1"));
        seznami.add(List.of("4QB5Oy0", "XpPE", "fiPD", "5hRal", "ekBhJOS", "Mn", "rMd", "5hRal", "5hRal", "BgTN", "t", "XpPE", "GIl", "_r7", "xBUu", "4L", "h", "cxXQSqt", "__PGVW", "t", "u0", "6VF", "h", "fiPD", "PgacVw", "lY", "Luw2__", "kj8u", "URY", "6VF", "h", "h", "6VF", "4L", "fiPD", "ekBhJOS", "fiPD", "lY", "GIl", "VjA", "jO", "BgTN", "44MV2", "xBUu", "cxXQSqt", "XpPE", "4QB5Oy0", "Mn", "VjA", "GIl", "cxXQSqt", "URY", "xBUu", "igsXG_1", "qR", "__PGVW"));
        seznami.add(List.of("fWOo5eP", "t", "JWX1", "aW4", "hv", "_r7", "BgTN", "URY", "xBUu", "n5X", "Y_X48", "kNSoJr", "Q_tr0Y", "P", "ePdAfl", "aW4", "G4ItsC", "ekBhJOS", "PgacVw", "qR", "VKaJ0", "sFXLhq", "1wBBQ", "yndPue5", "k2EGG7q", "XpPE", "iBHHP6", "XmDie", "UH", "Mdq4v", "W"));
        seznami.add(List.of("piY", "MJ", "iBHHP6", "ekBhJOS", "Mn", "ML", "8_", "4QB5Oy0", "BgTN", "hv", "CttvWyu", "JWX1", "b", "iqXg", "Mn", "lY", "igsXG_1", "yT5E38O", "GX", "SbuEbc", "pMchSSg", "u0", "3R7h", "Mn", "Rcs", "Egp", "T6bD", "yndPue5", "jqIaRmy", "megQ1", "b", "6VF", "piY", "7SaurEa", "3x", "kxusj", "megQ1", "XmDie", "ys", "44MV2", "Mn", "Y_X48", "kj8u", "megQ1", "3x", "xBUu", "SpUyp", "1wBBQ", "Qac", "Luw2__", "oERtsU", "yndPue5", "6VF", "fiPD", "__PGVW", "__PGVW", "4_AB", "Gq2Eq2F", "kj8u", "CttvWyu", "UH", "t2", "fiPD", "pUd", "Df"));
        seznami.add(List.of("kj8u", "__PGVW", "kt", "Df", "xl", "7SaurEa", "CttvWyu", "Q_tr0Y", "7SaurEa", "Q_tr0Y", "OE2nG", "xBUu", "sFXLhq", "bggWawT", "VjA", "W", "__PGVW", "xBUu", "Q_tr0Y", "xBUu", "MJ", "6VF", "__PGVW", "kt", "OE2nG", "Df", "W", "__PGVW", "bggWawT", "sFXLhq", "xl", "kxusj", "7SaurEa", "44MV2", "44MV2", "sFXLhq", "VjA", "Df", "7SaurEa", "Df", "6VF", "__PGVW", "sFXLhq", "OE2nG", "OE2nG", "__PGVW", "7SaurEa"));
        seznami.add(List.of("LN", "URY", "lY", "qR", "GIl", "t2", "Y_X48", "DVOn", "t2", "BgTN", "XpPE", "ML", "URY", "ekBhJOS", "OE2nG", "XpPE", "iBHHP6", "b", "pXytJ", "oERtsU", "jqIaRmy", "O", "GX", "Q_tr0Y", "iBHHP6", "iBHHP6", "pUd", "4L", "hv", "sFXLhq", "kj8u", "5V55BdB", "CttvWyu", "ANMLQ", "kNSoJr", "URY", "BgTN", "iqXg", "b", "DVOn", "44MV2", "__PGVW", "kt", "ekBhJOS", "SbuEbc", "megQ1", "Rcs", "Mn", "jO", "SbuEbc", "4QB5Oy0", "E7Lc0Hj", "UH", "0fWlG6", "PVgSP", "bggWawT", "b", "XpPE", "yndPue5", "igsXG_1", "XmDie", "44MV2", "__PGVW", "igsXG_1", "ML", "LN", "yT5E38O", "t2", "Egp", "5V55BdB", "h", "rMd", "b", "2LM", "pMchSSg", "pXytJ", "OE2nG", "0fWlG6", "PVgSP", "O", "t2", "cxXQSqt", "yT5E38O", "Gq2Eq2F", "lY", "pUd", "hv", "oERtsU", "Q_tr0Y", "Mdq4v", "VdNXICj"));
        seznami.add(List.of("igsXG_1", "yT5E38O", "DW", "VdNXICj", "CttvWyu", "hv", "6VF", "t", "piY", "4HT5", "1wBBQ", "pMchSSg", "h", "1wBBQ", "n5X", "5hRal", "kxusj", "SpUyp", "SpUyp", "rMd", "SbuEbc", "t2", "JWX1", "eIH", "SbuEbc", "SbuEbc", "bggWawT", "CttvWyu", "6VF", "Mn", "yT5E38O", "_r7", "evEWsmA", "Qac", "h", "4L", "1wBBQ", "kj8u", "4_AB", "eIH", "Egp", "E7Lc0Hj", "4HT5", "UH", "3x", "GX", "megQ1", "VjA", "T6bD", "DVOn", "yndPue5", "pMchSSg", "t", "Egp", "URY", "ekBhJOS", "6VF", "Mdq4v", "fWOo5eP", "qR", "ekBhJOS", "P", "4_AB", "URY", "fWOo5eP", "Mdq4v", "yT5E38O", "E7Lc0Hj", "PVgSP", "eIH", "yT5E38O", "cxXQSqt", "kxusj", "hv", "ML", "Mn", "hv", "pXytJ", "SbuEbc", "Qac", "4L", "piY", "UH", "P", "GIl", "DW", "DW", "VKaJ0", "Q_tr0Y", "pXytJ", "rMd", "VdNXICj", "Qac", "Egp", "Mn", "WBp3h", "Df", "PgacVw", "Rcs", "T6bD", "DVOn", "pXytJ", "6VF", "kt", "kxusj", "7SaurEa", "hv", "DVOn", "VdNXICj", "3x", "fiPD", "WBp3h", "t", "_r7", "bggWawT", "PgacVw", "URY", "ML", "GIl", "igsXG_1", "nM_VP", "n5X", "P", "P", "PVgSP", "4HT5", "igsXG_1", "PVgSP", "t2", "Y_X48", "nM_VP", "JWX1", "G4ItsC", "WBp3h", "SbuEbc", "4HT5", "Mn", "JWX1", "Mdq4v", "evEWsmA", "Y_X48", "VKaJ0", "44MV2", "W", "megQ1", "1wBBQ", "DW", "T6bD", "P", "sFXLhq", "hv", "pMchSSg", "pMchSSg"));
        seznami.add(List.of("__PGVW", "GX", "XmDie", "VKaJ0", "4L", "XpPE", "44MV2", "GIl", "iqXg", "k2EGG7q", "Df", "xl", "G4ItsC", "Luw2__", "XmDie", "yT5E38O", "MJ", "pUd", "PVgSP", "pMchSSg", "fWOo5eP", "h", "0fWlG6", "t2", "kNSoJr", "kt", "PgacVw", "7SaurEa", "Mn", "lY", "CttvWyu", "rMd", "VdNXICj", "4L", "oERtsU", "u0", "qR", "4QB5Oy0", "2LM", "yndPue5", "qoO", "ANMLQ", "LN", "kxusj", "T6bD", "cxXQSqt", "8_", "nM_VP", "jO", "3x", "megQ1", "igsXG_1", "Egp", "ML", "Mdq4v", "VjA", "WBp3h", "iBHHP6", "O", "SpUyp", "Qac", "evEWsmA", "jqIaRmy", "Y_X48", "aW4", "kt", "ekBhJOS", "b", "iqXg", "URY", "5hRal", "BgTN", "XpPE"));
        seznami.add(List.of("qR", "ekBhJOS", "5V55BdB", "0fWlG6", "Gq2Eq2F", "kj8u", "yT5E38O", "Y_X48", "3x", "Mn", "pMchSSg", "DW", "k2EGG7q", "OE2nG", "SpUyp", "lY", "kj8u", "kt", "cxXQSqt", "VdNXICj", "SpUyp", "JWX1", "4QB5Oy0", "Mdq4v", "0fWlG6", "E7Lc0Hj", "6VF", "eIH", "8_", "4L", "aW4", "44MV2", "DW", "u0", "ys", "Mdq4v", "_r7", "MJ", "5hRal", "megQ1", "kt", "n5X", "Qac", "xBUu", "4HT5", "XmDie", "T6bD", "Y_X48", "oERtsU", "DVOn", "ePdAfl", "DVOn", "6VF", "WBp3h", "44MV2", "DW", "Gq2Eq2F", "VdNXICj", "Y_X48", "6VF", "hv", "UH", "ys", "ANMLQ", "W", "k2EGG7q", "pUd", "BgTN", "pUd", "VKaJ0", "XmDie", "jO", "GIl", "8_", "fiPD", "qR", "4QB5Oy0", "ys", "O", "GIl", "44MV2", "t2", "h", "iqXg", "3R7h", "h", "Qac", "3x", "CttvWyu", "cxXQSqt", "kj8u", "Mn", "kxusj", "SbuEbc", "4QB5Oy0", "5hRal", "igsXG_1", "kj8u", "XpPE", "lY", "piY", "T6bD", "ANMLQ", "Mdq4v", "yndPue5", "Egp", "sFXLhq", "O", "UH", "b", "4_AB", "0fWlG6", "6VF", "cxXQSqt", "SbuEbc", "PgacVw", "T6bD", "XpPE", "WBp3h", "URY", "pUd", "oERtsU", "Luw2__", "cxXQSqt", "qR", "t", "PVgSP", "ys", "Q_tr0Y", "sFXLhq", "eIH", "2LM", "T6bD", "0fWlG6", "ekBhJOS", "xBUu", "jO", "ML", "XpPE", "LN", "Mn", "LN", "GX", "iqXg", "4HT5", "Q_tr0Y", "PVgSP", "7SaurEa", "Rcs", "Gq2Eq2F", "SpUyp", "1wBBQ", "cxXQSqt", "DW", "4_AB", "JWX1", "G4ItsC", "yndPue5", "4QB5Oy0", "ML", "0fWlG6", "0fWlG6", "SbuEbc", "yT5E38O", "ePdAfl", "Df", "5hRal", "4QB5Oy0", "jqIaRmy", "jqIaRmy", "b", "LN", "4HT5", "xl", "pXytJ", "3x", "yT5E38O", "0fWlG6", "eIH", "iBHHP6", "5V55BdB", "qoO", "WBp3h", "4HT5", "kxusj", "SpUyp", "yT5E38O", "PVgSP", "3R7h", "evEWsmA", "O", "kt", "xl", "fiPD", "DVOn", "UH", "aW4", "O", "44MV2", "GX", "ekBhJOS", "pXytJ", "n5X", "PgacVw", "oERtsU", "jO", "T6bD", "__PGVW", "yT5E38O", "Egp", "yndPue5", "t", "Mn", "5V55BdB", "ekBhJOS", "lY", "PgacVw", "kj8u", "rMd", "jO", "sFXLhq", "fiPD", "4_AB", "rMd", "O", "iqXg", "Egp", "Gq2Eq2F", "bggWawT", "ANMLQ", "h", "0fWlG6", "jO", "DVOn", "bggWawT", "JWX1", "7SaurEa", "44MV2", "_r7", "XmDie", "Qac", "evEWsmA"));
        seznami.add(List.of("XmDie", "XpPE", "SpUyp", "eIH", "URY", "XmDie", "URY", "XpPE", "CttvWyu", "SpUyp", "eIH", "yndPue5", "XmDie", "eIH"));
        seznami.add(List.of("kj8u", "lY", "T6bD", "VKaJ0", "xBUu", "URY", "_r7", "1wBBQ", "SbuEbc", "URY", "44MV2", "b", "t", "ePdAfl", "t2", "iBHHP6", "4L", "_r7", "iBHHP6", "megQ1", "oERtsU", "Egp", "G4ItsC", "piY", "qoO", "lY", "Qac", "OE2nG", "Qac", "Y_X48", "xBUu", "piY", "u0", "XpPE", "XpPE", "t2", "lY", "SbuEbc", "piY", "kt", "eIH", "u0", "pUd", "ePdAfl", "Df", "yndPue5", "piY", "Df", "_r7", "URY", "xBUu", "UH", "VdNXICj", "SbuEbc", "PVgSP", "qoO", "4QB5Oy0", "hv", "ePdAfl", "eIH", "W", "1wBBQ", "ML", "kt", "3x", "xBUu", "b", "1wBBQ", "44MV2", "b", "Q_tr0Y", "ePdAfl", "SbuEbc", "ML", "XpPE", "VjA", "nM_VP", "pXytJ", "Y_X48", "Df", "piY", "ML", "4L", "_r7", "VdNXICj", "3x", "4QB5Oy0", "Q_tr0Y", "Egp", "G4ItsC", "ePdAfl", "iBHHP6", "44MV2", "WBp3h", "kNSoJr", "4QB5Oy0", "Egp", "G4ItsC", "URY", "GX", "kNSoJr", "pUd", "hv", "O", "1wBBQ", "Rcs", "b", "O", "yndPue5", "megQ1", "W"));

        Cetrta.poDolziniBrezDuplikatov(seznami);

        for (List<String> seznam: seznami) {
            System.out.println(seznam);
        }
    }
}
