[a, a, a]
[w, 2, L, A, 2, P]
[j, d, o, 4, u, _]
[m, j, 2, 6, u, m, m, B, 2, 2, m, u, G, u, m]
[L, o, q, T, I, t, t, n, 4, U, o, q, n, 1]
[q, A, X, g, E, 1, 1, Q, q, Q, Q, q, g, U, r, X, A, Q, X, X, r, r, U, Q, 1, E, a, X, m, q]
[R, V, D, V, D, R, 1, 8, 8, V, 1, 8, k, 3, F, W, Y, 1, D, S, X, a, k, S, D, d, 3, Y, W, F, Y, D, R, d, V, S, W, S, D, W, a]
[V, W, Y, m, D, d, m, a, H, x, r, x, q, S, x, x, H, d, O, V, W, Q, Q, a, r, a, W, V, S, T, O, D, r]
[j, y, 2, 2, H, W, 3, 6, D, c, x, T, 3, W, o, g, o, B, B, v, G, v, S, T]
[X, 5, i, L, N, E, l, E, 0, f, E, B, 4, a, R, g, X, N, i, B, 2, a, R, h, B, h, A, E, N, 4, g, X, 0, A, P, 5, 2, g, 4, 2, P, h, l, B, E, R, R, A, f, 0, l, l, E]
[6, 4, 8, p, j, l, 4, M, G, K, p, p, x, G, K, o, d, 8, _, l, p, v, p, B, f, G, 5, v, 2, P, 6, B, M, _, 6, 2, 6, M, d, o, P]
[j, H, s, m, 8, p, 6, j, X, m, d, w, 8, 4, P, t, j, w, r, n, E, 0, t, H, j, r, b, b, n, P, d, 0, P, 4, t, 4, 1, r, G]
[d, j, j, W, b, A, P, S, r, L, R, L, r, Q, d, J, 3, r, Y, o, w, r, W, H, W, L, S, Y, w, a, m, W, m, j, I, o, 3, R, W, b, N, w, W, W, w, A, d, r, H, b]
[F, K, M, 3, q, J, H, x, 0, s, 6, 0, 3, p, G, o, W, 3, 3, h, T, P, R, 0, S, X, W, H, x, H, K, D, l]
[k, T, G, q, I, t, r, Q, w, L, 7, S, t, q, T, r, m, y, a, c, d, k, r, y, S, W, q, q, I, q, Q, 2, V, 2, y, d, l, 7, 8, X, A, W, A]
[q, E, J, F, I, j, Q, L, p, P, 7, D, D, 0, Q, h, v, p, d, J, 6, v, 7, h, h, q, L, o, p, q, H, o, _, o, M, E, P, A, m, O, m, 0, M, d, r, P, C, A, M, v, A, h]
[R, 6, K, i, 4, M, w, E, g, I, W, W, w, 1, y, W, m, V, 6, f, u, v, g, M, 4, r, e, 5, 1, r, 4, j, r, E, 7, S, 1, j, K, y, E, I, R, P, g, 2, W, P, 5, r, a, 5, E]
[j, O, e, o, h, A, g, G, 4, v, 1, G, n, g, 6, I, g, Q, 7, l, G, p, p, 3, A, I, 3, c, u, Q, E, 1, y, E, j, 1, b, 2, 2, 7, E, n, B, W, O, 2, 3, o, F, 1, A, 6, G]
[k, F, L, b, C, l, G, o, s, R, a, B, N, 1, m, u, K, D, 3, q, g, j, 8, y, a, Y, A, t, 2, 0]
[N, m, x, x, b, A, e, P, i, 7, Q, r, I, Q, v, c, t, h, 3, b, Y, I, f, O, 5, w, 6, a, P, T, c, h, A, v, e, b, I, A, b, Q, t, 4, c, A, f, j, N, 3, q, x, _, x, O, 6, B, j, 4, w, N, T, 7, O, t, B, _, b, O, A, r, c, e, Y, 3, f, A, s, A]
[x, d, Q, 4, q, 4, x, s, t, s, x, d, X, k, C, X, u, V, P, h, v, 4, s, 6, L, q, D, p, v, L, u, B, t, B, 7, C, t, D, L, Y, s, j, q, 0, p, O, 5, V, g, 2, 7, d, 2, Y, c, n, k, t, c, e, p, 3, d, h, 4, v]
[w, A, B, V, 0, 2, A, f, T, 8, M, g, u, F, x, c, K, h, s, 3, M, l, t, _, X, p, y, b, R, Q, 7, 5, 4, Y, N, n, C, I, w, i]
[5, V, W, t, 1, b, C, D, I, I, 7, 5, G, Y, r, w, J, x, p, I, f, O, T, 3, 7, t, M, x, V, C, 1, u, u, v, C, v, w, w, U, Q, D, k, V, T, f, C, o, G, f, s, D, x, G, a, N, u, 4, M, t, I, O, V, W, 4, T, 8, 8, _, B, O, V, W, W, A, x, _, u, D, C, a, N, o, R, u, 8, w, 2, A, M, M, B, I, W, s, Y, W, R, x, R, 6]
[N, 7, H, u, 6, 8, L, 6, u, n, j, Q, t, 1, x, R, 5, n, L, w, m, U, C, t, 1, U, l, J, w, U, Q, Y, x, U, _, i, F, G, S, L, J, l, x, F, 5, A, D, J, r, q, G, Y, j, W, M, t, S, W, J, m, Q, F, E, 7, E, 5, o, 4, i, R, 5, 6, c, 6, Y, 4, h, t, J, w, 1, F, o, U, 3, Y, m, A, l, y, C, u, J, w, E, 1, N, n, Q, D, P, F, y, y, l, t, C, x, _, q, H, u, t, F, F, 5, 4, S]
[k, a, v, M, s, 6, K, 1, x, w, 1, E, C, F, 7, F, x, 6, i, J, 4, P, j, g, b, K, t, X, E, s, k, T, n, Y, i, B, w, i, M, v, u, B, W, 1, j, q, m, x, V, E, M, T, u, l, g, K, L, v, v, n, R, J, l, U, u, B, _, b, y, 2, L, J, q, 8, v, v, F, U, V, 8, S, p, q, p, L, 4, A, H, R, k, T]
[t, P, V, x, p, n, G, F, v, t, d, q, X, y, 7, 6, e, o, 4, _, 3, h, e, W, h, y, h, h, A, c, t, T, _, U, c, V, t, O, g, G, V, l, n, w, Q, 3, P, E, L, W, 7, X, I, j, O, X, N, 7, O, B, g, J, F, v, K, J, 2, U, 4, _, J, 5, F, H, 6, X, t, n, k, n, 5, _, 2, M, t, E, t, Q, g, D, k, D, D, 7]
[k, T, e, i, A, o, q, x, w, 1, h, 6, o, T, T, 0, P, 0, H, S, w, g, n, C, b, h, u, x, a, m, X, a, f, S, k, b, Q, 1, M, u, G, C, 3, 8, q, U, h, u, 1, p, 6, 8, q, w, U, _, X, t, 4, A, S, g, n, e, k, N, H, P, 0, 7, G, S, x, k, D, s, N, w, T, X, V, f, 4, l, f, G, P, I, 1, s, A, n, F, M, t, A, b, V, W, y, m, f, M, N, V, 7, W, D, H, y, D, A, s, 1, D, n, Q, I, m, F, D, B, P, C, M]
[E, i, d, d, 4, f, R, 5, 7, W, a, b, 4, b, T, E, _, r, 3, j, c, p, y, 4, 8, L, f, d, s, K, F, R, l, d, I, X, 2, K, F, o, V, m, c, 5, E, B, r, r, R, o, j, U, 5, K, Y, R, E, d, k, b, Y, S, 0, G, O, M, b, 5, W, B, X, n, J, O, N, r, L, P, v, L, i, p, P, S, B, b, J, 1, N, d, m, V, W, a, U, 3, 0, b, j, A, y, f, 2]
[W, H, 6, n, j, 5, E, P, K, H, G, N, j, M, b, q, 8, a, m, p, Q, g, b, J, h, u, u, l, 6, N, n, m, a, p, C, D, a, W, F, K, 5, t, d, d, l, I, g, Q, h, M, P, X, r, T, D, S, o, d, 3, l, E, G, 5, V, 6, _, N, H, q, j, U, 8, B, H, a, F, M, V, W, r, i, 2, r, V, t, 8, q, o, b, g, w, P, 0, 7, 4, U, a, y, H, 1]
[4, v, f, O, U, g, A, _, k, T, I, e, 5, d, A, L, w, H, t, 7, F, t, u, V, G, Q, g, 8, j, y, M, s, i, R, P, h, V, Y, l, D, P, w, S, j, d, k, D, B, 8, Y, 1, J, f, W, R, t, X, q, e, s, R, E, U, T, e, o, c, n, J, W, J, o, K, a, _, K, n, A, Q, S, P, i, I, 2, m]
[B, 6, h, V, H, G, Y, n, M, 6, 1, E, j, w, 8, d, 0, G, C, X, k, I, q, E, O, K, 3, X, K, S, I, u, r, 4, _, 8, c, n, q, V, 7, n, W, m, W, F, y, y, 4, 4, J, L, v, J, g, Q, g, l, u, D, R, R, t, H, x, T, a, g, U, C, s, x, b, N, L, o, 2, j, v]
[g, _, D, t, A, 3, b, 5, g, u, U, p, N, 0, r, N, l, j, F, h, s, f, J, n, Y, P, I, X, w, q, H, C, y, w, o, 6, t, M, D, 1, _, E, K, 2, c, 4, L, 2, W, l, T, m, d, d, O, 8, 7, i, e, x, Q, G, K, S, 1, a]
[1, h, 4, Q, U, t, h, 5, X, W, t, V, F, j, y, P, o, q, a, S, k, A, T, g, Y, B, u, y, M, 8, b, 3, J, l, p, 0, 5, e, 2, m, D, G, H, O, 6, f, s, 7, x, r, L, n, i, R, 6, E, l, K, L, w, _, L, q, c, d, p, o]
[2, e, E, 6, C, D, t, H, b, m, f, Y, B, b, w, J, 4, r, L, H, 3, O, I, K, T, g, S, K, l, V, d, o, 1, 7, P, R, U, i, n, n, p, A, y, M, a, r, t, F, I, N, q, Q, s, N, X, _, h, u, c, 8, v, G, F, k, n, j, O, W, 5, x, w]
