[]
[N, N, N]
[2, 2, 7, 2, 7, 2]
[Q, n, P]
[X, W, E, E, X, Q, Q, Q]
[D, 6, y, D, y, y, y, 6, i, 6, p, 6, i, 6]
[J, E, _, _, 0, t, J, t, k, E, _]
[o, R, 6, o, J, e, R, _, a, o, a, 6, o, J, 6, 6]
[e, g, X, K, 0, S, M, S, b]
[U, G, 7, j, Y, S, 8, U, G, p, F, F]
[B, O, 4, e, d, e, e, O, A, N, A, n, B, d, D, 4, B, n, t, O, e, n]
[K, W, Y, P, l, S, D, a, K, p, Y, N, p, w, N]
[p, u, 2, 2, m, L, d, C, d, c, j, 1, C, I, 6, c]
[t, 7, Y, 7, I, W, P, Y, 7, 7, e, d, G, y, e, r, r, L, O, e, O, W]
[U, E, G, u, E, p, G, a, x, u, L, i, p, u, k, L, 1, U, G, x, 7, y, W, u, p, L, 7, y, a, u, B, 1, i, x, y, k]
[Y, d, L, d, t, o, g, t, _, g, b, h, u, Y, v, y, c, c, I, p, v, I, f]
[Y, i, 8, g, M, S, _, u, U, S, O, 7, N, x, g, _, M, j, C, e, q, i, x, Y, S, j, u, Y, N, N, _, j, _, U, _, N, M, C, g, C, x, M, 8, U]
[Y, 8, l, _, _, 1, D, O, S, 5, E, 3, h, T, A, _, 5, 3, y, B, _, w, S, K]
[w, K, 8, x, b, s, 4, F, c, R, R, F, H, U, K, M, U, c, s, o, s, F, g, F, w, g, F, b, B, _, B, U, F, L, _, M, 2, _, 8, H, M, R, w, R, w, U, U, 2, M]
[6, K, 0, S, S, h, P, _, h, D, d, J, a, q, M, P, V, 0, P, D, V, L, f, 0, O, _, S, J, M, M, 2, h, y, _, f, B, D]
[h, B, I, Y, W, y, C, c, I, c, y, J, I, J, I, Y, h, J, s, y, W, R, v, s, C, x, f, c, D, B, S, Y, S, 3, 7, Y, I, 3, 4, 4, R, D, N, S, N, C, I, p]
[1, F, Y, Y, i, b, o, Y, U, o, R, B, O, M, m, U, F, B, _, l, _, y, O, S, H, y, R, U, O, L, L, x, O, Y, w, y, i, B, l, M, n, l, B, i, i, x, d, w, 1, L, H, Y, _]
[6, k, n, p, j, T, m, B, x, P, O, H, O, L, t, D, t, S, B, L, U, 2, P, 6, x, t, 5, 7, S, p, s, 5, 2, w, p, U, S, p, U, n, D, j, P, k, 7, u, 5, T, p, j, T, 7, m, 6, s, u, t, m, s, u, T, m, 7, D, j, t, P, x]
[c, Y, W, k, 5, q, a, W, K, M, j, m, s, i, r, 8, T, s, I, 5, s, 1, O, 6, y, L, k, O, p, h, I, K, q, q, r]
[j, J, c, v, r, T, 3, h, x, h, 0, U, 5, S, r, r, e, c, J, 0, I, T, 3, J, v, T, 2, t, J, u, e, v, x, I, I, 2, v, Q, f, l, J, Q, t, x, c, S, N, C, P, 0, 5, T, C, l, a, w, r, P, l, P, I, u, w, P, c]
[0, r, I, q, P, 0, 0, S, U, 2, a, N, 2, U, 0, u, n, L, u, n, T, W, R, T, n, U, X, e, F, k, g, k, _, a, 5, s, V, V, L, u, L, P, 2, H, 7, k, H, e, u, 7, H, X, L]
[m, m, h, k, R, F, B, I, S, o, V, E, N, k, i, S, P, k, T, B, A, J, A, J, b, S, O, a, h, Y, 3, 1, n, M, B, 3, 5, b, O, b, H, p, q, a, v, H, o, F, _, k, i, v, Y, 3]
[b, a, 4, 5, n, 8, X, N, G, N, a, 4, i, S, W, h, E, J, 3, X, b, J, K, m, h, a, i, E, a, B, B, 0, c, I, e, S, R, M, 1, J, m, e, g, g, J, R, N, F, c, k, m, k, 8, V, V, t, c, Q, X, b, k]
[f, h, A, 6, n, m, 4, N, L, I, a, T, 7, P, x, 5, k, u, s, l, M, y, O, l, j, E, U, o, t, Q, K, G, b, e]
[Q, A, 2, 8, a, G, u, i, 3, i, 6, B, s, o, w, R, 6, o, v, Y, v, y, 5, 6, O, b, o, B, u, R, a, R, u, _, Q, t, L, U, u, q, 3, u, 8, L, 8, K, Y, v, f, L, Y, q, 8, A, _, f, w, a, 3, M, y, O, R, D, C, 2, Q, s, f, Q, o, x, Y, b, 5, 3, t, u, 8, f, K, K, N, D, E, a, N, b]
[O, V, 0, 1, 0, V, P, i, K, Y, n, P, w, P, v, b, b, L, c, n, 1, k, I, I, o, N, 5, A, L, b, k, i, Q, n, 4, p, P, g, v, w, Y, k, B, Y, o, 5, 1, Q, W, B, k, V, 1, E, J, V, k, J, c, g, v, B, Q, O, N, 1, Q, 3, J, o, j, Y, 1, A, l, c, Y, b, C, v, w, 3, M, q, 4, Y, b, C, p, A, c, K, 5, N, b, N, k, l, G, i, O, Y, O]
[T, D, n, A, k, k, J, D, q, 6, y, a, p, o, h, 6, P, Q, 2, t, D, 5, b, 7, E, U, y, j, w, k, 3, Y, X, j, e, D, 8, f, k, q, h, t, b, E, Y, L, X, p, 6, G, G, A, o, o, 3, Q, I, 7, j, J, Q, n, b, 8, Q, b, U, s, I, s, P, w, J, 5, h, L, U, C, f, h, K, G, 8, b, j, C, q]
[4, F, Y, W, l, i, w, b, r, g, y, n, R, 3, A, O, 2, t, J, r, P, 8, k, y, o, M, c, i, T, Q, R, q, i, C, 3, X, Y, r, P, g, k, r, L, p, R, 2, y, p, p, X, 2, W, p, l, d, 3, R, Q, U, F, u, Q, p, k, 2, M, b, V, k, S, q]
[o, u, 0, w, X, 4, C, J, 2, H, 6, n, U, j, m, t, H, U, v, 0, P, 1, D, X, b, g, D, H, V, I, 0, o, k, m, o, Q, b, j, H, k, K, m, C, L, D, Q, n, g, j, 5, L, 0, c, v, Q, u, P, o, c, 4, a, v, x, x, K, 8, P, G, a, A, k, 6, 5, C, n, x, f, x, t, v, c, G, 8, w, c, N, w, 6, k, K, a, I, f, n, n, c, T, v, A, o, 4, I, R, P, k, C, m, J, T, j]
[7, r, m, P, I, 4, s, P, q, d, d, 7, D, O, K, m, D, 5, k, l, i, O, S, Y, B, R, r, X, o, d, j, X, B, 1, l, Q, 4, E, a, X, u, B, 4, N, X, p, Y, q, d, J, 6, P, C, Y, u, U, d, a, o, p, K, u, 6, A, 7, 1, b, P, u, a, S, A, A, C, 5, B, j, N, B, R, C, 5, X, 1, R, D, f, q, 1, q, o, S, L, l, H, p, m, n, A, 5, C, B, r, 0, K, l, L]
[v, q, P, o, 7, I, y, y, 7, X, U, L, V, G, K, Y, O, n, Q, 4, E, W, H, b, x, f, 6, 5, s, l, k, 1, d, 3, g, N, V, 8, S, h, F, S, J, C, e, t, R]
[W, E, 5, S, Q, k, J, L, b, O, g, L, v, p, l, j, f, U, d, j, 3, j, b, Y, g, T, r, p, K, Y, 7, a, F, c, F, o, 5, 0, u, W, R, p, o, F, k, q, K, R, P, J, C, M, 5, A, Y, n, e, I, E, l, t, q, M, Q, 6, x, c, T, q, n, F, J, 0, j, b, c, x, x, r, t, e, P, C, S, R, A, W, 0, 2, Q, l, g, d, U, m, U, L]
[h, j, V, j, i, Y, Y, 2, l, 7, P, I, h, M, Q, s, y, W, j, F, 3, V, U, 4, G, c, L, 3, v, Y, q, A, 1, e, M, W, 2, 1, P, P, 2, o, Y, F, A, 4, G, N, o, h, y, U, D, k, X, Q, a, q, L, H, 1, 5, P, 3, r, i, 7, D, c, N, u, D, t, x, a, p, i, H, n, M, L, 3, M, p, D, A, a, 0, l, G, P, r, I, g, t, d, Q, Y, Y, n, a, d, U, j, 1, V, _, M, V, u, H, _, a, H, l, o, 1, 4, d, F]
[j, R, D, F, S, 0, 8, j, C, 2, J, J, p, 5, e, e, n, F, q, d, j, i, s, E, t, W, V, r, 5, Q, J, D, Q, 1, t, S, 7, w, 6, d, j, P, 2, 6, a, J, _, I, H, d, I, V, s, 2, w, 5, u, k, y, A, L, Y, h, o, W, 1, _, S, l, 0, a, j, 1, i, 3, s, a, n, 7, w, r, a, v, b, n, j, y, o, H, _, A, 1, k, S, D, 8, b, O, F, A]
[w, T, 7, W, 8, 2, 5, X, 6, t, p, l, j, K, m, g, b, g, T, 5, X, u, 5, V, 1, 6, O, Q, R, n, j, L, Q, 3, x, X, l, F, d, d, 5, C, b, r, 7, p, E, 4, f, c, Q, p, G, b, O, Q, S, x, a, R, L, r, b, u, p, 2, S, A, j, R, t, T, j, o, G, F, b, d, W, 7, I, G, k, 7, w, f, 0, r, 8, 8, 8, C, 0, l, X, S, x, i, r, 1, V, d, c, 8, O, Q, Q, 3, U, 4, E, u, h, l, J, a, 0, t, p, 3, k, g, R, 6, W, A, X, h]
[L, x, M, w, u, y, v, P, H, D, w, s, i, 6, f, O, A, e, X, G, C, a, L, E, h, 7, C, 6, e, D, J, 6, Y, G, E, O, p, T, s, e, d, r, Q, Y, q, M, c, n, n, B, d, E, X, c, b, y, 0, C, I, l, 1, t, 4, e, o, l, R, J, R, C, H, 7, F, 7, H, 5, O, R, i, g, S, U, o, a]
[D, f, 1, R, f, P, 8, E, q, 6, k, W, d, G, Q, l, q, F, p, _, T, V, m, s, n, m, 4, j, J, u, n, h, t, F, F, 2, 2, L, S, p, a, 0, q, G, 1, 3, U, L, Q, 5, 7, g, v, a, b, K, j, u, 0, d, 1, s, P, M, c, e, I, V, T, F, e, O, i, g, I, O, Y, G, v, E, B, O, M, e]
[G, V, 1, 6, L, o, f, w, 3, n, a, i, q, W, 8, d, 0, r, h, F, c, e, C, Y, L, G, m, A, i, a, X, 7, H, g, u, f, E, r, C, h, 8, D, L, o, V, J, 5, b, _, x, 5, _, c, _, 4, u, t, a, p, I, T, O, 6, 4, M, T, X, m, y, p, O, d, s, Y, p, o, l, w, F, K, 0, k, j, o, r, P]
[p, _, r, u, S, i, F, 2, 8, M, O, g, 0, C, H, y, 3, A, G, v, 5, f, V, E, x, P, m, s, L, R, j, N, 7, U, E, o, J, q, T, W, N, s, h, l, I, D, Q, e, k, c, m, n, a, w, d, 1, 1, b]
[v, P, V, L, N, g, l, n, U, 3, m, s, p, D, U, V, f, U, D, A, i, q, 5, k, i, w, e, L, G, u, e, J, c, Q, H, j, N, H, d, v, f, K, H, 0, _, O, G, B, 8, U, n, Y, J, o, 0, W, s, W, B, e, f, n, w, U, j, D, N, B, e, a, R, O, A, U, w, O, 6, N, o, T, q, G, S, r, _, k, B, D, L, D, X, r, t, F, R, i, 6, F, E, V, y, y, 4, b, I, 4, P, 5, b, 7, h, 8, m, Q, v, L, s]
[v, q, 0, a, O, Y, P, 6, E, g, w, d, E, U, M, G, O, H, v, A, j, q, L, T, v, o, t, 1, u, i, n, 6, S, l, m, A, _, B, e, A, H, 0, 7, V, X, T, 2, F, D, h, K, R, 6, l, r, 8, 4, l, I, g, y, 2, s, J, x, 3, D, 4, k, Q, p, N, C, d, n, 5, f, v, E, t, c, l, G, r, 8, R, f, s, W, C, I]
