
import java.util.*;

public class Test36 {

    public static void main(String[] args) {
        List<List<String>> seznami = new ArrayList<>();

        seznami.add(List.of("fWOo5eP", "GIl", "2LM", "xBUu", "GIl", "MJ", "O", "aW4", "7SaurEa", "t", "WBp3h", "kt", "7SaurEa", "Egp", "MJ", "0fWlG6", "pUd", "VKaJ0", "qR", "PVgSP", "MJ", "b", "ys", "fWOo5eP", "n5X", "nM_VP", "lY", "Qac", "7SaurEa", "O", "PVgSP", "4L", "UH", "pMchSSg", "kNSoJr", "fWOo5eP", "4L", "kxusj", "evEWsmA", "XmDie", "2LM", "__PGVW", "SpUyp", "SpUyp", "SpUyp", "G4ItsC", "SpUyp", "fiPD", "Mdq4v", "PVgSP", "Egp", "4L", "qR", "bggWawT", "b", "PVgSP", "Mdq4v", "XpPE", "2LM", "evEWsmA", "T6bD", "Luw2__", "SpUyp", "fWOo5eP", "LN", "ePdAfl", "4L", "VKaJ0", "__PGVW", "E7Lc0Hj", "h", "kt", "VdNXICj", "ML", "UH", "Df", "UH", "fWOo5eP", "t", "pUd", "ePdAfl", "xBUu", "lY", "GX", "xBUu", "Qac", "kxusj", "h", "kNSoJr", "lY", "44MV2", "bggWawT", "5V55BdB", "h", "Df", "XmDie", "aW4", "pUd", "4L", "44MV2", "ePdAfl", "Mdq4v", "Mn", "fiPD", "b", "ML", "5V55BdB"));
        seznami.add(List.of("Egp", "P", "eIH", "hv", "XmDie", "qR", "lY", "Mdq4v", "6VF", "Mn", "qoO", "44MV2", "VKaJ0", "OE2nG", "Df", "XpPE", "DW", "n5X", "XmDie", "7SaurEa", "LN", "O", "oERtsU", "fWOo5eP", "LN", "Qac", "hv", "1wBBQ", "Mn", "5V55BdB", "GIl", "GX", "WBp3h", "iBHHP6", "6VF", "VjA", "2LM", "44MV2", "7SaurEa", "qoO", "4QB5Oy0", "cxXQSqt", "SpUyp", "CttvWyu", "k2EGG7q", "W", "xl", "OE2nG", "Df", "G4ItsC", "SbuEbc", "cxXQSqt", "Y_X48", "XpPE", "Mdq4v", "lY", "BgTN", "u0", "piY", "OE2nG", "ML", "LN", "pUd", "SbuEbc", "P", "aW4", "4HT5", "MJ", "O", "Luw2__", "6VF", "rMd", "iBHHP6", "nM_VP", "hv", "fiPD", "fWOo5eP", "SbuEbc", "qR", "4HT5", "DW", "4QB5Oy0", "qR", "5hRal", "XmDie", "cxXQSqt", "GIl", "OE2nG", "Q_tr0Y", "2LM", "5V55BdB", "Q_tr0Y", "W", "__PGVW", "Q_tr0Y", "4L", "ys", "SbuEbc", "iqXg", "ekBhJOS", "kNSoJr", "n5X", "GIl", "5hRal", "SpUyp", "3x", "T6bD", "DW", "3R7h", "Qac", "__PGVW", "eIH", "k2EGG7q", "aW4", "5hRal", "fWOo5eP", "yT5E38O", "CttvWyu", "pUd", "igsXG_1", "ekBhJOS", "44MV2", "OE2nG", "jO", "Mn", "bggWawT", "xl", "fWOo5eP", "evEWsmA", "XpPE", "iqXg", "igsXG_1", "Df", "kt", "kNSoJr", "WBp3h", "4L", "Mdq4v", "aW4", "qoO", "PVgSP", "n5X", "Qac", "1wBBQ", "qoO", "XpPE", "BgTN", "VjA", "DW", "u0", "n5X", "lY", "cxXQSqt", "pMchSSg", "Q_tr0Y", "2LM", "URY", "W", "pMchSSg", "aW4", "fWOo5eP", "4HT5", "evEWsmA", "Qac", "7SaurEa", "Egp", "P", "k2EGG7q", "k2EGG7q", "4L", "Rcs", "T6bD", "3x", "k2EGG7q", "Df", "ML", "CttvWyu", "4HT5", "lY", "_r7", "URY", "Rcs", "W", "4HT5", "_r7", "yT5E38O", "OE2nG", "igsXG_1", "3R7h", "3R7h", "CttvWyu", "xl", "T6bD", "pUd", "Y_X48", "T6bD", "Egp", "kxusj", "oERtsU", "t2", "G4ItsC", "Y_X48", "ML", "__PGVW", "7SaurEa", "qoO", "MJ", "VjA", "u0", "oERtsU", "VjA", "4_AB", "URY", "eIH", "oERtsU", "ys", "Egp", "iqXg", "piY"));
        seznami.add(List.of("8_", "OE2nG", "1wBBQ", "MJ", "pUd", "kxusj", "evEWsmA", "k2EGG7q", "k2EGG7q", "PgacVw", "ys", "pUd", "kxusj", "k2EGG7q", "ANMLQ", "kj8u", "eIH", "ys", "yndPue5", "yndPue5", "yT5E38O", "1wBBQ", "kxusj", "kxusj", "MJ"));
        seznami.add(List.of("fiPD", "3x", "Rcs", "evEWsmA", "pXytJ", "kNSoJr", "E7Lc0Hj", "5V55BdB", "JWX1", "XpPE", "hv", "VjA", "3R7h", "O", "SbuEbc", "k2EGG7q", "megQ1", "3R7h", "nM_VP", "PgacVw", "sFXLhq", "yndPue5", "Df", "BgTN", "GIl", "LN", "GX", "VjA", "1wBBQ", "iBHHP6", "ANMLQ", "XpPE", "0fWlG6", "pMchSSg", "CttvWyu", "ML", "n5X", "DVOn", "fWOo5eP", "VKaJ0", "b", "qoO", "piY", "8_", "UH", "jO", "3R7h", "kj8u", "UH", "kxusj", "igsXG_1"));
        seznami.add(List.of("OE2nG", "DW", "VjA", "ePdAfl", "UH", "sFXLhq", "P", "E7Lc0Hj", "SbuEbc", "XmDie", "rMd", "Mdq4v", "h", "Qac", "XpPE", "oERtsU", "PVgSP", "GX", "ys", "iBHHP6", "3R7h", "Mn", "xBUu", "VdNXICj", "xl", "fWOo5eP", "4HT5", "BgTN", "DVOn", "WBp3h", "4L", "GIl", "ekBhJOS", "JWX1", "kxusj", "eIH", "W", "t2", "jO", "evEWsmA", "pUd", "2LM", "6VF", "ML", "pXytJ", "t", "MJ", "5V55BdB", "ANMLQ", "44MV2", "bggWawT", "hv", "4_AB", "4QB5Oy0", "b", "k2EGG7q", "yndPue5", "cxXQSqt", "Gq2Eq2F", "VKaJ0", "Q_tr0Y", "__PGVW", "CttvWyu", "Y_X48", "qR", "kt", "1wBBQ", "SpUyp", "T6bD", "n5X", "lY", "Egp", "megQ1", "5hRal", "piY", "0fWlG6", "Luw2__", "nM_VP", "Df", "Rcs", "yT5E38O", "aW4", "qoO", "G4ItsC", "iqXg", "_r7", "URY", "8_", "u0", "3x", "kj8u", "7SaurEa", "LN", "PgacVw", "fiPD"));
        seznami.add(List.of("Gq2Eq2F", "sFXLhq", "0fWlG6", "LN", "6VF", "aW4", "XmDie", "OE2nG", "XmDie", "BgTN", "iqXg", "aW4", "G4ItsC", "h", "iqXg", "k2EGG7q", "8_", "DVOn", "n5X", "Luw2__", "Q_tr0Y", "XmDie", "OE2nG", "0fWlG6", "bggWawT", "OE2nG", "kNSoJr", "Luw2__", "8_", "aW4", "bggWawT", "OE2nG", "ePdAfl", "6VF", "OE2nG", "LN", "aW4", "2LM", "jqIaRmy", "DVOn", "Gq2Eq2F", "3R7h", "SbuEbc", "Q_tr0Y", "G4ItsC", "eIH", "lY", "PgacVw", "VKaJ0", "h", "h", "megQ1", "3R7h", "4QB5Oy0", "k2EGG7q", "sFXLhq", "kNSoJr", "PgacVw", "XmDie", "W", "h", "G4ItsC", "jO", "megQ1", "3R7h", "eIH", "3R7h", "0fWlG6", "jO", "4_AB", "Gq2Eq2F", "jO", "G4ItsC", "Q_tr0Y", "kNSoJr", "lY", "W", "PVgSP", "kt", "PVgSP", "G4ItsC", "kNSoJr"));
        seznami.add(List.of("URY", "XmDie", "b", "hv", "k2EGG7q", "ANMLQ", "3R7h", "DVOn", "MJ", "t", "Egp", "t", "xBUu", "3x", "XmDie", "0fWlG6", "eIH", "4HT5", "T6bD", "xl", "GIl", "ekBhJOS", "VjA", "LN", "T6bD", "u0", "nM_VP", "Q_tr0Y", "piY", "ML", "megQ1", "JWX1", "PVgSP", "G4ItsC", "0fWlG6", "Df", "Rcs", "evEWsmA", "VdNXICj", "GX", "fiPD", "Rcs", "PgacVw", "__PGVW", "_r7", "DW", "pXytJ", "k2EGG7q", "DVOn", "Luw2__", "UH", "sFXLhq", "OE2nG", "jqIaRmy", "u0", "8_", "pUd", "1wBBQ", "jqIaRmy", "4L", "t", "0fWlG6", "bggWawT"));
        seznami.add(List.of("G4ItsC", "Mn", "jqIaRmy", "u0", "VjA", "Mn", "t", "kNSoJr", "eIH", "kj8u", "3R7h", "4_AB", "T6bD", "bggWawT", "fiPD", "kNSoJr", "G4ItsC", "SpUyp", "Mdq4v", "Egp", "Y_X48", "jqIaRmy", "Egp", "3R7h", "SpUyp", "VjA", "3R7h", "DW", "jO", "bggWawT", "DW", "T6bD", "fiPD", "SpUyp", "Egp", "8_", "u0", "Y_X48", "3R7h", "G4ItsC", "jO", "kj8u", "bggWawT", "DW", "3R7h", "jO", "sFXLhq", "3R7h", "VjA", "Mn", "sFXLhq", "Egp", "sFXLhq", "kj8u", "t", "T6bD", "t", "u0", "u0", "DW"));
        seznami.add(List.of("b", "jqIaRmy", "CttvWyu", "ys", "evEWsmA", "oERtsU", "URY", "evEWsmA", "jO", "GIl", "kxusj", "JWX1", "VdNXICj", "kt", "VKaJ0", "iBHHP6", "ekBhJOS", "CttvWyu", "G4ItsC", "Gq2Eq2F", "6VF", "xl", "kt", "h", "kj8u", "kt", "P", "iqXg", "xBUu", "ekBhJOS", "ePdAfl", "3R7h", "DVOn", "cxXQSqt", "_r7", "__PGVW", "W", "piY", "nM_VP", "T6bD", "Luw2__", "qR", "pXytJ", "jO", "t2", "yT5E38O", "Egp", "WBp3h", "n5X", "PgacVw", "aW4", "k2EGG7q", "4QB5Oy0", "pXytJ", "kNSoJr", "b", "iBHHP6", "T6bD", "4HT5", "PgacVw", "4QB5Oy0", "yT5E38O", "VdNXICj", "fWOo5eP", "DVOn", "PVgSP", "ekBhJOS", "Luw2__", "kj8u", "P", "iBHHP6", "Mn", "Gq2Eq2F", "4QB5Oy0", "nM_VP", "xl", "5V55BdB", "DW", "LN", "bggWawT", "7SaurEa", "4_AB", "XpPE", "piY", "Egp", "GX", "Egp", "Mn", "ePdAfl", "6VF", "k2EGG7q", "evEWsmA", "Qac", "5hRal", "t", "t2", "ML", "Df", "t", "t2", "pMchSSg", "CttvWyu", "xl", "iBHHP6", "XmDie", "2LM", "lY", "Gq2Eq2F", "Qac", "DW", "3x", "WBp3h", "MJ", "Luw2__", "xl", "ML", "yndPue5", "7SaurEa", "JWX1", "6VF", "WBp3h", "pUd", "PgacVw", "VjA", "jqIaRmy", "PVgSP", "kNSoJr", "eIH", "evEWsmA", "fWOo5eP", "pMchSSg", "7SaurEa", "hv", "ANMLQ", "ANMLQ", "u0", "qR", "WBp3h", "44MV2", "8_"));
        seznami.add(List.of("W", "k2EGG7q", "DVOn", "iqXg", "Gq2Eq2F", "pXytJ", "cxXQSqt", "t", "n5X", "evEWsmA", "E7Lc0Hj", "OE2nG", "DW", "4_AB", "Luw2__", "3R7h", "h", "cxXQSqt", "kxusj", "ML", "k2EGG7q", "MJ", "Y_X48", "URY", "OE2nG", "Q_tr0Y", "bggWawT", "OE2nG", "Gq2Eq2F", "5hRal", "Y_X48", "UH", "3R7h", "E7Lc0Hj", "DW", "Egp", "Luw2__", "cxXQSqt", "E7Lc0Hj", "kxusj", "Egp", "bggWawT", "pMchSSg", "n5X", "b", "3x", "xl", "b", "6VF", "n5X", "4_AB", "GX", "sFXLhq", "nM_VP", "GIl", "h", "E7Lc0Hj", "6VF", "h", "PgacVw", "5hRal", "SpUyp", "GX", "k2EGG7q", "WBp3h", "cxXQSqt", "6VF", "4_AB", "xl", "Y_X48", "ML", "Q_tr0Y", "LN", "URY", "DVOn", "GX", "iqXg", "UH", "n5X", "5hRal", "sFXLhq", "pMchSSg", "k2EGG7q", "5V55BdB", "6VF", "CttvWyu", "bggWawT"));
        seznami.add(List.of("qoO", "b", "Gq2Eq2F", "jqIaRmy", "jqIaRmy", "ML", "aW4", "LN", "lY", "aW4", "LN", "qoO", "aW4", "Gq2Eq2F", "Egp", "ML", "Egp", "aW4", "ML"));
        seznami.add(List.of("u0", "iBHHP6", "5V55BdB", "jO", "t", "pMchSSg", "igsXG_1", "VKaJ0", "DW", "fWOo5eP", "6VF", "qoO", "6VF", "n5X", "ePdAfl", "URY", "n5X", "kt", "O", "E7Lc0Hj", "LN", "LN", "aW4", "Mn", "oERtsU", "DW", "aW4", "GIl", "SpUyp", "4_AB", "VdNXICj", "1wBBQ", "kt", "eIH", "T6bD", "GIl", "1wBBQ", "aW4", "ys", "Df", "ekBhJOS", "P", "6VF", "u0", "u0", "iBHHP6", "Gq2Eq2F", "Df", "LN", "iBHHP6", "kt", "_r7", "O", "ekBhJOS", "b", "_r7", "iBHHP6", "fiPD", "qoO", "4_AB", "qR", "ekBhJOS", "5V55BdB", "JWX1", "hv", "GIl", "fWOo5eP", "44MV2", "PgacVw", "ePdAfl", "_r7", "Mdq4v", "VKaJ0", "yT5E38O", "pXytJ", "Y_X48", "BgTN", "4L", "yndPue5", "P", "ePdAfl", "4_AB", "oERtsU", "VKaJ0", "7SaurEa", "qoO", "PVgSP", "ys", "xBUu", "qoO", "oERtsU", "b", "__PGVW", "qoO", "XpPE", "VdNXICj", "Qac", "4L", "1wBBQ", "URY", "JWX1", "E7Lc0Hj", "Q_tr0Y", "Y_X48", "yndPue5", "sFXLhq", "Gq2Eq2F", "7SaurEa", "Q_tr0Y", "PVgSP", "Gq2Eq2F", "_r7", "44MV2", "4L", "44MV2", "SpUyp", "44MV2", "Mdq4v", "u0", "ekBhJOS", "Mn", "sFXLhq", "b", "1wBBQ", "DW", "SpUyp", "3x", "DW", "5V55BdB", "aW4", "u0", "ys", "igsXG_1", "fiPD", "yndPue5", "T6bD"));
        seznami.add(List.of("5V55BdB", "W", "Mdq4v", "4HT5", "jO", "kt", "P", "yndPue5", "kNSoJr", "eIH", "7SaurEa", "OE2nG", "kt", "E7Lc0Hj", "JWX1", "Luw2__", "Gq2Eq2F", "cxXQSqt", "Rcs", "VjA", "ML", "2LM", "kxusj", "6VF", "Luw2__", "oERtsU", "kNSoJr", "igsXG_1", "PVgSP", "LN", "LN", "nM_VP", "kt", "T6bD", "Q_tr0Y", "4HT5", "yndPue5", "b", "DW", "3x", "__PGVW", "XpPE", "SbuEbc", "G4ItsC", "xBUu", "igsXG_1", "Mdq4v", "4HT5", "b", "JWX1", "5hRal", "G4ItsC", "3R7h", "qoO", "qR", "Luw2__", "Mn", "nM_VP", "rMd", "2LM", "ekBhJOS", "qR", "Mdq4v", "kj8u", "kj8u", "4HT5", "kNSoJr", "lY", "5hRal", "aW4", "VKaJ0", "n5X", "4HT5", "5hRal", "P", "DVOn", "fiPD", "oERtsU", "jqIaRmy", "OE2nG", "t2", "P", "3x", "6VF", "DVOn", "xBUu", "SbuEbc", "44MV2", "UH", "kxusj", "ekBhJOS", "oERtsU", "Gq2Eq2F", "ANMLQ", "__PGVW", "qoO", "eIH", "xBUu", "7SaurEa", "3R7h", "qoO", "E7Lc0Hj", "P", "DW", "4QB5Oy0", "kNSoJr", "VKaJ0", "jO", "Luw2__", "0fWlG6", "OE2nG", "MJ", "6VF", "SbuEbc", "LN", "GX", "ekBhJOS", "5V55BdB", "pMchSSg", "iBHHP6", "2LM", "WBp3h", "qoO", "Mn", "4_AB", "4HT5", "XpPE", "yndPue5", "MJ", "3x", "GIl", "1wBBQ", "PVgSP", "6VF", "3R7h", "7SaurEa", "OE2nG", "GIl", "WBp3h", "kj8u", "t2", "kxusj", "ekBhJOS", "iBHHP6", "kxusj", "MJ", "SbuEbc", "lY", "JWX1", "44MV2", "rMd", "3R7h", "n5X", "ANMLQ", "pXytJ", "kt", "jqIaRmy", "yT5E38O", "3R7h", "yndPue5", "kNSoJr", "4_AB", "LN", "4QB5Oy0", "6VF", "Rcs", "Mn", "XmDie", "pMchSSg", "Q_tr0Y", "aW4", "GX", "Rcs", "lY", "4L", "qR", "SpUyp", "5V55BdB", "igsXG_1", "W", "_r7", "PVgSP", "Q_tr0Y", "XmDie", "qoO", "CttvWyu", "ML", "xBUu", "xl", "URY", "cxXQSqt", "evEWsmA", "evEWsmA", "Luw2__", "OE2nG", "OE2nG", "Q_tr0Y", "ekBhJOS", "DVOn", "JWX1", "fWOo5eP", "CttvWyu", "GX", "4L", "aW4", "fWOo5eP", "4QB5Oy0", "XpPE", "2LM", "xl", "DW", "Luw2__", "E7Lc0Hj", "kxusj", "0fWlG6", "n5X", "xl", "iBHHP6"));
        seznami.add(List.of("0fWlG6", "Df", "G4ItsC", "_r7", "_r7", "0fWlG6", "jO", "Df", "0fWlG6"));
        seznami.add(List.of("evEWsmA", "4HT5", "ePdAfl", "t", "t", "4HT5", "jqIaRmy", "Y_X48", "nM_VP", "0fWlG6", "WBp3h", "5V55BdB", "Mdq4v", "kNSoJr", "kxusj", "BgTN", "n5X", "GX", "fiPD", "JWX1", "bggWawT", "3R7h", "evEWsmA", "WBp3h", "G4ItsC", "44MV2", "yT5E38O", "lY", "G4ItsC", "BgTN", "Egp", "JWX1", "ePdAfl", "cxXQSqt", "xl", "MJ", "igsXG_1", "MJ", "fWOo5eP", "GIl", "VKaJ0", "ys", "0fWlG6", "kj8u", "jO", "cxXQSqt", "E7Lc0Hj", "fiPD", "6VF", "pXytJ", "megQ1", "igsXG_1", "pUd", "ys", "5V55BdB", "yndPue5", "iBHHP6", "DW", "bggWawT", "eIH", "ML", "sFXLhq", "Egp", "ePdAfl", "rMd", "qR", "URY", "Y_X48", "evEWsmA", "jqIaRmy", "0fWlG6", "jO", "4QB5Oy0", "Luw2__", "SpUyp", "6VF", "Egp", "__PGVW", "b", "7SaurEa", "GX", "qR", "__PGVW", "VKaJ0", "Q_tr0Y", "XpPE", "PgacVw", "6VF", "Q_tr0Y", "4HT5", "jO", "4_AB", "u0", "iqXg", "lY", "_r7", "h", "nM_VP", "qoO", "oERtsU", "G4ItsC", "xBUu", "pXytJ", "VdNXICj", "oERtsU", "Rcs", "iBHHP6", "ANMLQ", "Luw2__", "O", "XmDie", "PVgSP", "nM_VP", "OE2nG", "Df", "bggWawT", "SbuEbc", "4L", "MJ", "qR", "PgacVw", "VKaJ0", "0fWlG6", "evEWsmA", "Rcs", "h", "3x", "_r7", "5hRal", "URY", "ANMLQ", "qoO", "ML", "LN", "5V55BdB", "_r7", "sFXLhq", "SbuEbc", "2LM", "ekBhJOS", "qoO", "ANMLQ", "P", "Mn", "CttvWyu", "ML", "W", "T6bD", "8_", "URY", "kNSoJr", "MJ", "sFXLhq", "pXytJ", "megQ1", "2LM", "Luw2__", "megQ1", "8_", "k2EGG7q", "DW", "__PGVW", "O", "DVOn", "ekBhJOS", "fWOo5eP", "W", "kt", "xBUu", "PgacVw", "pUd", "VjA", "8_", "t2"));
        seznami.add(List.of("pMchSSg", "aW4", "ys", "rMd", "5hRal", "yT5E38O", "URY", "ePdAfl", "kt", "qR", "pMchSSg", "kNSoJr", "yndPue5", "sFXLhq", "u0", "u0", "OE2nG", "eIH", "ePdAfl", "t", "1wBBQ", "LN", "XmDie", "DVOn", "SbuEbc", "W", "oERtsU", "3R7h", "Df", "kNSoJr", "LN", "Y_X48", "CttvWyu", "Df", "O", "pUd", "Gq2Eq2F", "CttvWyu", "2LM", "VKaJ0", "Rcs", "Gq2Eq2F", "aW4"));
        seznami.add(List.of("VjA", "8_", "ePdAfl", "t2", "6VF", "ANMLQ", "hv", "DW", "ANMLQ", "1wBBQ", "Qac", "Mdq4v", "6VF", "E7Lc0Hj", "1wBBQ", "_r7", "GIl", "Mdq4v", "MJ", "qR", "aW4", "GIl", "UH", "ANMLQ", "t2", "XpPE", "1wBBQ", "jqIaRmy", "hv", "eIH", "UH", "E7Lc0Hj", "_r7", "8_", "Df", "_r7", "qR", "aW4", "ePdAfl", "PgacVw", "DW"));

        Cetrta.poDolziniBrezDuplikatov(seznami);

        for (List<String> seznam: seznami) {
            System.out.println(seznam);
        }
    }
}
