
import java.util.*;

public class Test03 {

    public static void main(String[] args) {
        List<List<String>> seznami = new ArrayList<>();

        seznami.add(List.of("3R7h", "Egp", "5hRal", "MJ", "VjA", "kxusj", "yT5E38O", "XpPE", "VdNXICj", "5V55BdB", "fiPD", "SpUyp", "fWOo5eP", "Rcs", "Qac", "0fWlG6", "PVgSP", "4L", "hv", "PgacVw", "7SaurEa", "T6bD", "Gq2Eq2F", "sFXLhq", "WBp3h", "LN", "Mn", "CttvWyu", "jO", "ANMLQ", "pXytJ", "evEWsmA", "nM_VP", "VKaJ0", "Y_X48", "t2", "4HT5", "oERtsU"));
        seznami.add(List.of("4QB5Oy0", "VdNXICj", "Mn", "4HT5", "kxusj", "Egp", "yT5E38O", "MJ", "5hRal", "igsXG_1", "fWOo5eP", "Y_X48", "SpUyp", "qoO", "hv", "CttvWyu", "Qac", "u0", "O", "fiPD", "evEWsmA", "h", "VKaJ0", "Rcs", "7SaurEa", "pMchSSg", "Gq2Eq2F"));
        seznami.add(List.of("kxusj", "fWOo5eP", "SpUyp", "Qac", "BgTN", "xBUu", "5hRal", "hv", "4HT5", "VKaJ0", "Mn", "fiPD", "MJ", "CttvWyu", "yT5E38O", "kt", "Gq2Eq2F", "Rcs", "JWX1", "evEWsmA", "_r7", "Egp", "PgacVw", "6VF", "7SaurEa", "n5X", "GIl", "PVgSP", "Y_X48", "T6bD", "ekBhJOS"));
        seznami.add(List.of("4L", "t", "MJ", "fiPD", "4HT5", "5hRal", "Q_tr0Y", "URY", "fWOo5eP", "SpUyp", "CttvWyu", "Qac", "yT5E38O", "O", "VKaJ0", "7SaurEa", "Egp", "VdNXICj", "qR", "BgTN", "t2", "cxXQSqt", "kxusj", "Gq2Eq2F", "__PGVW", "Y_X48", "n5X", "hv", "3x", "8_", "pMchSSg", "evEWsmA", "Mn", "Rcs"));
        seznami.add(List.of("Qac", "Gq2Eq2F", "igsXG_1", "4L", "ANMLQ", "VKaJ0", "u0", "evEWsmA", "SpUyp", "5V55BdB", "7SaurEa", "Rcs", "JWX1", "Y_X48", "44MV2", "Mn", "fiPD", "pMchSSg", "fWOo5eP", "MJ", "__PGVW", "hv", "XmDie", "ekBhJOS", "Egp", "4_AB", "5hRal", "yT5E38O", "CttvWyu", "qR", "kj8u", "4HT5", "1wBBQ", "aW4", "xl", "xBUu", "kxusj", "Mdq4v"));
        seznami.add(List.of("CttvWyu", "rMd", "VKaJ0", "hv", "G4ItsC", "yT5E38O", "PgacVw", "Egp", "Gq2Eq2F", "7SaurEa", "kxusj", "MJ", "VjA", "Mn", "4HT5", "5V55BdB", "t2", "fWOo5eP", "Y_X48", "xl", "Rcs", "yndPue5", "__PGVW", "kNSoJr", "5hRal", "fiPD", "3R7h", "iqXg", "xBUu", "Qac", "SpUyp", "u0", "evEWsmA", "lY", "jqIaRmy", "igsXG_1", "sFXLhq"));
        seznami.add(List.of("PVgSP", "BgTN", "evEWsmA", "b", "_r7", "O", "sFXLhq", "Egp", "h", "rMd", "hv", "iBHHP6", "Luw2__", "5hRal", "SpUyp", "Y_X48", "44MV2", "MJ", "Mn", "Qac", "kxusj", "7SaurEa", "8_", "fiPD", "fWOo5eP", "VKaJ0", "megQ1", "Gq2Eq2F", "Mdq4v", "Rcs", "pXytJ", "Df", "eIH", "WBp3h", "4HT5", "G4ItsC", "yT5E38O", "xl", "CttvWyu"));
        seznami.add(List.of("cxXQSqt", "P", "Gq2Eq2F", "WBp3h", "ML", "kxusj", "evEWsmA", "VKaJ0", "qoO", "DVOn", "Qac", "MJ", "yT5E38O", "Y_X48", "fiPD", "sFXLhq", "4HT5", "Mn", "hv", "Egp", "CttvWyu", "igsXG_1", "Rcs", "jqIaRmy", "u0", "xBUu", "fWOo5eP", "7SaurEa", "5hRal", "SpUyp"));
        seznami.add(List.of("DW", "PVgSP", "pXytJ", "evEWsmA", "MJ", "ekBhJOS", "VKaJ0", "Egp", "yndPue5", "hv", "Qac", "7SaurEa", "4HT5", "Rcs", "CttvWyu", "Mn", "Q_tr0Y", "JWX1", "pUd", "fWOo5eP", "Gq2Eq2F", "n5X", "SpUyp", "Y_X48", "kt", "Luw2__", "yT5E38O", "ML", "fiPD", "5hRal", "kxusj"));
        seznami.add(List.of("oERtsU", "VKaJ0", "h", "ePdAfl", "Gq2Eq2F", "CttvWyu", "4QB5Oy0", "xBUu", "SpUyp", "xl", "evEWsmA", "MJ", "kxusj", "Mn", "fWOo5eP", "Rcs", "5hRal", "Egp", "aW4", "4HT5", "yT5E38O", "fiPD", "7SaurEa", "Qac", "Y_X48", "hv", "ys", "GX"));
        seznami.add(List.of("4HT5", "5hRal", "VKaJ0", "Luw2__", "Y_X48", "fWOo5eP", "Mn", "kxusj", "Qac", "evEWsmA", "SpUyp", "Gq2Eq2F", "XpPE", "CttvWyu", "Egp", "fiPD", "MJ", "7SaurEa", "yT5E38O", "URY", "hv", "ys", "Rcs"));
        seznami.add(List.of("3x", "Rcs", "4QB5Oy0", "Mn", "ML", "7SaurEa", "b", "fiPD", "P", "evEWsmA", "pXytJ", "Qac", "Egp", "yT5E38O", "VKaJ0", "MJ", "4HT5", "Y_X48", "Gq2Eq2F", "4L", "fWOo5eP", "kxusj", "n5X", "5hRal", "hv", "SpUyp", "CttvWyu"));
        seznami.add(List.of("Y_X48", "Mdq4v", "PgacVw", "igsXG_1", "qR", "GX", "MJ", "xBUu", "VKaJ0", "Qac", "Mn", "CttvWyu", "piY", "fiPD", "yT5E38O", "G4ItsC", "kxusj", "h", "BgTN", "evEWsmA", "Egp", "yndPue5", "Gq2Eq2F", "qoO", "4HT5", "Rcs", "SpUyp", "E7Lc0Hj", "hv", "5hRal", "3R7h", "7SaurEa", "Luw2__", "fWOo5eP"));
        seznami.add(List.of("kxusj", "Gq2Eq2F", "yndPue5", "SpUyp", "5hRal", "Q_tr0Y", "CttvWyu", "fiPD", "fWOo5eP", "6VF", "Rcs", "jO", "k2EGG7q", "yT5E38O", "7SaurEa", "4HT5", "_r7", "Mn", "MJ", "evEWsmA", "Y_X48", "ANMLQ", "5V55BdB", "Qac", "VKaJ0", "hv", "iqXg", "qoO", "Egp"));
        seznami.add(List.of("VKaJ0", "n5X", "oERtsU", "SpUyp", "VjA", "Gq2Eq2F", "t2", "MJ", "PgacVw", "Rcs", "Egp", "5hRal", "jqIaRmy", "4HT5", "7SaurEa", "kxusj", "Y_X48", "fiPD", "Mn", "3x", "hv", "evEWsmA", "CttvWyu", "SbuEbc", "yT5E38O", "Df", "Qac", "fWOo5eP"));
        seznami.add(List.of("4HT5", "kxusj", "ePdAfl", "Mn", "Egp", "t", "evEWsmA", "GX", "k2EGG7q", "ys", "OE2nG", "CttvWyu", "Gq2Eq2F", "fiPD", "5hRal", "BgTN", "O", "VKaJ0", "Qac", "hv", "MJ", "E7Lc0Hj", "qoO", "b", "Q_tr0Y", "7SaurEa", "XmDie", "fWOo5eP", "n5X", "iqXg", "44MV2", "Y_X48", "jqIaRmy", "URY", "4L", "Rcs", "SpUyp", "XpPE", "yT5E38O"));
        seznami.add(List.of("fiPD", "Qac", "kNSoJr", "Egp", "BgTN", "UH", "Gq2Eq2F", "VKaJ0", "fWOo5eP", "Mn", "MJ", "SpUyp", "2LM", "yT5E38O", "Rcs", "cxXQSqt", "7SaurEa", "1wBBQ", "CttvWyu", "Y_X48", "GIl", "hv", "evEWsmA", "VjA", "4HT5", "kxusj", "5hRal"));
        seznami.add(List.of("7SaurEa", "Rcs", "SpUyp", "5hRal", "xBUu", "MJ", "CttvWyu", "kxusj", "Mn", "VKaJ0", "Qac", "Gq2Eq2F", "Egp", "fWOo5eP", "Y_X48", "evEWsmA", "4HT5", "yT5E38O", "hv", "fiPD"));
        seznami.add(List.of("yT5E38O", "6VF", "evEWsmA", "Y_X48", "4HT5", "Mn", "fiPD", "W", "XpPE", "PVgSP", "fWOo5eP", "4QB5Oy0", "Qac", "pUd", "Gq2Eq2F", "SpUyp", "7SaurEa", "MJ", "yndPue5", "Rcs", "5hRal", "Egp", "VKaJ0", "Mdq4v", "hv", "kxusj", "CttvWyu", "bggWawT"));
        seznami.add(List.of("Q_tr0Y", "8_", "Gq2Eq2F", "megQ1", "Mn", "Rcs", "E7Lc0Hj", "MJ", "Qac", "jO", "5hRal", "4HT5", "CttvWyu", "DVOn", "fWOo5eP", "Y_X48", "VKaJ0", "u0", "kxusj", "yT5E38O", "7SaurEa", "b", "fiPD", "SpUyp", "XmDie", "Egp", "hv", "evEWsmA"));
        seznami.add(List.of("Rcs", "VKaJ0", "megQ1", "MJ", "Mn", "Gq2Eq2F", "UH", "bggWawT", "XpPE", "fWOo5eP", "5hRal", "Egp", "fiPD", "sFXLhq", "ys", "hv", "GIl", "kxusj", "yT5E38O", "Qac", "7SaurEa", "Y_X48", "CttvWyu", "VjA", "4HT5", "Df", "evEWsmA", "pXytJ", "SpUyp"));
        seznami.add(List.of("qR", "CttvWyu", "W", "Gq2Eq2F", "UH", "PVgSP", "xl", "fiPD", "Mn", "44MV2", "WBp3h", "4L", "ekBhJOS", "4HT5", "yndPue5", "pUd", "Egp", "VKaJ0", "DVOn", "Qac", "VdNXICj", "5hRal", "Y_X48", "kxusj", "SpUyp", "u0", "hv", "evEWsmA", "2LM", "Rcs", "MJ", "0fWlG6", "aW4", "7SaurEa", "5V55BdB", "yT5E38O", "fWOo5eP"));
        seznami.add(List.of("Qac", "kxusj", "jqIaRmy", "bggWawT", "44MV2", "iqXg", "n5X", "7SaurEa", "8_", "Egp", "P", "Y_X48", "CttvWyu", "hv", "nM_VP", "SpUyp", "fiPD", "Mn", "pMchSSg", "fWOo5eP", "ePdAfl", "VKaJ0", "SbuEbc", "Rcs", "DVOn", "Gq2Eq2F", "4HT5", "evEWsmA", "yT5E38O", "5hRal", "E7Lc0Hj", "MJ", "G4ItsC"));
        seznami.add(List.of("pMchSSg", "URY", "5hRal", "SpUyp", "xBUu", "OE2nG", "7SaurEa", "Egp", "ANMLQ", "ML", "GIl", "GX", "hv", "rMd", "CttvWyu", "Y_X48", "kj8u", "2LM", "4HT5", "0fWlG6", "evEWsmA", "yT5E38O", "t", "MJ", "Mn", "Rcs", "4L", "Gq2Eq2F", "kxusj", "VKaJ0", "fWOo5eP", "44MV2", "fiPD", "Qac", "piY"));
        seznami.add(List.of("5hRal", "kj8u", "Egp", "k2EGG7q", "kxusj", "Gq2Eq2F", "Rcs", "hv", "MJ", "ePdAfl", "SpUyp", "fWOo5eP", "CttvWyu", "7SaurEa", "t", "VKaJ0", "evEWsmA", "4HT5", "Qac", "Y_X48", "fiPD", "yT5E38O", "Mn"));
        seznami.add(List.of("PVgSP", "Rcs", "bggWawT", "7SaurEa", "Egp", "k2EGG7q", "5hRal", "Qac", "VKaJ0", "yT5E38O", "Gq2Eq2F", "hv", "URY", "0fWlG6", "4HT5", "Mn", "fiPD", "DVOn", "kxusj", "Y_X48", "SpUyp", "ANMLQ", "xBUu", "OE2nG", "ML", "UH", "GIl", "CttvWyu", "evEWsmA", "fWOo5eP", "MJ", "T6bD"));
        seznami.add(List.of("VKaJ0", "kt", "fiPD", "5hRal", "7SaurEa", "Rcs", "SpUyp", "sFXLhq", "jqIaRmy", "JWX1", "T6bD", "evEWsmA", "kxusj", "VjA", "Y_X48", "LN", "hv", "PVgSP", "pMchSSg", "Gq2Eq2F", "GIl", "Egp", "fWOo5eP", "pUd", "4HT5", "yndPue5", "yT5E38O", "0fWlG6", "P", "G4ItsC", "MJ", "Qac", "CttvWyu", "Mn"));
        seznami.add(List.of("Gq2Eq2F", "hv", "Qac", "Mn", "evEWsmA", "iqXg", "5hRal", "fWOo5eP", "VdNXICj", "CttvWyu", "fiPD", "Egp", "kNSoJr", "4HT5", "kxusj", "VKaJ0", "7SaurEa", "PVgSP", "Rcs", "MJ", "yT5E38O", "SpUyp", "Y_X48"));
        seznami.add(List.of("8_", "T6bD", "Rcs", "G4ItsC", "h", "ANMLQ", "hv", "Mn", "5hRal", "pXytJ", "megQ1", "ePdAfl", "sFXLhq", "fiPD", "xl", "MJ", "kxusj", "CttvWyu", "pUd", "4HT5", "SpUyp", "Y_X48", "URY", "lY", "fWOo5eP", "bggWawT", "Qac", "4QB5Oy0", "W", "aW4", "JWX1", "VKaJ0", "3R7h", "Gq2Eq2F", "7SaurEa", "Egp", "evEWsmA", "yT5E38O", "__PGVW"));
        seznami.add(List.of("7SaurEa", "jqIaRmy", "b", "Gq2Eq2F", "piY", "evEWsmA", "Qac", "5hRal", "Egp", "fWOo5eP", "PVgSP", "Y_X48", "MJ", "yT5E38O", "Mn", "DW", "__PGVW", "SpUyp", "sFXLhq", "Rcs", "5V55BdB", "hv", "GX", "kxusj", "4HT5", "CttvWyu", "PgacVw", "44MV2", "fiPD", "VKaJ0"));
        seznami.add(List.of("7SaurEa", "fiPD", "4HT5", "hv", "MJ", "SpUyp", "Rcs", "Gq2Eq2F", "VKaJ0", "yT5E38O", "Mn", "Y_X48", "CttvWyu", "fWOo5eP", "Qac", "kxusj", "Egp", "5hRal", "evEWsmA", "ys"));
        seznami.add(List.of("h", "Rcs", "hv", "Egp", "XpPE", "__PGVW", "kxusj", "Mn", "4L", "n5X", "DVOn", "fiPD", "megQ1", "Mdq4v", "CttvWyu", "kNSoJr", "Gq2Eq2F", "Qac", "rMd", "jO", "evEWsmA", "MJ", "VKaJ0", "Luw2__", "SpUyp", "ePdAfl", "yT5E38O", "5hRal", "7SaurEa", "fWOo5eP", "Y_X48", "4HT5"));
        seznami.add(List.of("Rcs", "Q_tr0Y", "yT5E38O", "fWOo5eP", "fiPD", "k2EGG7q", "xl", "7SaurEa", "Y_X48", "Mn", "xBUu", "5hRal", "GIl", "VKaJ0", "CttvWyu", "WBp3h", "kxusj", "Egp", "VjA", "Gq2Eq2F", "MJ", "hv", "Qac", "4HT5", "evEWsmA", "SpUyp"));
        seznami.add(List.of("4HT5", "ys", "Y_X48", "GX", "WBp3h", "XmDie", "GIl", "kxusj", "evEWsmA", "SpUyp", "fiPD", "ML", "Luw2__", "MJ", "Qac", "yT5E38O", "7SaurEa", "VKaJ0", "fWOo5eP", "hv", "SbuEbc", "2LM", "qR", "Mn", "nM_VP", "Egp", "Rcs", "Gq2Eq2F", "3R7h", "LN", "CttvWyu", "lY", "yndPue5", "5hRal", "PgacVw", "u0"));
        seznami.add(List.of("4_AB", "pXytJ", "G4ItsC", "iqXg", "7SaurEa", "evEWsmA", "Egp", "JWX1", "yT5E38O", "fWOo5eP", "W", "Gq2Eq2F", "ekBhJOS", "CttvWyu", "5hRal", "P", "4HT5", "WBp3h", "xl", "fiPD", "OE2nG", "Qac", "Rcs", "hv", "Y_X48", "kxusj", "VKaJ0", "Mn", "SpUyp", "MJ", "3R7h"));
        seznami.add(List.of("0fWlG6", "XmDie", "PgacVw", "fiPD", "Egp", "n5X", "Gq2Eq2F", "kNSoJr", "yT5E38O", "BgTN", "CttvWyu", "7SaurEa", "LN", "5hRal", "hv", "piY", "VjA", "Qac", "MJ", "6VF", "4HT5", "kxusj", "Mn", "fWOo5eP", "bggWawT", "VKaJ0", "evEWsmA", "Rcs", "SpUyp", "4_AB", "Y_X48"));
        seznami.add(List.of("Mn", "kxusj", "Gq2Eq2F", "Egp", "4L", "SpUyp", "4HT5", "Qac", "hv", "Y_X48", "VKaJ0", "fiPD", "evEWsmA", "7SaurEa", "DVOn", "yT5E38O", "u0", "CttvWyu", "5hRal", "MJ", "WBp3h", "XpPE", "fWOo5eP", "Rcs"));
        seznami.add(List.of("5hRal", "Egp", "Mn", "hv", "jqIaRmy", "44MV2", "ANMLQ", "jO", "t", "P", "fWOo5eP", "BgTN", "VKaJ0", "CttvWyu", "fiPD", "MJ", "Q_tr0Y", "SpUyp", "evEWsmA", "Gq2Eq2F", "Qac", "4HT5", "Rcs", "kxusj", "ePdAfl", "Y_X48", "yT5E38O", "XpPE", "7SaurEa"));

        Set<String> mnozica = Cetrta.skupni(seznami);

        List<String> lstMnozica = new ArrayList<>(mnozica);
        lstMnozica.sort(null);
        System.out.println(lstMnozica);
    }
}
