*                                                                                                                                     *
 *                                                                                                                                   *
  *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
   *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
    *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
     *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
      *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
       *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
        *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
         *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
          *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
           *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
            *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
             *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
              *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
               *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                 *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                  *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                   *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                    *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                     *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                      *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                       *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                        *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                         *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                          *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                           *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                            *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                             *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                              *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                               *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                 *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                  *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                   *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                    *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                     *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                      *ooooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                       *ooooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                        *ooooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                         *ooooooooooooooooooooooooooooooooooooooooooooooooooo*
                                          *ooooooooooooooooooooooooooooooooooooooooooooooooo*
                                           *ooooooooooooooooooooooooooooooooooooooooooooooo*
                                            *ooooooooooooooooooooooooooooooooooooooooooooo*
                                             *ooooooooooooooooooooooooooooooooooooooooooo*
                                              *ooooooooooooooooooooooooooooooooooooooooo*
                                               *ooooooooooooooooooooooooooooooooooooooo*
                                                *ooooooooooooooooooooooooooooooooooooo*
                                                 *ooooooooooooooooooooooooooooooooooo*
                                                  *ooooooooooooooooooooooooooooooooo*
                                                   *ooooooooooooooooooooooooooooooo*
                                                    *ooooooooooooooooooooooooooooo*
                                                     *ooooooooooooooooooooooooooo*
                                                      *ooooooooooooooooooooooooo*
                                                       *ooooooooooooooooooooooo*
                                                        *ooooooooooooooooooooo*
                                                         *ooooooooooooooooooo*
                                                          *ooooooooooooooooo*
                                                           *ooooooooooooooo*
                                                            *ooooooooooooo*
                                                             *ooooooooooo*
                                                              *ooooooooo*
                                                               *ooooooo*
                                                                *ooooo*
                                                                 *ooo*
                                                                  *o*
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
                                                                   *
***************************************************************************************************************************************
