*                     *
 *ooooooooooooooooooo*
  *ooooooooooooooooo*
   *ooooooooooooooo*
    *ooooooooooooo*
     *ooooooooooo*
      *ooooooooo*
       *ooooooo*
        *ooooo*
         *ooo*
          *o*
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
           *
***********************
