greda 0 -> false
greda 1 -> false
greda 2 -> true
greda 3 -> false
greda 4 -> false
greda 5 -> false
greda 6 -> true
greda 7 -> false
greda 8 -> true
greda 9 -> false
greda 10 -> true
greda 11 -> true
