greda 0 -> true
greda 1 -> false
greda 2 -> false
greda 3 -> false
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> true
greda 11 -> true
greda 12 -> false
greda 13 -> true
greda 14 -> true
greda 15 -> true
greda 16 -> true
greda 17 -> false
greda 18 -> false
