greda 0 -> true
greda 1 -> true
greda 2 -> false
greda 3 -> true
greda 4 -> false
greda 5 -> true
greda 6 -> false
greda 7 -> false
greda 8 -> false
greda 9 -> true
greda 10 -> true
greda 11 -> false
greda 12 -> true
greda 13 -> true
greda 14 -> true
greda 15 -> false
greda 16 -> false
greda 17 -> true
greda 18 -> false
greda 19 -> true
greda 20 -> false
greda 21 -> true
greda 22 -> true
greda 23 -> true
greda 24 -> true
greda 25 -> true
greda 26 -> true
