greda 0 -> true
greda 1 -> true
greda 2 -> true
greda 3 -> true
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> true
greda 8 -> false
greda 9 -> false
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> true
greda 14 -> true
