greda 0 -> true
greda 1 -> true
greda 2 -> true
greda 3 -> false
greda 4 -> false
greda 5 -> false
greda 6 -> true
greda 7 -> true
greda 8 -> false
greda 9 -> false
greda 10 -> true
greda 11 -> true
greda 12 -> false
greda 13 -> true
greda 14 -> false
greda 15 -> false
greda 16 -> true
greda 17 -> false
greda 18 -> true
greda 19 -> true
greda 20 -> false
greda 21 -> true
greda 22 -> true
greda 23 -> true
greda 24 -> false
greda 25 -> true
