greda 0 -> true
greda 1 -> true
greda 2 -> true
greda 3 -> true
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> true
greda 9 -> false
greda 10 -> true
greda 11 -> false
greda 12 -> true
greda 13 -> true
greda 14 -> false
greda 15 -> true
greda 16 -> true
greda 17 -> true
