greda 0 -> false
greda 1 -> true
greda 2 -> false
greda 3 -> true
greda 4 -> true
greda 5 -> true
greda 6 -> false
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> true
greda 11 -> false
greda 12 -> true
