greda 0 -> true
greda 1 -> false
greda 2 -> true
greda 3 -> false
greda 4 -> true
greda 5 -> false
greda 6 -> true
greda 7 -> true
greda 8 -> false
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> false
greda 14 -> true
greda 15 -> true
greda 16 -> false
greda 17 -> true
greda 18 -> true
greda 19 -> true
