greda 0 -> true
greda 1 -> false
greda 2 -> false
greda 3 -> true
greda 4 -> false
greda 5 -> true
greda 6 -> false
greda 7 -> true
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> true
greda 14 -> false
greda 15 -> true
greda 16 -> true
greda 17 -> true
greda 18 -> true
greda 19 -> false
greda 20 -> false
greda 21 -> true
greda 22 -> false
greda 23 -> false
greda 24 -> false
greda 25 -> false
