greda 0 -> true
greda 1 -> true
greda 2 -> true
greda 3 -> false
greda 4 -> false
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> false
greda 9 -> true
greda 10 -> true
greda 11 -> true
greda 12 -> true
greda 13 -> false
greda 14 -> true
greda 15 -> true
greda 16 -> false
