greda 0 -> true
greda 1 -> false
greda 2 -> true
greda 3 -> true
greda 4 -> false
greda 5 -> true
greda 6 -> true
greda 7 -> true
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> false
greda 12 -> true
greda 13 -> false
greda 14 -> true
greda 15 -> true
greda 16 -> false
greda 17 -> false
greda 18 -> true
greda 19 -> false
greda 20 -> false
