greda 0 -> false
greda 1 -> false
greda 2 -> false
greda 3 -> false
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> false
greda 13 -> false
greda 14 -> true
greda 15 -> false
greda 16 -> false
greda 17 -> true
greda 18 -> false
greda 19 -> true
greda 20 -> false
greda 21 -> true
greda 22 -> false
greda 23 -> true
greda 24 -> false
greda 25 -> false
greda 26 -> false
greda 27 -> true
greda 28 -> false
