greda 0 -> true
greda 1 -> true
greda 2 -> false
greda 3 -> true
greda 4 -> true
greda 5 -> true
greda 6 -> true
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> true
greda 14 -> false
