greda 0 -> false
greda 1 -> true
greda 2 -> false
greda 3 -> false
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> false
greda 9 -> true
greda 10 -> true
greda 11 -> true
greda 12 -> false
greda 13 -> false
greda 14 -> true
greda 15 -> false
greda 16 -> false
greda 17 -> false
greda 18 -> true
greda 19 -> false
greda 20 -> true
greda 21 -> true
