greda 0 -> false
greda 1 -> false
greda 2 -> false
greda 3 -> true
greda 4 -> false
greda 5 -> false
greda 6 -> true
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> false
greda 14 -> false
