greda 0 -> true
greda 1 -> true
greda 2 -> false
greda 3 -> false
greda 4 -> true
greda 5 -> false
greda 6 -> false
greda 7 -> true
greda 8 -> false
greda 9 -> true
greda 10 -> false
greda 11 -> true
greda 12 -> true
greda 13 -> true
greda 14 -> true
greda 15 -> false
greda 16 -> true
greda 17 -> true
greda 18 -> false
greda 19 -> false
greda 20 -> true
greda 21 -> false
greda 22 -> false
greda 23 -> true
greda 24 -> true
