greda 0 -> false
greda 1 -> true
greda 2 -> false
greda 3 -> true
greda 4 -> false
greda 5 -> false
greda 6 -> false
greda 7 -> true
greda 8 -> false
greda 9 -> false
greda 10 -> false
greda 11 -> false
greda 12 -> true
greda 13 -> false
greda 14 -> false
greda 15 -> false
greda 16 -> false
greda 17 -> false
greda 18 -> true
greda 19 -> true
