greda 0 -> false
greda 1 -> true
greda 2 -> false
greda 3 -> true
greda 4 -> false
greda 5 -> false
greda 6 -> false
greda 7 -> false
greda 8 -> true
greda 9 -> true
greda 10 -> false
greda 11 -> false
