
import java.util.*;

public class Test24 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(19, 19);

        mesto.postavi(13, 14, new Tretja.Stanovanjska(20));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 7, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 14, new Tretja.Stanovanjska(85));
        mesto.postavi(15, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 14, new Tretja.Stanovanjska(7));
        mesto.postavi(4, 8, new Tretja.Stanovanjska(93));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 9, new Tretja.Poslovna());
        mesto.postavi(16, 18, new Tretja.Poslovna());
        mesto.postavi(5, 18, new Tretja.Stanovanjska(50));
        mesto.postavi(5, 12, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 12, new Tretja.Stanovanjska(54));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(4));
        mesto.postavi(5, 18, new Tretja.Stanovanjska(66));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 14, new Tretja.Poslovna());
        mesto.postavi(12, 7, new Tretja.Poslovna());
        mesto.postavi(18, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Stanovanjska(13));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(16));
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Poslovna());
        mesto.postavi(14, 4, new Tretja.Stanovanjska(61));
        mesto.postavi(5, 12, new Tretja.Stanovanjska(5));
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Stanovanjska(38));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 14, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(64));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 18, new Tretja.Stanovanjska(64));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(37));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(21));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(11, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(52));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 12, new Tretja.Stanovanjska(2));
        mesto.postavi(12, 7, new Tretja.Stanovanjska(78));
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(93));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 9, new Tretja.Stanovanjska(58));
        mesto.postavi(6, 13, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 14, new Tretja.Stanovanjska(37));
        mesto.postavi(18, 0, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 12, new Tretja.Stanovanjska(48));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 14, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(15));
        mesto.postavi(12, 16, new Tretja.Stanovanjska(76));
        mesto.postavi(18, 5, new Tretja.Stanovanjska(24));
        mesto.postavi(18, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(96));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(47));
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(17, 7, new Tretja.Poslovna());
        mesto.postavi(9, 11, new Tretja.Poslovna());
        mesto.postavi(15, 14, new Tretja.Poslovna());
        mesto.postavi(11, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(12, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 18, new Tretja.Poslovna());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(53));
        mesto.postavi(16, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 15, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Stanovanjska(64));
        mesto.postavi(7, 2, new Tretja.Stanovanjska(68));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(63));
        mesto.postavi(18, 15, new Tretja.Poslovna());
        mesto.postavi(12, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(13, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 0, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        mesto.postavi(5, 18, new Tretja.Stanovanjska(32));
        mesto.postavi(7, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 15, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(12, 14, new Tretja.Stanovanjska(61));
        mesto.postavi(14, 4, new Tretja.Stanovanjska(56));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(12, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(25));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(39));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(80));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(20));
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Stanovanjska(98));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(36));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(21));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(13, 2, new Tretja.Stanovanjska(54));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(17, 7, new Tretja.Stanovanjska(82));
        mesto.postavi(9, 12, new Tretja.Stanovanjska(74));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(14, 9, new Tretja.Stanovanjska(12));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 13, new Tretja.Stanovanjska(98));
        mesto.postavi(17, 7, new Tretja.Stanovanjska(65));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 16, new Tretja.Stanovanjska(36));
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Stanovanjska(2));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Stanovanjska(40));
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(81));
        mesto.postavi(15, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Stanovanjska(100));
        mesto.postavi(13, 14, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Stanovanjska(4));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 14, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 3, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 12, new Tretja.Poslovna());
        mesto.postavi(5, 16, new Tretja.Stanovanjska(28));
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(16));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 4, new Tretja.Stanovanjska(81));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 15, new Tretja.Stanovanjska(48));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(24));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(48));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(83));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(9));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Stanovanjska(35));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Stanovanjska(81));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        mesto.postavi(12, 7, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Stanovanjska(72));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(18));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 3, new Tretja.Stanovanjska(70));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(18, 15, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(12, 6, new Tretja.Stanovanjska(43));
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Stanovanjska(22));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 14, new Tretja.Stanovanjska(98));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(39));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 16, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 4, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Stanovanjska(54));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 3, new Tretja.Stanovanjska(13));
        mesto.postavi(12, 17, new Tretja.Stanovanjska(93));
        mesto.postavi(0, 14, new Tretja.Stanovanjska(29));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        mesto.postavi(12, 15, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(13, 14, new Tretja.Stanovanjska(97));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 18, new Tretja.Stanovanjska(83));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 7, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 2, new Tretja.Poslovna());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Stanovanjska(61));
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(6));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(5, 12, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(29));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(65));
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Poslovna());
        mesto.postavi(12, 13, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 3, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(42));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 16, new Tretja.Stanovanjska(54));
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(40));
        mesto.postavi(15, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(5, 16, new Tretja.Stanovanjska(84));
        mesto.postavi(6, 13, new Tretja.Stanovanjska(57));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(22));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Stanovanjska(47));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 5, new Tretja.Poslovna());
        mesto.postavi(18, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 9, new Tretja.Stanovanjska(78));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(93));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(30));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(100));
        mesto.postavi(1, 16, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        mesto.postavi(15, 18, new Tretja.Stanovanjska(46));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(12));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Stanovanjska(40));
        mesto.postavi(13, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 14, new Tretja.Stanovanjska(28));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(92));
        mesto.postavi(18, 5, new Tretja.Stanovanjska(9));
        mesto.postavi(15, 18, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        mesto.postavi(15, 14, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(12, 14, new Tretja.Stanovanjska(13));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(18, 5, new Tretja.Stanovanjska(51));
        mesto.postavi(13, 14, new Tretja.Stanovanjska(49));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(62));
        mesto.postavi(11, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(12, 14, new Tretja.Stanovanjska(55));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 2, new Tretja.Stanovanjska(55));
        mesto.postavi(12, 17, new Tretja.Stanovanjska(10));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(91));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(99));
        mesto.postavi(11, 2, new Tretja.Stanovanjska(40));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(14, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(14, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 18, new Tretja.Poslovna());
        mesto.postavi(12, 17, new Tretja.Stanovanjska(1));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(49));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(3));
        mesto.postavi(12, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 15, new Tretja.Poslovna());
        mesto.postavi(14, 9, new Tretja.Stanovanjska(28));
        mesto.postavi(5, 16, new Tretja.Stanovanjska(59));
        mesto.postavi(14, 15, new Tretja.Stanovanjska(88));
        mesto.postavi(5, 12, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 14, new Tretja.Stanovanjska(34));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(99));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(57));
        mesto.postavi(7, 2, new Tretja.Stanovanjska(54));
        mesto.postavi(1, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 0, new Tretja.Stanovanjska(95));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(18));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Stanovanjska(5));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Stanovanjska(61));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Stanovanjska(4));
        mesto.postavi(10, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(22));
        mesto.postavi(14, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(26));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        mesto.postavi(10, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 15, new Tretja.Stanovanjska(64));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Stanovanjska(45));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(82));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(10));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(50));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 15, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(7, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(2));
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(7, 15, new Tretja.Stanovanjska(19));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(64));
        mesto.postavi(17, 7, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(91));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(15, 18, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(9, 11, new Tretja.Stanovanjska(18));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(12, 13, new Tretja.Stanovanjska(100));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 5, new Tretja.Stanovanjska(10));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Stanovanjska(13));
        mesto.postavi(14, 5, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(52));
        mesto.postavi(15, 18, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 7, new Tretja.Stanovanjska(7));
        mesto.postavi(18, 16, new Tretja.Stanovanjska(17));
        mesto.postavi(11, 9, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(9, 0, new Tretja.Stanovanjska(28));
        mesto.postavi(6, 13, new Tretja.Stanovanjska(81));
        mesto.postavi(11, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 8, new Tretja.Stanovanjska(56));
        mesto.postavi(18, 14, new Tretja.Stanovanjska(93));
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 4, new Tretja.Poslovna());
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(5, 18, new Tretja.Stanovanjska(24));
        mesto.postavi(3, 8, new Tretja.Stanovanjska(30));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Stanovanjska(58));
        mesto.postavi(4, 8, new Tretja.Stanovanjska(65));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 17, new Tretja.Stanovanjska(62));
        mesto.postavi(11, 10, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 14, new Tretja.Stanovanjska(26));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(0, 14, new Tretja.Stanovanjska(59));
        mesto.postavi(7, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Stanovanjska(16));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Stanovanjska(35));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
