
import java.util.*;

public class Test18 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(26, 18);

        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(35));
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(23, 2, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(63));
        mesto.postavi(14, 0, new Tretja.Stanovanjska(38));
        mesto.postavi(0, 7, new Tretja.Stanovanjska(36));
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(25, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(89));
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(10, 15, new Tretja.Poslovna());
        mesto.postavi(25, 6, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Poslovna());
        mesto.postavi(10, 17, new Tretja.Stanovanjska(62));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Poslovna());
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(14, 2, new Tretja.Stanovanjska(76));
        mesto.postavi(24, 16, new Tretja.Stanovanjska(17));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(89));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(93));
        mesto.postavi(22, 9, new Tretja.Stanovanjska(80));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 15, new Tretja.Stanovanjska(43));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 14, new Tretja.Poslovna());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 10, new Tretja.Stanovanjska(78));
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 15, new Tretja.Stanovanjska(37));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(14, 3, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 13, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(7, 6, new Tretja.Stanovanjska(95));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        mesto.postavi(21, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(96));
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(10, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(24, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 9, new Tretja.Stanovanjska(51));
        mesto.postavi(5, 2, new Tretja.Poslovna());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(94));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(78));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(47));
        mesto.postavi(17, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 15, new Tretja.Stanovanjska(88));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Stanovanjska(55));
        mesto.postavi(24, 11, new Tretja.Stanovanjska(33));
        mesto.postavi(25, 7, new Tretja.Poslovna());
        mesto.postavi(5, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 15, new Tretja.Stanovanjska(98));
        mesto.postavi(2, 14, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Stanovanjska(28));
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(19, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 3, new Tretja.Poslovna());
        mesto.postavi(24, 11, new Tretja.Poslovna());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(15));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 14, new Tretja.Stanovanjska(36));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(20, 13, new Tretja.Poslovna());
        mesto.postavi(18, 13, new Tretja.Stanovanjska(65));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(65));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(24));
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(25, 15, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Stanovanjska(16));
        mesto.postavi(3, 14, new Tretja.Stanovanjska(89));
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(21, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 1, new Tretja.Poslovna());
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(21, 15, new Tretja.Stanovanjska(72));
        mesto.postavi(6, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 7, new Tretja.Stanovanjska(18));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(11));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 5, new Tretja.Stanovanjska(67));
        mesto.postavi(1, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 15, new Tretja.Stanovanjska(79));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(14, 12, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(83));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(23, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 2, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(1));
        mesto.postavi(15, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 6, new Tretja.Stanovanjska(4));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(17, 5, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 17, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Stanovanjska(46));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(10, 15, new Tretja.Stanovanjska(82));
        mesto.postavi(23, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 7, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 0, new Tretja.Stanovanjska(4));
        mesto.postavi(6, 11, new Tretja.Stanovanjska(33));
        mesto.postavi(17, 4, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Stanovanjska(14));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Stanovanjska(46));
        mesto.postavi(3, 4, new Tretja.Stanovanjska(63));
        mesto.postavi(7, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 16, new Tretja.Stanovanjska(41));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 5, new Tretja.Poslovna());
        mesto.postavi(11, 1, new Tretja.Stanovanjska(63));
        mesto.postavi(14, 2, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(21));
        mesto.postavi(6, 0, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Poslovna());
        mesto.postavi(4, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 5, new Tretja.Stanovanjska(85));
        mesto.postavi(7, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(1, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(10));
        mesto.postavi(19, 7, new Tretja.Stanovanjska(29));
        mesto.postavi(12, 11, new Tretja.Stanovanjska(21));
        mesto.postavi(18, 12, new Tretja.Stanovanjska(19));
        mesto.postavi(22, 16, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 5, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 14, new Tretja.Stanovanjska(19));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 12, new Tretja.Stanovanjska(32));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(18, 17, new Tretja.Stanovanjska(18));
        mesto.postavi(12, 9, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Stanovanjska(3));
        mesto.postavi(24, 16, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 16, new Tretja.Poslovna());
        mesto.postavi(16, 8, new Tretja.Stanovanjska(84));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(32));
        mesto.postavi(18, 17, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Poslovna());
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 12, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Stanovanjska(84));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(72));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(4));
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(2, 16, new Tretja.Stanovanjska(99));
        mesto.postavi(18, 10, new Tretja.Stanovanjska(36));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(62));
        mesto.postavi(23, 0, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 0, new Tretja.Poslovna());
        mesto.postavi(8, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 6, new Tretja.Stanovanjska(36));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Stanovanjska(74));
        mesto.postavi(4, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 7, new Tretja.Stanovanjska(4));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(13, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 16, new Tretja.Stanovanjska(75));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        mesto.postavi(16, 0, new Tretja.Stanovanjska(95));
        mesto.postavi(9, 3, new Tretja.Stanovanjska(46));
        mesto.postavi(17, 3, new Tretja.Stanovanjska(18));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(55));
        mesto.postavi(24, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(11, 3, new Tretja.Stanovanjska(78));
        mesto.postavi(17, 5, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Stanovanjska(39));
        mesto.postavi(11, 7, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Stanovanjska(71));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 0, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(99));
        mesto.postavi(11, 7, new Tretja.Stanovanjska(93));
        mesto.postavi(17, 5, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(15));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Stanovanjska(73));
        mesto.postavi(16, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 4, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        mesto.postavi(15, 15, new Tretja.Stanovanjska(46));
        mesto.postavi(16, 1, new Tretja.Stanovanjska(88));
        mesto.postavi(5, 9, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(17, 6, new Tretja.Poslovna());
        mesto.postavi(22, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 17, new Tretja.Stanovanjska(31));
        mesto.postavi(15, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 1, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(89));
        mesto.postavi(25, 16, new Tretja.Stanovanjska(14));
        mesto.postavi(16, 8, new Tretja.Poslovna());
        mesto.postavi(23, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(14, 14, new Tretja.Stanovanjska(93));
        mesto.postavi(24, 11, new Tretja.Stanovanjska(71));
        mesto.postavi(0, 7, new Tretja.Stanovanjska(50));
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(10, 5, new Tretja.Stanovanjska(30));
        mesto.postavi(14, 6, new Tretja.Stanovanjska(39));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 16, new Tretja.Poslovna());
        mesto.postavi(18, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(15, 6, new Tretja.Stanovanjska(80));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 6, new Tretja.Stanovanjska(84));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(81));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Stanovanjska(24));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(17, 15, new Tretja.Stanovanjska(62));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(67));
        mesto.postavi(23, 10, new Tretja.Poslovna());
        mesto.postavi(18, 13, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(95));
        mesto.postavi(25, 6, new Tretja.Stanovanjska(95));
        mesto.postavi(17, 2, new Tretja.Stanovanjska(21));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Stanovanjska(44));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(30));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(76));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 14, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(23, 10, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(99));
        mesto.postavi(25, 9, new Tretja.Poslovna());
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(25, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 12, new Tretja.Stanovanjska(100));
        mesto.postavi(17, 3, new Tretja.Poslovna());
        mesto.postavi(12, 8, new Tretja.Stanovanjska(21));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 14, new Tretja.Stanovanjska(84));
        mesto.postavi(2, 2, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 5, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(19, 5, new Tretja.Stanovanjska(3));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(83));
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Stanovanjska(12));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(23, 8, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 14, new Tretja.Stanovanjska(35));
        mesto.postavi(24, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 10, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 6, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(25));
        mesto.postavi(15, 0, new Tretja.Stanovanjska(91));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(65));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 8, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 15, new Tretja.Stanovanjska(56));
        mesto.postavi(3, 17, new Tretja.Poslovna());
        mesto.postavi(16, 15, new Tretja.Stanovanjska(88));
        mesto.postavi(23, 10, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(16));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(18));
        mesto.postavi(23, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 7, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 17, new Tretja.Poslovna());
        mesto.postavi(2, 16, new Tretja.Poslovna());
        mesto.postavi(12, 9, new Tretja.Stanovanjska(82));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(97));
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Stanovanjska(24));
        mesto.postavi(2, 13, new Tretja.Stanovanjska(89));
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 5, new Tretja.Stanovanjska(11));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(82));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Stanovanjska(73));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(44));
        mesto.postavi(13, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 5, new Tretja.Stanovanjska(46));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(11, 3, new Tretja.Stanovanjska(58));
        mesto.postavi(25, 16, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(9, 13, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 13, new Tretja.Poslovna());
        mesto.postavi(24, 3, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(54));
        mesto.postavi(18, 6, new Tretja.Stanovanjska(22));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(86));
        mesto.postavi(0, 11, new Tretja.Stanovanjska(31));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(22, 16, new Tretja.Stanovanjska(21));
        mesto.postavi(17, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        mesto.postavi(21, 15, new Tretja.Stanovanjska(23));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(100));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(43));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 5, new Tretja.Stanovanjska(15));
        mesto.postavi(25, 16, new Tretja.Poslovna());
        mesto.postavi(25, 15, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 0, new Tretja.Stanovanjska(66));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Stanovanjska(86));
        mesto.postavi(4, 1, new Tretja.Stanovanjska(81));
        mesto.postavi(25, 15, new Tretja.Poslovna());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(16, 12, new Tretja.Stanovanjska(91));
        mesto.postavi(14, 6, new Tretja.Stanovanjska(86));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(84));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 9, new Tretja.Stanovanjska(34));
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Stanovanjska(26));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(83));
        mesto.postavi(23, 10, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Stanovanjska(79));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(82));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 3, new Tretja.Stanovanjska(60));
        mesto.postavi(2, 6, new Tretja.Stanovanjska(93));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 1, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Stanovanjska(63));
        mesto.postavi(17, 4, new Tretja.Poslovna());
        mesto.postavi(16, 12, new Tretja.Poslovna());
        mesto.postavi(25, 6, new Tretja.Stanovanjska(59));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Stanovanjska(82));
        mesto.postavi(14, 14, new Tretja.Stanovanjska(18));
        mesto.postavi(20, 14, new Tretja.Stanovanjska(2));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(25, 9, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(60));
        mesto.postavi(17, 2, new Tretja.Stanovanjska(76));
        mesto.postavi(1, 8, new Tretja.Poslovna());
        mesto.postavi(12, 17, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Stanovanjska(51));
        mesto.postavi(20, 5, new Tretja.Stanovanjska(4));
        mesto.postavi(12, 0, new Tretja.Stanovanjska(55));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 14, new Tretja.Poslovna());
        mesto.postavi(9, 1, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 11, new Tretja.Stanovanjska(85));
        mesto.postavi(2, 17, new Tretja.Stanovanjska(7));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(43));
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(52));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Stanovanjska(21));
        mesto.postavi(11, 7, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(95));
        mesto.postavi(9, 13, new Tretja.Poslovna());
        mesto.postavi(13, 7, new Tretja.Poslovna());
        mesto.postavi(17, 4, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(5, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 5, new Tretja.Stanovanjska(17));
        mesto.postavi(14, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(16, 12, new Tretja.Stanovanjska(85));
        mesto.postavi(3, 1, new Tretja.Stanovanjska(98));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Stanovanjska(85));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(14, 2, new Tretja.Poslovna());
        mesto.postavi(17, 4, new Tretja.Poslovna());
        mesto.postavi(3, 8, new Tretja.Stanovanjska(7));
        mesto.postavi(23, 10, new Tretja.Stanovanjska(11));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 17, new Tretja.Stanovanjska(32));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 17, new Tretja.Stanovanjska(59));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(53));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 2, new Tretja.Poslovna());
        mesto.postavi(12, 9, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(41));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Stanovanjska(16));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 6, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 5, new Tretja.Stanovanjska(78));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 16, new Tretja.Stanovanjska(2));
        mesto.postavi(3, 14, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(9));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 14, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 12, new Tretja.Poslovna());
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 0, new Tretja.Poslovna());
        mesto.postavi(11, 13, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(86));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(65));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 0, new Tretja.Stanovanjska(48));
        mesto.postavi(1, 0, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(0, 12, new Tretja.Stanovanjska(18));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(9));
        mesto.postavi(25, 6, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(2, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(31));
        mesto.postavi(22, 9, new Tretja.Stanovanjska(94));
        mesto.postavi(20, 15, new Tretja.Stanovanjska(99));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(17, 15, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 1, new Tretja.Stanovanjska(75));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(58));
        mesto.postavi(17, 17, new Tretja.Stanovanjska(68));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 15, new Tretja.Poslovna());
        mesto.postavi(13, 5, new Tretja.Stanovanjska(50));
        mesto.postavi(4, 11, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(84));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 9, new Tretja.Poslovna());
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Stanovanjska(90));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 3, new Tretja.Stanovanjska(6));
        mesto.postavi(14, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(91));
        mesto.postavi(18, 17, new Tretja.Poslovna());
        mesto.postavi(23, 14, new Tretja.Poslovna());
        mesto.postavi(6, 6, new Tretja.Stanovanjska(51));
        mesto.postavi(19, 5, new Tretja.Stanovanjska(31));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 11, new Tretja.Stanovanjska(31));
        mesto.postavi(12, 9, new Tretja.Poslovna());
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(98));
        mesto.postavi(25, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(0, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(30));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(17));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(14, 12, new Tretja.Poslovna());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(88));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(30));
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(14, 12, new Tretja.Stanovanjska(21));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(98));
        mesto.postavi(25, 7, new Tretja.Poslovna());
        mesto.postavi(2, 17, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(53));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(5));
        mesto.postavi(18, 16, new Tretja.Stanovanjska(29));
        mesto.postavi(3, 17, new Tretja.Stanovanjska(70));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(27));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(41));
        mesto.postavi(11, 0, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(31));
        mesto.postavi(14, 6, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 17, new Tretja.Poslovna());
        mesto.postavi(12, 15, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(34));
        mesto.postavi(18, 13, new Tretja.Poslovna());
        mesto.postavi(6, 0, new Tretja.Stanovanjska(38));
        mesto.postavi(19, 5, new Tretja.Stanovanjska(58));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(29));
        mesto.postavi(13, 5, new Tretja.Stanovanjska(16));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 14, new Tretja.Stanovanjska(51));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(72));
        mesto.postavi(5, 2, new Tretja.Stanovanjska(66));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 14, new Tretja.Poslovna());
        mesto.postavi(24, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        mesto.postavi(25, 6, new Tretja.Stanovanjska(4));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(1, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 11, new Tretja.Poslovna());
        mesto.postavi(0, 7, new Tretja.Stanovanjska(77));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(74));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(0, 2, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(2));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 17, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Stanovanjska(17));
        mesto.postavi(5, 9, new Tretja.Stanovanjska(9));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(27));
        mesto.postavi(8, 14, new Tretja.Stanovanjska(90));
        mesto.postavi(19, 10, new Tretja.Poslovna());
        mesto.postavi(7, 1, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(21, 16, new Tretja.Poslovna());
        mesto.postavi(8, 6, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(65));
        mesto.postavi(3, 14, new Tretja.Poslovna());
        mesto.postavi(23, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(70));
        mesto.postavi(22, 11, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(63));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(96));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        mesto.postavi(24, 3, new Tretja.Stanovanjska(6));
        mesto.postavi(16, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 9, new Tretja.Stanovanjska(18));
        mesto.postavi(25, 6, new Tretja.Stanovanjska(35));
        mesto.postavi(21, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
