
import java.util.*;

public class Test02 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(26, 25);

        mesto.postavi(19, 13, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(22, 16, new Tretja.Stanovanjska(86));
        mesto.postavi(23, 6, new Tretja.Poslovna());
        mesto.postavi(14, 1, new Tretja.Stanovanjska(20));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(17, 19, new Tretja.Poslovna());
        mesto.postavi(1, 21, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Stanovanjska(92));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(16, 15, new Tretja.Poslovna());
        mesto.postavi(12, 18, new Tretja.Stanovanjska(87));
        mesto.postavi(5, 18, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 11, new Tretja.Stanovanjska(33));
        mesto.postavi(3, 12, new Tretja.Stanovanjska(28));
        mesto.postavi(22, 24, new Tretja.Poslovna());
        mesto.postavi(16, 19, new Tretja.Stanovanjska(70));
        mesto.postavi(1, 15, new Tretja.Stanovanjska(55));
        mesto.postavi(19, 18, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 6, new Tretja.Stanovanjska(26));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Poslovna());
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(25, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(96));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(51));
        mesto.postavi(24, 9, new Tretja.Stanovanjska(82));
        mesto.postavi(1, 15, new Tretja.Stanovanjska(52));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(87));
        mesto.postavi(18, 17, new Tretja.Poslovna());
        mesto.postavi(7, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 6, new Tretja.Stanovanjska(47));
        mesto.postavi(22, 24, new Tretja.Stanovanjska(5));
        mesto.postavi(23, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(1));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(3));
        mesto.postavi(7, 23, new Tretja.Stanovanjska(43));
        mesto.postavi(3, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 21, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(23, 7, new Tretja.Poslovna());
        mesto.postavi(8, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 21, new Tretja.Stanovanjska(44));
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(20, 21, new Tretja.Stanovanjska(40));
        mesto.postavi(19, 23, new Tretja.Stanovanjska(83));
        mesto.postavi(17, 23, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 5, new Tretja.Stanovanjska(89));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(9));
        mesto.postavi(25, 2, new Tretja.Stanovanjska(77));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 18, new Tretja.Stanovanjska(60));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(4, 23, new Tretja.Stanovanjska(90));
        mesto.postavi(3, 23, new Tretja.Stanovanjska(26));
        mesto.postavi(0, 5, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 13, new Tretja.Stanovanjska(48));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 21, new Tretja.Poslovna());
        mesto.postavi(9, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 20, new Tretja.Stanovanjska(35));
        mesto.postavi(13, 15, new Tretja.Poslovna());
        mesto.postavi(14, 24, new Tretja.Stanovanjska(26));
        mesto.postavi(13, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 22, new Tretja.Stanovanjska(75));
        mesto.postavi(17, 18, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Stanovanjska(99));
        mesto.postavi(19, 23, new Tretja.Stanovanjska(20));
        mesto.postavi(18, 23, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        mesto.postavi(11, 5, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        mesto.postavi(13, 10, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(6, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 19, new Tretja.Poslovna());
        mesto.postavi(23, 1, new Tretja.Poslovna());
        mesto.postavi(19, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(10, 20, new Tretja.Stanovanjska(25));
        mesto.postavi(2, 3, new Tretja.Stanovanjska(6));
        mesto.postavi(5, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 6, new Tretja.Poslovna());
        mesto.postavi(4, 12, new Tretja.Stanovanjska(64));
        mesto.postavi(5, 15, new Tretja.Stanovanjska(86));
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 17, new Tretja.Stanovanjska(32));
        mesto.postavi(12, 22, new Tretja.Stanovanjska(99));
        mesto.postavi(22, 12, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(6, 12, new Tretja.Stanovanjska(11));
        mesto.postavi(19, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Poslovna());
        mesto.postavi(23, 18, new Tretja.Stanovanjska(6));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        mesto.postavi(10, 17, new Tretja.Poslovna());
        mesto.postavi(19, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 9, new Tretja.Stanovanjska(83));
        mesto.postavi(21, 7, new Tretja.Stanovanjska(10));
        mesto.postavi(19, 2, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 5, new Tretja.Stanovanjska(88));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Stanovanjska(32));
        mesto.postavi(12, 3, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Stanovanjska(16));
        mesto.postavi(13, 16, new Tretja.Stanovanjska(47));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 1, new Tretja.Stanovanjska(7));
        mesto.postavi(17, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(23, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 22, new Tretja.Stanovanjska(43));
        mesto.postavi(17, 11, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Stanovanjska(49));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(23, 4, new Tretja.Stanovanjska(75));
        mesto.postavi(23, 8, new Tretja.Poslovna());
        mesto.postavi(24, 17, new Tretja.Stanovanjska(44));
        mesto.postavi(4, 12, new Tretja.Stanovanjska(87));
        mesto.postavi(16, 20, new Tretja.Poslovna());
        mesto.postavi(6, 11, new Tretja.Stanovanjska(24));
        mesto.postavi(6, 21, new Tretja.Stanovanjska(46));
        mesto.postavi(14, 12, new Tretja.Stanovanjska(37));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 24, new Tretja.Stanovanjska(58));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(12));
        mesto.postavi(0, 19, new Tretja.Poslovna());
        mesto.postavi(15, 22, new Tretja.Poslovna());
        mesto.postavi(12, 22, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 22, new Tretja.Stanovanjska(26));
        mesto.postavi(11, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 19, new Tretja.Poslovna());
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(14, 7, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 9, new Tretja.Stanovanjska(4));
        mesto.postavi(3, 9, new Tretja.Poslovna());
        mesto.postavi(7, 23, new Tretja.Stanovanjska(46));
        mesto.postavi(3, 0, new Tretja.Stanovanjska(48));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(25, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(73));
        mesto.postavi(21, 24, new Tretja.Stanovanjska(26));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        mesto.postavi(17, 2, new Tretja.Poslovna());
        mesto.postavi(14, 16, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(75));
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Stanovanjska(12));
        mesto.postavi(1, 23, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 21, new Tretja.Poslovna());
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(18, 13, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(24, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 22, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Stanovanjska(58));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(25));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 3, new Tretja.Poslovna());
        mesto.postavi(2, 5, new Tretja.Poslovna());
        mesto.postavi(15, 16, new Tretja.Stanovanjska(34));
        mesto.postavi(18, 9, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Stanovanjska(38));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(15, 16, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(9, 2, new Tretja.Stanovanjska(27));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(81));
        mesto.postavi(7, 21, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 11, new Tretja.Stanovanjska(71));
        mesto.postavi(18, 16, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Stanovanjska(73));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 23, new Tretja.Stanovanjska(71));
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(24, 6, new Tretja.Stanovanjska(90));
        mesto.postavi(8, 24, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 2, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 18, new Tretja.Stanovanjska(96));
        mesto.postavi(24, 9, new Tretja.Poslovna());
        mesto.postavi(14, 17, new Tretja.Stanovanjska(10));
        mesto.postavi(20, 11, new Tretja.Poslovna());
        mesto.postavi(16, 16, new Tretja.Poslovna());
        mesto.postavi(3, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(25, 17, new Tretja.Poslovna());
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(20, 23, new Tretja.Poslovna());
        mesto.postavi(0, 20, new Tretja.Stanovanjska(78));
        mesto.postavi(9, 12, new Tretja.Stanovanjska(89));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(66));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(30));
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        mesto.postavi(1, 11, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 23, new Tretja.Stanovanjska(9));
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(25, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 23, new Tretja.Poslovna());
        mesto.postavi(5, 1, new Tretja.Poslovna());
        mesto.postavi(8, 20, new Tretja.Stanovanjska(45));
        mesto.postavi(22, 20, new Tretja.Stanovanjska(83));
        mesto.postavi(25, 17, new Tretja.Poslovna());
        mesto.postavi(25, 6, new Tretja.Poslovna());
        mesto.postavi(24, 14, new Tretja.Stanovanjska(22));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 20, new Tretja.Stanovanjska(77));
        mesto.postavi(0, 4, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Stanovanjska(50));
        mesto.postavi(8, 4, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 18, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(81));
        mesto.postavi(14, 7, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Stanovanjska(70));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(3));
        mesto.postavi(22, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(10, 5, new Tretja.Stanovanjska(2));
        mesto.postavi(13, 19, new Tretja.Stanovanjska(64));
        mesto.postavi(12, 11, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 5, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 1, new Tretja.Poslovna());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(16));
        mesto.postavi(18, 7, new Tretja.Stanovanjska(62));
        mesto.postavi(4, 3, new Tretja.Poslovna());
        mesto.postavi(20, 21, new Tretja.Stanovanjska(22));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(14));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 19, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(90));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 18, new Tretja.Stanovanjska(25));
        mesto.postavi(7, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 20, new Tretja.Stanovanjska(96));
        mesto.postavi(14, 18, new Tretja.Poslovna());
        mesto.postavi(19, 23, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 23, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Poslovna());
        mesto.postavi(20, 4, new Tretja.Stanovanjska(71));
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(99));
        mesto.postavi(13, 6, new Tretja.Stanovanjska(50));
        mesto.postavi(24, 14, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 14, new Tretja.Stanovanjska(23));
        mesto.postavi(17, 9, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(39));
        mesto.postavi(12, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 21, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 20, new Tretja.Stanovanjska(16));
        mesto.postavi(15, 12, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 21, new Tretja.Stanovanjska(77));
        mesto.postavi(10, 15, new Tretja.Stanovanjska(59));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 3, new Tretja.Poslovna());
        mesto.postavi(14, 14, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(70));
        mesto.postavi(13, 10, new Tretja.Stanovanjska(68));
        mesto.postavi(14, 16, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Poslovna());
        mesto.postavi(22, 14, new Tretja.Stanovanjska(100));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(10, 5, new Tretja.Stanovanjska(87));
        mesto.postavi(15, 15, new Tretja.Stanovanjska(32));
        mesto.postavi(25, 9, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        mesto.postavi(14, 14, new Tretja.Poslovna());
        mesto.postavi(7, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 15, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 21, new Tretja.Stanovanjska(14));
        mesto.postavi(25, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 13, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 24, new Tretja.Stanovanjska(55));
        mesto.postavi(18, 7, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 15, new Tretja.Poslovna());
        mesto.postavi(14, 24, new Tretja.Stanovanjska(7));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 9, new Tretja.Poslovna());
        mesto.postavi(8, 24, new Tretja.Stanovanjska(90));
        mesto.postavi(22, 12, new Tretja.Stanovanjska(31));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(5));
        mesto.postavi(6, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 17, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(54));
        mesto.postavi(22, 16, new Tretja.Stanovanjska(96));
        mesto.postavi(12, 1, new Tretja.Stanovanjska(99));
        mesto.postavi(9, 13, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(33));
        mesto.postavi(14, 17, new Tretja.Poslovna());
        mesto.postavi(4, 19, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Stanovanjska(48));
        mesto.postavi(13, 21, new Tretja.Poslovna());
        mesto.postavi(0, 19, new Tretja.Stanovanjska(100));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(19, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 24, new Tretja.Stanovanjska(64));
        mesto.postavi(5, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 0, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        mesto.postavi(25, 22, new Tretja.Poslovna());
        mesto.postavi(2, 8, new Tretja.Stanovanjska(94));
        mesto.postavi(20, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 6, new Tretja.Poslovna());
        mesto.postavi(22, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        mesto.postavi(14, 13, new Tretja.Stanovanjska(41));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(68));
        mesto.postavi(19, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 12, new Tretja.Stanovanjska(47));
        mesto.postavi(0, 0, new Tretja.Stanovanjska(23));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 9, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 11, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(24, 17, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 5, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 10, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(25, 10, new Tretja.Poslovna());
        mesto.postavi(2, 8, new Tretja.Poslovna());
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 2, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 11, new Tretja.Stanovanjska(83));
        mesto.postavi(13, 15, new Tretja.Stanovanjska(74));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(72));
        mesto.postavi(25, 11, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(20, 21, new Tretja.Poslovna());
        mesto.postavi(9, 22, new Tretja.Stanovanjska(68));
        mesto.postavi(24, 4, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 23, new Tretja.Stanovanjska(18));
        mesto.postavi(15, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 1, new Tretja.Stanovanjska(96));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(77));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 15, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 17, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 6, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(12, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 15, new Tretja.Stanovanjska(76));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        mesto.postavi(23, 18, new Tretja.Stanovanjska(20));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        mesto.postavi(18, 13, new Tretja.Stanovanjska(4));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(21, 0, new Tretja.Poslovna());
        mesto.postavi(11, 5, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(58));
        mesto.postavi(23, 17, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Stanovanjska(68));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(77));
        mesto.postavi(22, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(10, 20, new Tretja.Stanovanjska(39));
        mesto.postavi(17, 14, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 3, new Tretja.Stanovanjska(51));
        mesto.postavi(18, 6, new Tretja.Poslovna());
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Stanovanjska(38));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(44));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 7, new Tretja.Stanovanjska(29));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 22, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 3, new Tretja.Poslovna());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(97));
        mesto.postavi(6, 22, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(33));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(66));
        mesto.postavi(17, 10, new Tretja.Poslovna());
        mesto.postavi(16, 10, new Tretja.Poslovna());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(96));
        mesto.postavi(15, 22, new Tretja.Stanovanjska(93));
        mesto.postavi(14, 20, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 18, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 24, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Stanovanjska(32));
        mesto.postavi(18, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 6, new Tretja.Stanovanjska(80));
        mesto.postavi(6, 14, new Tretja.Stanovanjska(95));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 6, new Tretja.Stanovanjska(93));
        mesto.postavi(14, 22, new Tretja.Stanovanjska(11));
        mesto.postavi(3, 24, new Tretja.Poslovna());
        mesto.postavi(1, 11, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 13, new Tretja.Stanovanjska(59));
        mesto.postavi(7, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 2, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Stanovanjska(18));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 17, new Tretja.Stanovanjska(51));
        mesto.postavi(17, 4, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 24, new Tretja.Poslovna());
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(12, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 1, new Tretja.Stanovanjska(29));
        mesto.postavi(25, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 12, new Tretja.Stanovanjska(52));
        mesto.postavi(16, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 23, new Tretja.Stanovanjska(68));
        mesto.postavi(14, 18, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Stanovanjska(18));
        mesto.postavi(21, 7, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(63));
        mesto.postavi(20, 23, new Tretja.Stanovanjska(51));
        mesto.postavi(9, 21, new Tretja.Stanovanjska(74));
        mesto.postavi(14, 16, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 12, new Tretja.Stanovanjska(29));
        mesto.postavi(8, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 15, new Tretja.Stanovanjska(20));
        mesto.postavi(23, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(25, 10, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(19, 1, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(84));
        mesto.postavi(24, 9, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(16, 10, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 11, new Tretja.Stanovanjska(47));
        mesto.postavi(24, 3, new Tretja.Stanovanjska(65));
        mesto.postavi(14, 10, new Tretja.Stanovanjska(38));
        mesto.postavi(21, 24, new Tretja.Poslovna());
        mesto.postavi(23, 6, new Tretja.Stanovanjska(9));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 24, new Tretja.Poslovna());
        mesto.postavi(18, 17, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(17, 18, new Tretja.Poslovna());
        mesto.postavi(19, 3, new Tretja.Stanovanjska(32));
        mesto.postavi(1, 23, new Tretja.Stanovanjska(89));
        mesto.postavi(14, 1, new Tretja.Stanovanjska(29));
        mesto.postavi(8, 11, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(83));
        mesto.postavi(24, 5, new Tretja.Stanovanjska(12));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(48));
        mesto.postavi(24, 17, new Tretja.Stanovanjska(65));
        mesto.postavi(17, 3, new Tretja.Stanovanjska(48));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(6, 21, new Tretja.Stanovanjska(70));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 23, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 3, new Tretja.Stanovanjska(8));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 22, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Stanovanjska(64));
        mesto.postavi(15, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
