
import java.util.*;

public class Test13 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(19, 17);

        mesto.postavi(16, 8, new Tretja.Stanovanjska(83));
        mesto.postavi(2, 9, new Tretja.Stanovanjska(96));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(9, 16, new Tretja.Stanovanjska(74));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(45));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(99));
        mesto.postavi(4, 2, new Tretja.Stanovanjska(66));
        mesto.postavi(14, 15, new Tretja.Stanovanjska(36));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 6, new Tretja.Stanovanjska(2));
        mesto.postavi(15, 2, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(65));
        mesto.postavi(2, 4, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 2, new Tretja.Stanovanjska(99));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 6, new Tretja.Stanovanjska(16));
        mesto.postavi(2, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Stanovanjska(8));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 7, new Tretja.Poslovna());
        mesto.postavi(1, 1, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 9, new Tretja.Poslovna());
        mesto.postavi(12, 15, new Tretja.Stanovanjska(90));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(0, 16, new Tretja.Stanovanjska(90));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 10, new Tretja.Stanovanjska(71));
        mesto.postavi(18, 15, new Tretja.Poslovna());
        mesto.postavi(4, 16, new Tretja.Stanovanjska(63));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(66));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(92));
        mesto.postavi(15, 13, new Tretja.Stanovanjska(27));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 9, new Tretja.Stanovanjska(44));
        mesto.postavi(1, 10, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 8, new Tretja.Stanovanjska(2));
        mesto.postavi(5, 2, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 7, new Tretja.Stanovanjska(9));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 1, new Tretja.Stanovanjska(77));
        mesto.postavi(9, 14, new Tretja.Stanovanjska(84));
        mesto.postavi(4, 14, new Tretja.Stanovanjska(36));
        mesto.postavi(15, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 2, new Tretja.Poslovna());
        mesto.postavi(12, 5, new Tretja.Stanovanjska(73));
        mesto.postavi(7, 4, new Tretja.Stanovanjska(31));
        mesto.postavi(1, 3, new Tretja.Stanovanjska(10));
        mesto.postavi(12, 10, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(15, 1, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(84));
        mesto.postavi(13, 1, new Tretja.Stanovanjska(7));
        mesto.postavi(8, 5, new Tretja.Stanovanjska(95));
        mesto.postavi(15, 15, new Tretja.Stanovanjska(15));
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Stanovanjska(88));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(15, 7, new Tretja.Poslovna());
        mesto.postavi(17, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 2, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 6, new Tretja.Stanovanjska(98));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(14, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(41));
        mesto.postavi(3, 15, new Tretja.Stanovanjska(12));
        mesto.postavi(6, 6, new Tretja.Stanovanjska(25));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(15));
        mesto.postavi(1, 7, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Stanovanjska(39));
        mesto.postavi(0, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Stanovanjska(74));
        mesto.postavi(16, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(77));
        mesto.postavi(16, 7, new Tretja.Stanovanjska(28));
        mesto.postavi(7, 7, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 0, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(94));
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Stanovanjska(16));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(11));
        mesto.postavi(7, 3, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 4, new Tretja.Poslovna());
        mesto.postavi(17, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 7, new Tretja.Stanovanjska(47));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 14, new Tretja.Poslovna());
        mesto.postavi(14, 12, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 16, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 5, new Tretja.Stanovanjska(100));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(90));
        mesto.postavi(9, 7, new Tretja.Stanovanjska(25));
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
