
import java.util.*;

public class Test10 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(30, 30);

        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 3, new Tretja.Stanovanjska(11));
        mesto.postavi(14, 12, new Tretja.Stanovanjska(83));
        mesto.postavi(22, 17, new Tretja.Stanovanjska(83));
        mesto.postavi(13, 14, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Stanovanjska(31));
        mesto.postavi(24, 21, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Poslovna());
        mesto.postavi(25, 29, new Tretja.Poslovna());
        mesto.postavi(21, 12, new Tretja.Stanovanjska(57));
        mesto.postavi(11, 4, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 29, new Tretja.Stanovanjska(53));
        mesto.postavi(23, 3, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 23, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 23, new Tretja.Stanovanjska(22));
        mesto.postavi(26, 8, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 26, new Tretja.Stanovanjska(62));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 16, new Tretja.Stanovanjska(38));
        mesto.postavi(5, 29, new Tretja.Poslovna());
        mesto.postavi(25, 26, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 5, new Tretja.Poslovna());
        mesto.postavi(13, 16, new Tretja.Stanovanjska(43));
        mesto.postavi(19, 28, new Tretja.Poslovna());
        mesto.postavi(15, 17, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 3, new Tretja.Poslovna());
        mesto.postavi(14, 5, new Tretja.Poslovna());
        mesto.postavi(6, 12, new Tretja.Poslovna());
        mesto.postavi(4, 29, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 23, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(95));
        mesto.postavi(24, 25, new Tretja.Stanovanjska(32));
        mesto.postavi(1, 14, new Tretja.Stanovanjska(45));
        mesto.postavi(25, 11, new Tretja.Stanovanjska(53));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 21, new Tretja.Stanovanjska(99));
        mesto.postavi(4, 7, new Tretja.Stanovanjska(63));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 14, new Tretja.Stanovanjska(44));
        mesto.postavi(27, 23, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(27, 29, new Tretja.Stanovanjska(80));
        mesto.postavi(21, 26, new Tretja.Poslovna());
        mesto.postavi(19, 4, new Tretja.Stanovanjska(30));
        mesto.postavi(22, 16, new Tretja.Poslovna());
        mesto.postavi(10, 28, new Tretja.Stanovanjska(32));
        mesto.postavi(10, 28, new Tretja.Stanovanjska(68));
        mesto.postavi(14, 29, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 14, new Tretja.Stanovanjska(28));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(81));
        mesto.postavi(18, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        mesto.postavi(17, 10, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Stanovanjska(28));
        mesto.postavi(21, 24, new Tretja.Stanovanjska(48));
        mesto.postavi(26, 3, new Tretja.Poslovna());
        mesto.postavi(5, 26, new Tretja.Stanovanjska(49));
        mesto.postavi(19, 1, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 20, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 25, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 14, new Tretja.Poslovna());
        mesto.postavi(1, 21, new Tretja.Stanovanjska(64));
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(15, 8, new Tretja.Stanovanjska(7));
        mesto.postavi(8, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 13, new Tretja.Stanovanjska(9));
        mesto.postavi(0, 6, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 5, new Tretja.Poslovna());
        mesto.postavi(26, 29, new Tretja.Stanovanjska(35));
        mesto.postavi(8, 16, new Tretja.Poslovna());
        mesto.postavi(5, 28, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 14, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 27, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Stanovanjska(73));
        mesto.postavi(7, 21, new Tretja.Stanovanjska(79));
        mesto.postavi(9, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 28, new Tretja.Stanovanjska(76));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 2, new Tretja.Stanovanjska(58));
        mesto.postavi(28, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 8, new Tretja.Stanovanjska(88));
        mesto.postavi(18, 27, new Tretja.Stanovanjska(20));
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(23, 24, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 28, new Tretja.Poslovna());
        mesto.postavi(12, 25, new Tretja.Poslovna());
        mesto.postavi(24, 6, new Tretja.Poslovna());
        mesto.postavi(0, 11, new Tretja.Poslovna());
        mesto.postavi(20, 11, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 28, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 1, new Tretja.Poslovna());
        mesto.postavi(17, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(11));
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 12, new Tretja.Stanovanjska(78));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        mesto.postavi(10, 18, new Tretja.Stanovanjska(55));
        mesto.postavi(29, 22, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 20, new Tretja.Poslovna());
        mesto.postavi(1, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 13, new Tretja.Stanovanjska(3));
        mesto.postavi(13, 23, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(19));
        mesto.postavi(21, 3, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 28, new Tretja.Stanovanjska(91));
        mesto.postavi(9, 28, new Tretja.Stanovanjska(84));
        mesto.postavi(24, 22, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 24, new Tretja.Poslovna());
        mesto.postavi(2, 24, new Tretja.Poslovna());
        mesto.postavi(25, 28, new Tretja.Stanovanjska(73));
        mesto.postavi(18, 0, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 29, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Stanovanjska(5));
        mesto.postavi(25, 18, new Tretja.Stanovanjska(89));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 5, new Tretja.Stanovanjska(93));
        mesto.postavi(5, 21, new Tretja.Stanovanjska(75));
        mesto.postavi(16, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 0, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(26, 0, new Tretja.Poslovna());
        mesto.postavi(27, 22, new Tretja.Stanovanjska(37));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 17, new Tretja.Poslovna());
        mesto.postavi(15, 25, new Tretja.Stanovanjska(87));
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(22, 16, new Tretja.Poslovna());
        mesto.postavi(11, 24, new Tretja.Stanovanjska(36));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 5, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 27, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Stanovanjska(17));
        mesto.postavi(18, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 10, new Tretja.Stanovanjska(73));
        mesto.postavi(12, 26, new Tretja.Poslovna());
        mesto.postavi(27, 12, new Tretja.Stanovanjska(14));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 19, new Tretja.Poslovna());
        mesto.postavi(21, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(6, 25, new Tretja.Stanovanjska(45));
        mesto.postavi(26, 2, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 24, new Tretja.Poslovna());
        mesto.postavi(1, 15, new Tretja.Stanovanjska(50));
        mesto.postavi(23, 8, new Tretja.Stanovanjska(78));
        mesto.postavi(25, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 7, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 10, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 16, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 19, new Tretja.Stanovanjska(72));
        mesto.postavi(16, 1, new Tretja.Stanovanjska(99));
        mesto.postavi(5, 7, new Tretja.Stanovanjska(99));
        mesto.postavi(21, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(97));
        mesto.postavi(5, 27, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 18, new Tretja.Stanovanjska(98));
        mesto.postavi(4, 22, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 19, new Tretja.Stanovanjska(86));
        mesto.postavi(16, 17, new Tretja.Stanovanjska(69));
        mesto.postavi(27, 18, new Tretja.Stanovanjska(13));
        mesto.postavi(17, 17, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 24, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 7, new Tretja.Stanovanjska(58));
        mesto.postavi(26, 27, new Tretja.Poslovna());
        mesto.postavi(8, 13, new Tretja.Poslovna());
        mesto.postavi(15, 7, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(57));
        mesto.postavi(0, 27, new Tretja.Stanovanjska(95));
        mesto.postavi(27, 10, new Tretja.Stanovanjska(39));
        mesto.postavi(20, 5, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(1, 2, new Tretja.Stanovanjska(41));
        mesto.postavi(5, 7, new Tretja.Stanovanjska(26));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 0, new Tretja.Stanovanjska(16));
        mesto.postavi(24, 6, new Tretja.Stanovanjska(54));
        mesto.postavi(27, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 29, new Tretja.Stanovanjska(94));
        mesto.postavi(25, 1, new Tretja.Stanovanjska(47));
        mesto.postavi(4, 13, new Tretja.Stanovanjska(97));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(61));
        mesto.postavi(14, 3, new Tretja.Poslovna());
        mesto.postavi(17, 16, new Tretja.Stanovanjska(63));
        mesto.postavi(4, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 3, new Tretja.Stanovanjska(55));
        mesto.postavi(16, 16, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Poslovna());
        mesto.postavi(15, 16, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 29, new Tretja.Stanovanjska(35));
        mesto.postavi(0, 6, new Tretja.Poslovna());
        mesto.postavi(16, 16, new Tretja.Poslovna());
        mesto.postavi(20, 28, new Tretja.Poslovna());
        mesto.postavi(16, 11, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Poslovna());
        mesto.postavi(19, 1, new Tretja.Poslovna());
        mesto.postavi(25, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 10, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(96));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 24, new Tretja.Stanovanjska(12));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(87));
        mesto.postavi(22, 18, new Tretja.Stanovanjska(50));
        mesto.postavi(1, 29, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(63));
        mesto.postavi(9, 16, new Tretja.Stanovanjska(13));
        mesto.postavi(28, 4, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 7, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 21, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 11, new Tretja.Stanovanjska(42));
        mesto.postavi(10, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 18, new Tretja.Stanovanjska(99));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(60));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(34));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(91));
        mesto.postavi(3, 27, new Tretja.Stanovanjska(16));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 27, new Tretja.Stanovanjska(61));
        mesto.postavi(20, 19, new Tretja.Stanovanjska(69));
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(20, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 29, new Tretja.Stanovanjska(68));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 17, new Tretja.Stanovanjska(54));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(24, 24, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Stanovanjska(15));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 19, new Tretja.Stanovanjska(53));
        mesto.postavi(14, 28, new Tretja.Stanovanjska(51));
        mesto.postavi(0, 11, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 21, new Tretja.Stanovanjska(2));
        mesto.postavi(11, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 18, new Tretja.Stanovanjska(29));
        mesto.postavi(5, 27, new Tretja.Poslovna());
        mesto.postavi(14, 28, new Tretja.Poslovna());
        mesto.postavi(13, 10, new Tretja.Poslovna());
        mesto.postavi(20, 12, new Tretja.Poslovna());
        mesto.postavi(14, 19, new Tretja.Stanovanjska(35));
        mesto.postavi(12, 20, new Tretja.Stanovanjska(22));
        mesto.postavi(24, 15, new Tretja.Poslovna());
        mesto.postavi(11, 26, new Tretja.Stanovanjska(8));
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(27, 6, new Tretja.Stanovanjska(28));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        mesto.postavi(22, 11, new Tretja.Stanovanjska(42));
        mesto.postavi(25, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(41));
        mesto.postavi(26, 6, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(69));
        mesto.postavi(17, 16, new Tretja.Stanovanjska(17));
        mesto.postavi(16, 27, new Tretja.Stanovanjska(69));
        mesto.postavi(29, 28, new Tretja.Stanovanjska(33));
        mesto.postavi(9, 7, new Tretja.Stanovanjska(32));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 22, new Tretja.Poslovna());
        mesto.postavi(11, 24, new Tretja.Poslovna());
        mesto.postavi(17, 22, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        mesto.postavi(28, 17, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 25, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 18, new Tretja.Poslovna());
        mesto.postavi(14, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 25, new Tretja.Poslovna());
        mesto.postavi(23, 27, new Tretja.Stanovanjska(98));
        mesto.postavi(10, 28, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 7, new Tretja.Stanovanjska(65));
        mesto.postavi(12, 10, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(57));
        mesto.postavi(22, 19, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(5));
        mesto.postavi(19, 19, new Tretja.Poslovna());
        mesto.postavi(19, 3, new Tretja.Poslovna());
        mesto.postavi(14, 19, new Tretja.Stanovanjska(40));
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(24, 12, new Tretja.Poslovna());
        mesto.postavi(29, 13, new Tretja.Poslovna());
        mesto.postavi(26, 3, new Tretja.Poslovna());
        mesto.postavi(27, 21, new Tretja.Poslovna());
        mesto.postavi(20, 0, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        mesto.postavi(19, 24, new Tretja.Stanovanjska(81));
        mesto.postavi(11, 1, new Tretja.Stanovanjska(7));
        mesto.postavi(5, 26, new Tretja.Poslovna());
        mesto.postavi(23, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 25, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 5, new Tretja.Poslovna());
        mesto.postavi(10, 24, new Tretja.Poslovna());
        mesto.postavi(19, 4, new Tretja.Stanovanjska(61));
        mesto.postavi(20, 18, new Tretja.Poslovna());
        mesto.postavi(1, 21, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 27, new Tretja.Stanovanjska(48));
        mesto.postavi(4, 17, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 24, new Tretja.Stanovanjska(47));
        mesto.postavi(26, 22, new Tretja.Poslovna());
        mesto.postavi(23, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 14, new Tretja.Stanovanjska(27));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 18, new Tretja.Stanovanjska(98));
        mesto.postavi(10, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 6, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 23, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 20, new Tretja.Stanovanjska(27));
        mesto.postavi(24, 25, new Tretja.Poslovna());
        mesto.postavi(9, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 28, new Tretja.Poslovna());
        mesto.postavi(23, 17, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(44));
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(19));
        mesto.postavi(13, 6, new Tretja.Stanovanjska(17));
        mesto.postavi(24, 1, new Tretja.Stanovanjska(23));
        mesto.postavi(27, 27, new Tretja.Poslovna());
        mesto.postavi(26, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 18, new Tretja.Stanovanjska(9));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 11, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(91));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(13, 24, new Tretja.Poslovna());
        mesto.postavi(14, 29, new Tretja.Stanovanjska(74));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(20, 27, new Tretja.Poslovna());
        mesto.postavi(8, 27, new Tretja.Poslovna());
        mesto.postavi(27, 6, new Tretja.Poslovna());
        mesto.postavi(1, 23, new Tretja.Stanovanjska(22));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(88));
        mesto.postavi(1, 18, new Tretja.Stanovanjska(69));
        mesto.postavi(21, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 27, new Tretja.Stanovanjska(90));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 7, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(44));
        mesto.postavi(19, 15, new Tretja.Poslovna());
        mesto.postavi(5, 25, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 18, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 15, new Tretja.Stanovanjska(1));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(4, 23, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(24));
        mesto.postavi(14, 0, new Tretja.Poslovna());
        mesto.postavi(24, 14, new Tretja.Poslovna());
        mesto.postavi(12, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 4, new Tretja.Stanovanjska(54));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 19, new Tretja.Stanovanjska(98));
        mesto.postavi(21, 3, new Tretja.Stanovanjska(28));
        mesto.postavi(3, 5, new Tretja.Stanovanjska(54));
        mesto.postavi(19, 23, new Tretja.Stanovanjska(55));
        mesto.postavi(24, 7, new Tretja.Stanovanjska(14));
        mesto.postavi(25, 24, new Tretja.Poslovna());
        mesto.postavi(3, 29, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 23, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Stanovanjska(61));
        mesto.postavi(14, 12, new Tretja.Stanovanjska(25));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 29, new Tretja.Stanovanjska(2));
        mesto.postavi(24, 21, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(80));
        mesto.postavi(24, 12, new Tretja.Poslovna());
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(26, 14, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(4));
        mesto.postavi(28, 17, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 15, new Tretja.Stanovanjska(18));
        mesto.postavi(21, 11, new Tretja.Poslovna());
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(6, 16, new Tretja.Stanovanjska(74));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 17, new Tretja.Stanovanjska(19));
        mesto.postavi(21, 16, new Tretja.Poslovna());
        mesto.postavi(15, 17, new Tretja.Stanovanjska(15));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Stanovanjska(70));
        mesto.postavi(12, 23, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 23, new Tretja.Poslovna());
        mesto.postavi(29, 1, new Tretja.Poslovna());
        mesto.postavi(19, 18, new Tretja.Stanovanjska(15));
        mesto.postavi(15, 4, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(26, 17, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Stanovanjska(10));
        mesto.postavi(14, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 12, new Tretja.Poslovna());
        mesto.postavi(22, 2, new Tretja.Stanovanjska(30));
        mesto.postavi(24, 28, new Tretja.Stanovanjska(29));
        mesto.postavi(9, 8, new Tretja.Poslovna());
        mesto.postavi(29, 24, new Tretja.Poslovna());
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(28, 21, new Tretja.Poslovna());
        mesto.postavi(24, 19, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 24, new Tretja.Stanovanjska(94));
        mesto.postavi(10, 22, new Tretja.Poslovna());
        mesto.postavi(15, 15, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 26, new Tretja.Poslovna());
        mesto.postavi(10, 10, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 3, new Tretja.Poslovna());
        mesto.postavi(10, 23, new Tretja.Poslovna());
        mesto.postavi(20, 27, new Tretja.Stanovanjska(86));
        mesto.postavi(16, 1, new Tretja.Stanovanjska(48));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 28, new Tretja.Poslovna());
        mesto.postavi(29, 26, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 16, new Tretja.Stanovanjska(2));
        mesto.postavi(7, 13, new Tretja.Poslovna());
        mesto.postavi(20, 28, new Tretja.Stanovanjska(55));
        mesto.postavi(20, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 27, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(24));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(44));
        mesto.postavi(23, 23, new Tretja.Stanovanjska(71));
        mesto.postavi(3, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 0, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Stanovanjska(9));
        mesto.postavi(5, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(27, 5, new Tretja.Poslovna());
        mesto.postavi(23, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 29, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 24, new Tretja.Stanovanjska(96));
        mesto.postavi(19, 1, new Tretja.Stanovanjska(90));
        mesto.postavi(19, 13, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 23, new Tretja.Poslovna());
        mesto.postavi(18, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 19, new Tretja.Stanovanjska(5));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 23, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 3, new Tretja.Poslovna());
        mesto.postavi(10, 4, new Tretja.Poslovna());
        mesto.postavi(18, 17, new Tretja.Stanovanjska(67));
        mesto.postavi(19, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 4, new Tretja.Stanovanjska(70));
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(16, 23, new Tretja.Stanovanjska(73));
        mesto.postavi(23, 3, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(40));
        mesto.postavi(2, 20, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 13, new Tretja.Stanovanjska(52));
        mesto.postavi(19, 1, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 16, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(15, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 0, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(28));
        mesto.postavi(15, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 29, new Tretja.Poslovna());
        mesto.postavi(9, 5, new Tretja.Stanovanjska(73));
        mesto.postavi(7, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 12, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 28, new Tretja.Stanovanjska(35));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 18, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 11, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 23, new Tretja.Stanovanjska(37));
        mesto.postavi(12, 11, new Tretja.Stanovanjska(23));
        mesto.postavi(26, 29, new Tretja.Stanovanjska(92));
        mesto.postavi(22, 17, new Tretja.Stanovanjska(51));
        mesto.postavi(3, 13, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 6, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 23, new Tretja.Stanovanjska(11));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 7, new Tretja.Stanovanjska(35));
        mesto.postavi(10, 24, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Stanovanjska(44));
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(3, 27, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 29, new Tretja.Stanovanjska(48));
        mesto.postavi(12, 23, new Tretja.Poslovna());
        mesto.postavi(8, 6, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Stanovanjska(31));
        mesto.postavi(6, 18, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 20, new Tretja.Stanovanjska(3));
        mesto.postavi(19, 23, new Tretja.Stanovanjska(3));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 11, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 24, new Tretja.Stanovanjska(78));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(91));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 26, new Tretja.Stanovanjska(38));
        mesto.postavi(10, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 15, new Tretja.Poslovna());
        mesto.postavi(25, 11, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 19, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(20, 14, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 6, new Tretja.Stanovanjska(49));
        mesto.postavi(18, 25, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 7, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 29, new Tretja.Poslovna());
        mesto.postavi(2, 21, new Tretja.Stanovanjska(99));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 18, new Tretja.Stanovanjska(43));
        mesto.postavi(0, 14, new Tretja.Stanovanjska(38));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Stanovanjska(57));
        mesto.postavi(17, 1, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 22, new Tretja.Stanovanjska(100));
        mesto.postavi(16, 1, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(12, 5, new Tretja.Poslovna());
        mesto.postavi(24, 25, new Tretja.Poslovna());
        mesto.postavi(28, 0, new Tretja.Poslovna());
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 1, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 20, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 28, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 13, new Tretja.Stanovanjska(79));
        mesto.postavi(4, 1, new Tretja.Stanovanjska(47));
        mesto.postavi(1, 3, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Stanovanjska(80));
        mesto.postavi(14, 12, new Tretja.Poslovna());
        mesto.postavi(29, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 21, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 16, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 19, new Tretja.Stanovanjska(73));
        mesto.postavi(26, 3, new Tretja.Stanovanjska(99));
        mesto.postavi(26, 6, new Tretja.Poslovna());
        mesto.postavi(25, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 2, new Tretja.Poslovna());
        mesto.postavi(9, 26, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 27, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 6, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 21, new Tretja.Stanovanjska(30));
        mesto.postavi(25, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(18, 19, new Tretja.Stanovanjska(65));
        mesto.postavi(3, 27, new Tretja.Stanovanjska(9));
        mesto.postavi(17, 22, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Poslovna());
        mesto.postavi(12, 13, new Tretja.Poslovna());
        mesto.postavi(8, 13, new Tretja.Stanovanjska(74));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 1, new Tretja.Poslovna());
        mesto.postavi(17, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 18, new Tretja.Stanovanjska(65));
        mesto.postavi(29, 28, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 14, new Tretja.Stanovanjska(21));
        mesto.postavi(21, 18, new Tretja.Stanovanjska(8));
        mesto.postavi(23, 19, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 24, new Tretja.Poslovna());
        mesto.postavi(22, 28, new Tretja.Poslovna());
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(26, 8, new Tretja.Stanovanjska(81));
        mesto.postavi(27, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 18, new Tretja.Stanovanjska(12));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 21, new Tretja.Stanovanjska(5));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(72));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(6, 12, new Tretja.Stanovanjska(45));
        mesto.postavi(12, 20, new Tretja.Stanovanjska(70));
        mesto.postavi(7, 10, new Tretja.Poslovna());
        mesto.postavi(3, 6, new Tretja.Stanovanjska(12));
        mesto.postavi(29, 2, new Tretja.Stanovanjska(50));
        mesto.postavi(6, 25, new Tretja.Stanovanjska(28));
        mesto.postavi(7, 27, new Tretja.Poslovna());
        mesto.postavi(24, 22, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Stanovanjska(44));
        mesto.postavi(18, 10, new Tretja.Poslovna());
        mesto.postavi(26, 0, new Tretja.Poslovna());
        mesto.postavi(21, 14, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Stanovanjska(20));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 6, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(27, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 4, new Tretja.Stanovanjska(31));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(7));
        mesto.postavi(25, 25, new Tretja.Poslovna());
        mesto.postavi(23, 17, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(76));
        mesto.postavi(23, 8, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(82));
        mesto.postavi(12, 26, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 10, new Tretja.Stanovanjska(15));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Stanovanjska(29));
        mesto.postavi(6, 22, new Tretja.Poslovna());
        mesto.postavi(9, 11, new Tretja.Stanovanjska(25));
        mesto.postavi(28, 4, new Tretja.Stanovanjska(70));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(69));
        mesto.postavi(9, 16, new Tretja.Stanovanjska(63));
        mesto.postavi(1, 15, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 7, new Tretja.Stanovanjska(33));
        mesto.postavi(13, 25, new Tretja.Stanovanjska(53));
        mesto.postavi(9, 12, new Tretja.Stanovanjska(14));
        mesto.postavi(7, 0, new Tretja.Poslovna());
        mesto.postavi(25, 0, new Tretja.Poslovna());
        mesto.postavi(23, 11, new Tretja.Stanovanjska(85));
        mesto.postavi(23, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 14, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 23, new Tretja.Stanovanjska(72));
        mesto.postavi(3, 21, new Tretja.Stanovanjska(31));
        mesto.postavi(7, 20, new Tretja.Poslovna());
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Stanovanjska(31));
        mesto.postavi(17, 16, new Tretja.Stanovanjska(7));
        mesto.postavi(13, 27, new Tretja.Poslovna());
        mesto.postavi(9, 27, new Tretja.Poslovna());
        mesto.postavi(25, 0, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 20, new Tretja.Stanovanjska(39));
        mesto.postavi(23, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 19, new Tretja.Stanovanjska(36));
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(28, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 28, new Tretja.Stanovanjska(99));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 16, new Tretja.Stanovanjska(92));
        mesto.postavi(21, 9, new Tretja.Stanovanjska(85));
        mesto.postavi(6, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 9, new Tretja.Poslovna());
        mesto.postavi(21, 11, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(27, 28, new Tretja.Stanovanjska(13));
        mesto.postavi(25, 27, new Tretja.Stanovanjska(86));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(2, 20, new Tretja.Poslovna());
        mesto.postavi(29, 7, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 29, new Tretja.Stanovanjska(32));
        mesto.postavi(22, 18, new Tretja.Stanovanjska(33));
        mesto.postavi(21, 3, new Tretja.Stanovanjska(47));
        mesto.postavi(21, 25, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 18, new Tretja.Stanovanjska(14));
        mesto.postavi(18, 9, new Tretja.Stanovanjska(55));
        mesto.postavi(9, 18, new Tretja.Poslovna());
        mesto.postavi(28, 6, new Tretja.Stanovanjska(55));
        mesto.postavi(2, 24, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 26, new Tretja.Stanovanjska(2));
        mesto.postavi(16, 27, new Tretja.Poslovna());
        mesto.postavi(24, 28, new Tretja.Poslovna());
        mesto.postavi(29, 1, new Tretja.Stanovanjska(9));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 29, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 28, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 3, new Tretja.Stanovanjska(13));
        mesto.postavi(4, 29, new Tretja.Poslovna());
        mesto.postavi(25, 23, new Tretja.Stanovanjska(42));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 27, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Poslovna());
        mesto.postavi(1, 2, new Tretja.Stanovanjska(26));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(5));
        mesto.postavi(28, 25, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 22, new Tretja.Stanovanjska(80));
        mesto.postavi(24, 27, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 0, new Tretja.Poslovna());
        mesto.postavi(25, 29, new Tretja.Stanovanjska(62));
        mesto.postavi(23, 26, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 19, new Tretja.Poslovna());
        mesto.postavi(1, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 24, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 5, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 29, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Stanovanjska(30));
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(0, 15, new Tretja.Stanovanjska(80));
        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(61));
        mesto.postavi(26, 12, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 2, new Tretja.Poslovna());
        mesto.postavi(7, 25, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(8));
        mesto.postavi(5, 23, new Tretja.Stanovanjska(37));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 17, new Tretja.Stanovanjska(22));
        mesto.postavi(24, 12, new Tretja.Stanovanjska(60));
        mesto.postavi(28, 0, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(54));
        mesto.postavi(13, 23, new Tretja.Stanovanjska(45));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(27, 2, new Tretja.Stanovanjska(21));
        mesto.postavi(8, 24, new Tretja.Poslovna());
        mesto.postavi(22, 9, new Tretja.Poslovna());
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(4, 22, new Tretja.Poslovna());
        mesto.postavi(19, 28, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 29, new Tretja.Stanovanjska(55));
        mesto.postavi(3, 18, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 19, new Tretja.Stanovanjska(99));
        mesto.postavi(3, 0, new Tretja.Stanovanjska(10));
        mesto.postavi(26, 16, new Tretja.Stanovanjska(57));
        mesto.postavi(21, 11, new Tretja.Stanovanjska(56));
        mesto.postavi(0, 6, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 22, new Tretja.Stanovanjska(52));
        mesto.postavi(22, 16, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 4, new Tretja.Stanovanjska(23));
        mesto.postavi(4, 24, new Tretja.Stanovanjska(83));
        mesto.postavi(1, 23, new Tretja.Poslovna());
        mesto.postavi(29, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 0, new Tretja.Poslovna());
        mesto.postavi(27, 21, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 17, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 28, new Tretja.Poslovna());
        mesto.postavi(24, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 5, new Tretja.Stanovanjska(51));
        mesto.postavi(1, 1, new Tretja.Poslovna());
        mesto.postavi(29, 7, new Tretja.Stanovanjska(72));
        mesto.postavi(22, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 19, new Tretja.Stanovanjska(35));
        mesto.postavi(15, 19, new Tretja.Poslovna());
        mesto.postavi(22, 2, new Tretja.Poslovna());
        mesto.postavi(6, 25, new Tretja.Poslovna());
        mesto.postavi(9, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 14, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 25, new Tretja.Poslovna());
        mesto.postavi(26, 13, new Tretja.Stanovanjska(32));
        mesto.postavi(3, 27, new Tretja.Stanovanjska(9));
        mesto.postavi(17, 22, new Tretja.Poslovna());
        mesto.postavi(7, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 18, new Tretja.Poslovna());
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(37));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 2, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(3, 15, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 11, new Tretja.Stanovanjska(39));
        mesto.postavi(3, 11, new Tretja.Poslovna());
        mesto.postavi(24, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 1, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 1, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 9, new Tretja.Stanovanjska(55));
        mesto.postavi(13, 15, new Tretja.Stanovanjska(57));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 18, new Tretja.Poslovna());
        mesto.postavi(29, 28, new Tretja.Poslovna());
        mesto.postavi(28, 0, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 24, new Tretja.Stanovanjska(35));
        mesto.postavi(23, 24, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Poslovna());
        mesto.postavi(22, 19, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 0, new Tretja.Poslovna());
        mesto.postavi(27, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 18, new Tretja.Poslovna());
        mesto.postavi(9, 22, new Tretja.Poslovna());
        mesto.postavi(29, 21, new Tretja.Stanovanjska(4));
        mesto.postavi(21, 12, new Tretja.Stanovanjska(48));
        mesto.postavi(3, 12, new Tretja.Stanovanjska(65));
        mesto.postavi(3, 5, new Tretja.Stanovanjska(56));
        mesto.postavi(29, 29, new Tretja.Poslovna());
        mesto.postavi(10, 28, new Tretja.Poslovna());
        mesto.postavi(26, 13, new Tretja.Stanovanjska(19));
        mesto.postavi(26, 16, new Tretja.Poslovna());
        mesto.postavi(25, 17, new Tretja.Stanovanjska(13));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 27, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 16, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 11, new Tretja.Stanovanjska(30));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(10));
        mesto.postavi(10, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 17, new Tretja.Stanovanjska(55));
        mesto.postavi(1, 19, new Tretja.Stanovanjska(47));
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(13, 23, new Tretja.Poslovna());
        mesto.postavi(20, 29, new Tretja.Poslovna());
        mesto.postavi(28, 0, new Tretja.Stanovanjska(4));
        mesto.postavi(24, 12, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(72));
        mesto.postavi(15, 7, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Poslovna());
        mesto.postavi(17, 29, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 10, new Tretja.Stanovanjska(29));
        mesto.postavi(15, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 11, new Tretja.Stanovanjska(64));
        mesto.postavi(15, 4, new Tretja.Poslovna());
        mesto.postavi(3, 27, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(21, 3, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 22, new Tretja.Stanovanjska(55));
        mesto.postavi(2, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 18, new Tretja.Stanovanjska(68));
        mesto.postavi(26, 3, new Tretja.Poslovna());
        mesto.postavi(2, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(5, 28, new Tretja.Poslovna());
        mesto.postavi(6, 10, new Tretja.Stanovanjska(100));
        mesto.postavi(29, 1, new Tretja.Poslovna());
        mesto.postavi(17, 4, new Tretja.Poslovna());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        mesto.postavi(16, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(14, 3, new Tretja.Stanovanjska(52));
        mesto.postavi(11, 1, new Tretja.Poslovna());
        mesto.postavi(20, 15, new Tretja.Stanovanjska(32));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 25, new Tretja.Stanovanjska(42));
        mesto.postavi(29, 8, new Tretja.Poslovna());
        mesto.postavi(22, 11, new Tretja.Poslovna());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(10));
        mesto.postavi(8, 6, new Tretja.Poslovna());
        mesto.postavi(16, 11, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(2, 11, new Tretja.Poslovna());
        mesto.postavi(26, 29, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Stanovanjska(15));
        mesto.postavi(27, 2, new Tretja.Stanovanjska(1));
        mesto.postavi(29, 28, new Tretja.Poslovna());
        mesto.postavi(22, 28, new Tretja.Poslovna());
        mesto.postavi(17, 16, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Poslovna());
        mesto.postavi(19, 24, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 27, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 25, new Tretja.Poslovna());
        mesto.postavi(27, 1, new Tretja.Stanovanjska(31));
        mesto.postavi(1, 23, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 20, new Tretja.Stanovanjska(15));
        mesto.postavi(22, 12, new Tretja.Poslovna());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(25, 10, new Tretja.Stanovanjska(25));
        mesto.postavi(15, 16, new Tretja.Stanovanjska(87));
        mesto.postavi(27, 19, new Tretja.Stanovanjska(7));
        mesto.postavi(19, 25, new Tretja.Poslovna());
        mesto.postavi(25, 25, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 25, new Tretja.Poslovna());
        mesto.postavi(8, 24, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 19, new Tretja.Poslovna());
        mesto.postavi(24, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 21, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 28, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 6, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Poslovna());
        mesto.postavi(28, 27, new Tretja.Stanovanjska(83));
        mesto.postavi(21, 24, new Tretja.Stanovanjska(16));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 23, new Tretja.Stanovanjska(31));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 15, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 9, new Tretja.Poslovna());
        mesto.postavi(15, 7, new Tretja.Poslovna());
        mesto.postavi(25, 24, new Tretja.Poslovna());
        mesto.postavi(29, 16, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 27, new Tretja.Stanovanjska(27));
        mesto.postavi(27, 6, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(5, 11, new Tretja.Stanovanjska(52));
        mesto.postavi(26, 26, new Tretja.Stanovanjska(53));
        mesto.postavi(26, 12, new Tretja.Stanovanjska(77));
        mesto.postavi(20, 25, new Tretja.Stanovanjska(47));
        mesto.postavi(24, 20, new Tretja.Poslovna());
        mesto.postavi(18, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 16, new Tretja.Stanovanjska(47));
        mesto.postavi(22, 9, new Tretja.Stanovanjska(80));
        mesto.postavi(21, 25, new Tretja.Stanovanjska(22));
        mesto.postavi(14, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 14, new Tretja.Stanovanjska(6));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 21, new Tretja.Stanovanjska(38));
        mesto.postavi(23, 4, new Tretja.Stanovanjska(10));
        mesto.postavi(1, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 8, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 23, new Tretja.Stanovanjska(53));
        mesto.postavi(9, 28, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Poslovna());
        mesto.postavi(9, 26, new Tretja.Stanovanjska(36));
        mesto.postavi(6, 26, new Tretja.Stanovanjska(52));
        mesto.postavi(19, 19, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(62));
        mesto.postavi(23, 17, new Tretja.Poslovna());
        mesto.postavi(27, 27, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 23, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Stanovanjska(43));
        mesto.postavi(28, 21, new Tretja.Poslovna());
        mesto.postavi(24, 10, new Tretja.Poslovna());
        mesto.postavi(24, 10, new Tretja.Stanovanjska(84));
        mesto.postavi(16, 27, new Tretja.Poslovna());
        mesto.postavi(15, 17, new Tretja.Stanovanjska(82));
        mesto.postavi(15, 10, new Tretja.Poslovna());
        mesto.postavi(21, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 7, new Tretja.Stanovanjska(99));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(11));
        mesto.postavi(20, 14, new Tretja.Stanovanjska(52));
        mesto.postavi(19, 2, new Tretja.Stanovanjska(87));
        mesto.postavi(13, 20, new Tretja.Poslovna());
        mesto.postavi(8, 28, new Tretja.Stanovanjska(72));
        mesto.postavi(25, 24, new Tretja.Stanovanjska(63));
        mesto.postavi(7, 23, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 14, new Tretja.Stanovanjska(73));
        mesto.postavi(24, 16, new Tretja.Stanovanjska(78));
        mesto.postavi(24, 21, new Tretja.Stanovanjska(66));
        mesto.postavi(18, 9, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Stanovanjska(6));
        mesto.postavi(19, 15, new Tretja.Stanovanjska(96));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(23));
        mesto.postavi(11, 20, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(27, 20, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 9, new Tretja.Stanovanjska(74));
        mesto.postavi(4, 23, new Tretja.Stanovanjska(13));
        mesto.postavi(27, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 26, new Tretja.Stanovanjska(28));
        mesto.postavi(15, 23, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 6, new Tretja.Poslovna());
        mesto.postavi(23, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 29, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 13, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(27));
        mesto.postavi(22, 4, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(25, 14, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 27, new Tretja.Stanovanjska(85));
        mesto.postavi(21, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 28, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Stanovanjska(28));
        mesto.postavi(21, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 25, new Tretja.Stanovanjska(6));
        mesto.postavi(19, 1, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(92));
        mesto.postavi(17, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 22, new Tretja.Stanovanjska(60));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 11, new Tretja.Stanovanjska(85));
        mesto.postavi(17, 29, new Tretja.Stanovanjska(64));
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Stanovanjska(57));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(53));
        mesto.postavi(11, 15, new Tretja.Poslovna());
        mesto.postavi(3, 25, new Tretja.Poslovna());
        mesto.postavi(29, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 21, new Tretja.Stanovanjska(33));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(57));
        mesto.postavi(1, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 25, new Tretja.Poslovna());
        mesto.postavi(28, 17, new Tretja.Stanovanjska(39));
        mesto.postavi(14, 20, new Tretja.Poslovna());
        mesto.postavi(22, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(18, 14, new Tretja.Poslovna());
        mesto.postavi(23, 29, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(9, 16, new Tretja.Stanovanjska(1));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 8, new Tretja.Stanovanjska(74));
        mesto.postavi(25, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 25, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 10, new Tretja.Stanovanjska(66));
        mesto.postavi(4, 15, new Tretja.Stanovanjska(49));
        mesto.postavi(25, 23, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 7, new Tretja.Stanovanjska(11));
        mesto.postavi(27, 9, new Tretja.Stanovanjska(74));
        mesto.postavi(6, 23, new Tretja.Stanovanjska(84));
        mesto.postavi(16, 14, new Tretja.Stanovanjska(47));
        mesto.postavi(16, 9, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(21));
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(23, 24, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Stanovanjska(29));
        mesto.postavi(13, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
