
import java.util.*;

public class Test12 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(12, 28);

        mesto.postavi(1, 20, new Tretja.Stanovanjska(75));
        mesto.postavi(11, 16, new Tretja.Poslovna());
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(7, 20, new Tretja.Stanovanjska(7));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(6, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 25, new Tretja.Stanovanjska(18));
        mesto.postavi(7, 12, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(98));
        mesto.postavi(0, 21, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 13, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 5, new Tretja.Stanovanjska(91));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(89));
        mesto.postavi(5, 16, new Tretja.Stanovanjska(53));
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(36));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(98));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(7, 23, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 19, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(10, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 0, new Tretja.Stanovanjska(73));
        mesto.postavi(11, 6, new Tretja.Stanovanjska(2));
        mesto.postavi(5, 19, new Tretja.Stanovanjska(74));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(5, 1, new Tretja.Stanovanjska(94));
        mesto.postavi(1, 26, new Tretja.Stanovanjska(87));
        mesto.postavi(6, 26, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 14, new Tretja.Stanovanjska(73));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 5, new Tretja.Poslovna());
        mesto.postavi(9, 16, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 18, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 19, new Tretja.Poslovna());
        mesto.postavi(9, 6, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(66));
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Poslovna());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(30));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(71));
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(92));
        mesto.postavi(1, 9, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(9, 0, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 17, new Tretja.Poslovna());
        mesto.postavi(10, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(3, 26, new Tretja.Stanovanjska(43));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Stanovanjska(88));
        mesto.postavi(8, 20, new Tretja.Stanovanjska(97));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 8, new Tretja.Poslovna());
        mesto.postavi(3, 26, new Tretja.Stanovanjska(88));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Poslovna());
        mesto.postavi(8, 19, new Tretja.Poslovna());
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(10, 15, new Tretja.Stanovanjska(47));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 2, new Tretja.Stanovanjska(24));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(10, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 8, new Tretja.Stanovanjska(86));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 22, new Tretja.Stanovanjska(2));
        mesto.postavi(2, 17, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 15, new Tretja.Stanovanjska(79));
        mesto.postavi(3, 25, new Tretja.Stanovanjska(48));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        mesto.postavi(4, 19, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 23, new Tretja.Stanovanjska(73));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 3, new Tretja.Poslovna());
        mesto.postavi(7, 14, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 26, new Tretja.Poslovna());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(27));
        mesto.postavi(8, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Stanovanjska(64));
        mesto.postavi(4, 23, new Tretja.Stanovanjska(46));
        mesto.postavi(0, 21, new Tretja.Stanovanjska(23));
        mesto.postavi(7, 1, new Tretja.Stanovanjska(93));
        mesto.postavi(2, 25, new Tretja.Poslovna());
        mesto.postavi(10, 25, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(79));
        mesto.postavi(3, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 27, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 17, new Tretja.Stanovanjska(53));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 14, new Tretja.Stanovanjska(93));
        mesto.postavi(9, 14, new Tretja.Stanovanjska(53));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(19));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(83));
        mesto.postavi(1, 27, new Tretja.Poslovna());
        mesto.postavi(4, 20, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 19, new Tretja.Stanovanjska(86));
        mesto.postavi(6, 14, new Tretja.Poslovna());
        mesto.postavi(5, 17, new Tretja.Stanovanjska(39));
        mesto.postavi(8, 27, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(5, 3, new Tretja.Stanovanjska(50));
        mesto.postavi(5, 17, new Tretja.Stanovanjska(77));
        mesto.postavi(8, 9, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 20, new Tretja.Stanovanjska(93));
        mesto.postavi(9, 2, new Tretja.Stanovanjska(98));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 13, new Tretja.Stanovanjska(18));
        mesto.postavi(8, 23, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 13, new Tretja.Poslovna());
        mesto.postavi(9, 22, new Tretja.Poslovna());
        mesto.postavi(6, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 25, new Tretja.Stanovanjska(5));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 17, new Tretja.Stanovanjska(51));
        mesto.postavi(8, 12, new Tretja.Stanovanjska(69));
        mesto.postavi(9, 2, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 24, new Tretja.Poslovna());
        mesto.postavi(7, 27, new Tretja.Stanovanjska(47));
        mesto.postavi(1, 21, new Tretja.Stanovanjska(18));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(54));
        mesto.postavi(7, 12, new Tretja.Poslovna());
        mesto.postavi(11, 23, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Poslovna());
        mesto.postavi(6, 24, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Poslovna());
        mesto.postavi(10, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(83));
        mesto.postavi(2, 5, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(5, 25, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 22, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(7, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 17, new Tretja.Stanovanjska(88));
        mesto.postavi(8, 24, new Tretja.Stanovanjska(55));
        mesto.postavi(6, 7, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 18, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 27, new Tretja.Poslovna());
        mesto.postavi(3, 18, new Tretja.Poslovna());
        mesto.postavi(2, 20, new Tretja.Stanovanjska(49));
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(45));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(9, 21, new Tretja.Stanovanjska(79));
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(4, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 23, new Tretja.Stanovanjska(88));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 17, new Tretja.Stanovanjska(90));
        mesto.postavi(8, 3, new Tretja.Stanovanjska(67));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(30));
        mesto.postavi(5, 15, new Tretja.Stanovanjska(13));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(38));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        mesto.postavi(8, 10, new Tretja.Stanovanjska(84));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 23, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Stanovanjska(84));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(9, 21, new Tretja.Poslovna());
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(7, 27, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(10));
        mesto.postavi(7, 7, new Tretja.Stanovanjska(13));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 22, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(17));
        mesto.postavi(6, 16, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 8, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(90));
        mesto.postavi(3, 14, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 23, new Tretja.Poslovna());
        mesto.postavi(3, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(34));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 12, new Tretja.Stanovanjska(34));
        mesto.postavi(5, 13, new Tretja.Poslovna());
        mesto.postavi(9, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 21, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 18, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 0, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 23, new Tretja.Stanovanjska(76));
        mesto.postavi(5, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 8, new Tretja.Stanovanjska(79));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(77));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 13, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 26, new Tretja.Stanovanjska(95));
        mesto.postavi(4, 23, new Tretja.Poslovna());
        mesto.postavi(6, 4, new Tretja.Stanovanjska(67));
        mesto.postavi(5, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Stanovanjska(12));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 9, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 26, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 6, new Tretja.Stanovanjska(100));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(5, 10, new Tretja.Poslovna());
        mesto.postavi(8, 6, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(10, 24, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(8, 23, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 12, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(21));
        mesto.postavi(3, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(0, 22, new Tretja.Poslovna());
        mesto.postavi(1, 7, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 24, new Tretja.Stanovanjska(23));
        mesto.postavi(9, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(60));
        mesto.postavi(8, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 19, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(58));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(71));
        mesto.postavi(9, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 2, new Tretja.Stanovanjska(42));
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 22, new Tretja.Stanovanjska(27));
        mesto.postavi(9, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 25, new Tretja.Poslovna());
        mesto.postavi(2, 21, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(59));
        mesto.postavi(7, 4, new Tretja.Stanovanjska(77));
        mesto.postavi(11, 20, new Tretja.Stanovanjska(91));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 25, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Stanovanjska(88));
        mesto.postavi(2, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 22, new Tretja.Poslovna());
        mesto.postavi(6, 8, new Tretja.Stanovanjska(20));
        mesto.postavi(4, 9, new Tretja.Poslovna());
        mesto.postavi(3, 19, new Tretja.Stanovanjska(56));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(26));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(94));
        mesto.postavi(9, 15, new Tretja.Stanovanjska(31));
        mesto.postavi(0, 27, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 14, new Tretja.Stanovanjska(85));
        mesto.postavi(8, 13, new Tretja.Stanovanjska(95));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(11, 16, new Tretja.Stanovanjska(6));
        mesto.postavi(7, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 27, new Tretja.Stanovanjska(69));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(23));
        mesto.postavi(5, 4, new Tretja.Stanovanjska(32));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(90));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Poslovna());
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(5, 0, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 18, new Tretja.Poslovna());
        mesto.postavi(0, 1, new Tretja.Stanovanjska(4));
        mesto.postavi(0, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Poslovna());
        mesto.postavi(8, 26, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 15, new Tretja.Stanovanjska(43));
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(5, 16, new Tretja.Stanovanjska(20));
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(2, 16, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Poslovna());
        mesto.postavi(1, 12, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Stanovanjska(61));
        mesto.postavi(8, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(9, 11, new Tretja.Stanovanjska(73));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 10, new Tretja.Stanovanjska(14));
        mesto.postavi(2, 9, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(4));
        mesto.postavi(11, 16, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(46));
        mesto.postavi(5, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(5, 27, new Tretja.Poslovna());
        mesto.postavi(4, 25, new Tretja.Poslovna());
        mesto.postavi(11, 23, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 17, new Tretja.Stanovanjska(32));
        mesto.postavi(2, 23, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 4, new Tretja.Stanovanjska(97));
        mesto.postavi(8, 2, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 1, new Tretja.Stanovanjska(26));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Poslovna());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 4, new Tretja.Stanovanjska(46));
        mesto.postavi(5, 3, new Tretja.Stanovanjska(41));
        mesto.postavi(7, 3, new Tretja.Stanovanjska(45));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(46));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(92));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(7, 10, new Tretja.Poslovna());
        mesto.postavi(5, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 0, new Tretja.Stanovanjska(9));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(9, 21, new Tretja.Poslovna());
        mesto.postavi(7, 0, new Tretja.Stanovanjska(76));
        mesto.postavi(4, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 12, new Tretja.Stanovanjska(66));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(32));
        mesto.postavi(3, 27, new Tretja.Stanovanjska(45));
        mesto.postavi(8, 8, new Tretja.Poslovna());
        mesto.postavi(3, 20, new Tretja.Poslovna());
        mesto.postavi(7, 0, new Tretja.Poslovna());
        mesto.postavi(0, 12, new Tretja.Poslovna());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(81));
        mesto.postavi(5, 10, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 21, new Tretja.Stanovanjska(76));
        mesto.postavi(4, 10, new Tretja.Stanovanjska(66));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(45));
        mesto.postavi(4, 14, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 11, new Tretja.Poslovna());
        mesto.postavi(1, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 25, new Tretja.Stanovanjska(62));
        mesto.postavi(5, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(5, 4, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(6));
        mesto.postavi(2, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 5, new Tretja.Poslovna());
        mesto.postavi(5, 0, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(71));
        mesto.postavi(10, 27, new Tretja.Stanovanjska(19));
        mesto.postavi(9, 13, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 5, new Tretja.Poslovna());
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(6, 8, new Tretja.Poslovna());
        mesto.postavi(2, 27, new Tretja.Poslovna());
        mesto.postavi(5, 4, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 20, new Tretja.Stanovanjska(25));
        mesto.postavi(9, 5, new Tretja.Poslovna());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 9, new Tretja.Stanovanjska(7));
        mesto.postavi(7, 19, new Tretja.Poslovna());
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(2, 12, new Tretja.Stanovanjska(94));
        mesto.postavi(4, 18, new Tretja.Stanovanjska(50));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 22, new Tretja.Stanovanjska(16));
        mesto.postavi(6, 0, new Tretja.Stanovanjska(76));
        mesto.postavi(10, 18, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Stanovanjska(78));
        mesto.postavi(7, 15, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(57));
        mesto.postavi(7, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Stanovanjska(73));
        mesto.postavi(10, 24, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        mesto.postavi(5, 24, new Tretja.Stanovanjska(72));
        mesto.postavi(3, 17, new Tretja.Stanovanjska(25));
        mesto.postavi(7, 16, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Stanovanjska(43));
        mesto.postavi(4, 22, new Tretja.Poslovna());
        mesto.postavi(11, 13, new Tretja.Stanovanjska(61));
        mesto.postavi(4, 22, new Tretja.Stanovanjska(78));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        mesto.postavi(9, 24, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 23, new Tretja.Stanovanjska(69));
        mesto.postavi(11, 24, new Tretja.Stanovanjska(54));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 20, new Tretja.Stanovanjska(40));
        mesto.postavi(4, 18, new Tretja.Poslovna());
        mesto.postavi(1, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(1, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 26, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 20, new Tretja.Stanovanjska(1));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(41));
        mesto.postavi(1, 8, new Tretja.Poslovna());
        mesto.postavi(7, 11, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(21));
        mesto.postavi(11, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 17, new Tretja.Stanovanjska(17));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        mesto.postavi(2, 26, new Tretja.Stanovanjska(42));
        mesto.postavi(3, 2, new Tretja.Stanovanjska(20));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(75));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(11, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(92));
        mesto.postavi(0, 23, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 11, new Tretja.Stanovanjska(63));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(45));
        mesto.postavi(8, 26, new Tretja.Stanovanjska(77));
        mesto.postavi(5, 26, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Stanovanjska(61));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 12, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(59));
        mesto.postavi(11, 3, new Tretja.Stanovanjska(2));
        mesto.postavi(3, 6, new Tretja.Stanovanjska(54));
        mesto.postavi(3, 27, new Tretja.Stanovanjska(24));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 10, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
    }
}
