
import java.util.*;

public class Test08 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(29, 13);

        mesto.postavi(16, 2, new Tretja.Stanovanjska(54));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 10, new Tretja.Stanovanjska(14));
        mesto.postavi(24, 11, new Tretja.Poslovna());
        mesto.postavi(28, 12, new Tretja.Stanovanjska(88));
        mesto.postavi(2, 11, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(63));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Stanovanjska(39));
        mesto.postavi(5, 6, new Tretja.Stanovanjska(11));
        mesto.postavi(16, 4, new Tretja.Poslovna());
        mesto.postavi(19, 3, new Tretja.Stanovanjska(29));
        mesto.postavi(5, 7, new Tretja.Stanovanjska(37));
        mesto.postavi(9, 6, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 3, new Tretja.Stanovanjska(74));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(22, 3, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(21, 3, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(83));
        mesto.postavi(24, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 8, new Tretja.Stanovanjska(18));
        mesto.postavi(19, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 3, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Stanovanjska(73));
        mesto.postavi(5, 1, new Tretja.Stanovanjska(96));
        mesto.postavi(21, 1, new Tretja.Stanovanjska(5));
        mesto.postavi(28, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(8));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(64));
        mesto.postavi(13, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 11, new Tretja.Stanovanjska(19));
        mesto.postavi(5, 5, new Tretja.Stanovanjska(85));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        mesto.postavi(2, 8, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(22, 10, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 10, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Stanovanjska(46));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(13, 8, new Tretja.Stanovanjska(43));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 11, new Tretja.Stanovanjska(15));
        mesto.postavi(16, 5, new Tretja.Stanovanjska(78));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(66));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        mesto.postavi(28, 7, new Tretja.Poslovna());
        mesto.postavi(23, 0, new Tretja.Stanovanjska(19));
        mesto.postavi(9, 9, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(72));
        mesto.postavi(14, 4, new Tretja.Poslovna());
        mesto.postavi(15, 2, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 6, new Tretja.Poslovna());
        mesto.postavi(19, 8, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 8, new Tretja.Stanovanjska(80));
        mesto.postavi(6, 3, new Tretja.Stanovanjska(46));
        mesto.postavi(21, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 3, new Tretja.Stanovanjska(13));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 11, new Tretja.Poslovna());
        mesto.postavi(12, 10, new Tretja.Stanovanjska(100));
        mesto.postavi(8, 8, new Tretja.Poslovna());
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Stanovanjska(83));
        mesto.postavi(17, 11, new Tretja.Stanovanjska(56));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(26, 8, new Tretja.Stanovanjska(58));
        mesto.postavi(5, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(3));
        mesto.postavi(22, 12, new Tretja.Stanovanjska(38));
        mesto.postavi(22, 1, new Tretja.Stanovanjska(69));
        mesto.postavi(14, 10, new Tretja.Stanovanjska(3));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 5, new Tretja.Stanovanjska(41));
        mesto.postavi(6, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 10, new Tretja.Poslovna());
        mesto.postavi(15, 12, new Tretja.Poslovna());
        mesto.postavi(21, 10, new Tretja.Stanovanjska(88));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 1, new Tretja.Stanovanjska(37));
        mesto.postavi(21, 11, new Tretja.Stanovanjska(83));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(10));
        mesto.postavi(1, 6, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 4, new Tretja.Poslovna());
        mesto.postavi(21, 11, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 7, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 6, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 3, new Tretja.Stanovanjska(79));
        mesto.postavi(10, 0, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 3, new Tretja.Stanovanjska(20));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 8, new Tretja.Poslovna());
        mesto.postavi(5, 4, new Tretja.Stanovanjska(65));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(91));
        mesto.postavi(11, 11, new Tretja.Stanovanjska(37));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(21, 3, new Tretja.Stanovanjska(16));
        mesto.postavi(24, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(4, 2, new Tretja.Stanovanjska(74));
        mesto.postavi(5, 10, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 9, new Tretja.Stanovanjska(58));
        mesto.postavi(5, 5, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 1, new Tretja.Stanovanjska(70));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(16, 12, new Tretja.Stanovanjska(15));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Stanovanjska(67));
        mesto.postavi(1, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 8, new Tretja.Stanovanjska(92));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(26, 6, new Tretja.Stanovanjska(49));
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(21, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 0, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 9, new Tretja.Stanovanjska(24));
        mesto.postavi(19, 8, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        mesto.postavi(28, 10, new Tretja.Stanovanjska(37));
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(16, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 9, new Tretja.Poslovna());
        mesto.postavi(5, 10, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 4, new Tretja.Stanovanjska(13));
        mesto.postavi(2, 8, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 10, new Tretja.Poslovna());
        mesto.postavi(14, 7, new Tretja.Stanovanjska(27));
        mesto.postavi(9, 5, new Tretja.Stanovanjska(10));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        mesto.postavi(7, 0, new Tretja.Stanovanjska(49));
        mesto.postavi(14, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 1, new Tretja.Stanovanjska(89));
        mesto.postavi(13, 10, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 9, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(16, 11, new Tretja.Stanovanjska(89));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        mesto.postavi(25, 5, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 12, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 10, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Stanovanjska(32));
        mesto.postavi(21, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 7, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 6, new Tretja.Stanovanjska(77));
        mesto.postavi(28, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 12, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 10, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 8, new Tretja.Stanovanjska(91));
        mesto.postavi(22, 1, new Tretja.Stanovanjska(33));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(87));
        mesto.postavi(26, 5, new Tretja.Stanovanjska(58));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 6, new Tretja.Stanovanjska(70));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 5, new Tretja.Stanovanjska(59));
        mesto.postavi(0, 2, new Tretja.Stanovanjska(15));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(30));
        mesto.postavi(20, 9, new Tretja.Stanovanjska(17));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 9, new Tretja.Poslovna());
        mesto.postavi(18, 4, new Tretja.Poslovna());
        mesto.postavi(25, 4, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 10, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 0, new Tretja.Stanovanjska(75));
        mesto.postavi(11, 6, new Tretja.Poslovna());
        mesto.postavi(15, 10, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
    }
}
