
import java.util.*;

public class Test27 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(22, 10);

        mesto.postavi(2, 6, new Tretja.Stanovanjska(67));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(15, 2, new Tretja.Stanovanjska(63));
        mesto.postavi(14, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 2, new Tretja.Stanovanjska(96));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 0, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Stanovanjska(27));
        mesto.postavi(15, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Stanovanjska(6));
        mesto.postavi(12, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 9, new Tretja.Stanovanjska(61));
        mesto.postavi(10, 5, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 2, new Tretja.Poslovna());
        mesto.postavi(13, 3, new Tretja.Stanovanjska(28));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 1, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 9, new Tretja.Poslovna());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(85));
        mesto.postavi(5, 5, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        mesto.postavi(12, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 1, new Tretja.Stanovanjska(31));
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 0, new Tretja.Poslovna());
        mesto.postavi(4, 3, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(75));
        mesto.postavi(19, 0, new Tretja.Stanovanjska(13));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 6, new Tretja.Poslovna());
        mesto.postavi(1, 6, new Tretja.Stanovanjska(44));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(89));
        mesto.postavi(15, 6, new Tretja.Poslovna());
        mesto.postavi(16, 3, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Poslovna());
        mesto.postavi(17, 3, new Tretja.Stanovanjska(89));
        mesto.postavi(20, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(24));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 6, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Stanovanjska(6));
        mesto.postavi(17, 7, new Tretja.Stanovanjska(91));
        mesto.postavi(2, 1, new Tretja.Stanovanjska(59));
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(21, 8, new Tretja.Stanovanjska(2));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(6, 4, new Tretja.Stanovanjska(100));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 7, new Tretja.Poslovna());
        mesto.postavi(7, 1, new Tretja.Stanovanjska(60));
        mesto.postavi(18, 4, new Tretja.Poslovna());
        mesto.postavi(9, 5, new Tretja.Poslovna());
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 1, new Tretja.Stanovanjska(51));
        mesto.postavi(20, 0, new Tretja.Poslovna());
        mesto.postavi(20, 8, new Tretja.Stanovanjska(68));
        mesto.postavi(15, 4, new Tretja.Stanovanjska(90));
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(19, 4, new Tretja.Stanovanjska(17));
        mesto.postavi(21, 1, new Tretja.Poslovna());
        mesto.postavi(2, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 1, new Tretja.Stanovanjska(89));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(44));
        mesto.postavi(8, 7, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(0, 7, new Tretja.Stanovanjska(85));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(57));
        mesto.postavi(16, 2, new Tretja.Stanovanjska(84));
        mesto.postavi(4, 8, new Tretja.Stanovanjska(66));
        mesto.postavi(4, 9, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Stanovanjska(73));
        mesto.postavi(3, 4, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 6, new Tretja.Stanovanjska(81));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(18));
        mesto.postavi(21, 9, new Tretja.Poslovna());
        mesto.postavi(21, 3, new Tretja.Stanovanjska(11));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        mesto.postavi(11, 8, new Tretja.Stanovanjska(31));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(60));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 5, new Tretja.Stanovanjska(93));
        mesto.postavi(14, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(11));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        mesto.postavi(19, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 8, new Tretja.Poslovna());
        mesto.postavi(18, 9, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 5, new Tretja.Stanovanjska(2));
        mesto.postavi(9, 9, new Tretja.Stanovanjska(23));
        mesto.postavi(14, 3, new Tretja.Stanovanjska(76));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(81));
        mesto.postavi(15, 5, new Tretja.Stanovanjska(51));
        mesto.postavi(1, 2, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(9));
        mesto.postavi(5, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(33));
        mesto.postavi(7, 7, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(14, 2, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(36));
        mesto.postavi(18, 2, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 9, new Tretja.Stanovanjska(18));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(10, 4, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(44));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 2, new Tretja.Stanovanjska(48));
        mesto.postavi(19, 7, new Tretja.Stanovanjska(23));
        mesto.postavi(20, 4, new Tretja.Stanovanjska(52));
        mesto.postavi(7, 5, new Tretja.Poslovna());
        mesto.postavi(21, 4, new Tretja.Poslovna());
        mesto.postavi(20, 2, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
