
import java.util.*;

public class Test17 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(14, 24);

        mesto.postavi(11, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 13, new Tretja.Stanovanjska(96));
        mesto.postavi(10, 15, new Tretja.Poslovna());
        mesto.postavi(13, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 9, new Tretja.Stanovanjska(50));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(60));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 12, new Tretja.Stanovanjska(97));
        mesto.postavi(10, 16, new Tretja.Stanovanjska(6));
        mesto.postavi(2, 22, new Tretja.Poslovna());
        mesto.postavi(6, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 19, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 3, new Tretja.Poslovna());
        mesto.postavi(0, 19, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(1, 19, new Tretja.Poslovna());
        mesto.postavi(12, 5, new Tretja.Poslovna());
        mesto.postavi(2, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 5, new Tretja.Stanovanjska(96));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 19, new Tretja.Stanovanjska(97));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 1, new Tretja.Poslovna());
        mesto.postavi(13, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(8, 17, new Tretja.Stanovanjska(76));
        mesto.postavi(13, 19, new Tretja.Stanovanjska(43));
        mesto.postavi(13, 20, new Tretja.Stanovanjska(26));
        mesto.postavi(5, 4, new Tretja.Stanovanjska(51));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(31));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(12, 20, new Tretja.Poslovna());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 12, new Tretja.Stanovanjska(32));
        mesto.postavi(10, 9, new Tretja.Stanovanjska(50));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 21, new Tretja.Stanovanjska(82));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(19));
        mesto.postavi(8, 13, new Tretja.Stanovanjska(19));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 2, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(73));
        mesto.postavi(5, 3, new Tretja.Stanovanjska(98));
        mesto.postavi(4, 16, new Tretja.Poslovna());
        mesto.postavi(3, 22, new Tretja.Stanovanjska(34));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(4, 14, new Tretja.Stanovanjska(3));
        mesto.postavi(2, 11, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Stanovanjska(68));
        mesto.postavi(10, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 3, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Stanovanjska(79));
        mesto.postavi(8, 20, new Tretja.Stanovanjska(70));
        mesto.postavi(1, 1, new Tretja.Stanovanjska(74));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 20, new Tretja.Poslovna());
        mesto.postavi(5, 1, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(50));
        mesto.postavi(7, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 21, new Tretja.Poslovna());
        mesto.postavi(13, 14, new Tretja.Poslovna());
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(7, 20, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 23, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(12, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 14, new Tretja.Stanovanjska(34));
        mesto.postavi(3, 19, new Tretja.Stanovanjska(47));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(97));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Stanovanjska(87));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(0, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 0, new Tretja.Stanovanjska(72));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 7, new Tretja.Stanovanjska(37));
        mesto.postavi(13, 22, new Tretja.Stanovanjska(80));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 17, new Tretja.Stanovanjska(78));
        mesto.postavi(13, 2, new Tretja.Poslovna());
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Stanovanjska(16));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 15, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        mesto.postavi(1, 2, new Tretja.Stanovanjska(87));
        mesto.postavi(12, 1, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Stanovanjska(59));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 15, new Tretja.Stanovanjska(95));
        mesto.postavi(6, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 1, new Tretja.Stanovanjska(95));
        mesto.postavi(9, 6, new Tretja.Stanovanjska(77));
        mesto.postavi(8, 10, new Tretja.Stanovanjska(77));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 22, new Tretja.Stanovanjska(38));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 23, new Tretja.Stanovanjska(91));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(32));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 17, new Tretja.Stanovanjska(60));
        mesto.postavi(7, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 14, new Tretja.Stanovanjska(42));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 18, new Tretja.Stanovanjska(82));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 15, new Tretja.Stanovanjska(45));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 16, new Tretja.Stanovanjska(65));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(99));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(26));
        mesto.postavi(7, 4, new Tretja.Stanovanjska(97));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(79));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(30));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 21, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 5, new Tretja.Stanovanjska(57));
        mesto.postavi(6, 9, new Tretja.Stanovanjska(3));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(35));
        mesto.postavi(3, 11, new Tretja.Poslovna());
        mesto.postavi(5, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 13, new Tretja.Stanovanjska(98));
        mesto.postavi(11, 16, new Tretja.Stanovanjska(63));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
