
import java.util.*;

public class Test20 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(14, 25);

        mesto.postavi(12, 19, new Tretja.Stanovanjska(70));
        mesto.postavi(5, 9, new Tretja.Stanovanjska(34));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        mesto.postavi(7, 13, new Tretja.Stanovanjska(52));
        mesto.postavi(1, 18, new Tretja.Poslovna());
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(0, 12, new Tretja.Stanovanjska(5));
        mesto.postavi(3, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(44));
        mesto.postavi(3, 15, new Tretja.Stanovanjska(30));
        mesto.postavi(9, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 1, new Tretja.Stanovanjska(93));
        mesto.postavi(0, 5, new Tretja.Stanovanjska(58));
        mesto.postavi(12, 7, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 10, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Stanovanjska(5));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(84));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 20, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 8, new Tretja.Stanovanjska(97));
        mesto.postavi(3, 3, new Tretja.Stanovanjska(37));
        mesto.postavi(10, 5, new Tretja.Stanovanjska(32));
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(13, 8, new Tretja.Stanovanjska(28));
        mesto.postavi(8, 16, new Tretja.Poslovna());
        mesto.postavi(8, 21, new Tretja.Stanovanjska(67));
        mesto.postavi(0, 4, new Tretja.Stanovanjska(36));
        mesto.postavi(2, 14, new Tretja.Poslovna());
        mesto.postavi(1, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 21, new Tretja.Poslovna());
        mesto.postavi(10, 20, new Tretja.Stanovanjska(61));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(8, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 22, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Stanovanjska(27));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(0, 19, new Tretja.Poslovna());
        mesto.postavi(3, 5, new Tretja.Stanovanjska(64));
        mesto.postavi(8, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(30));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 3, new Tretja.Stanovanjska(23));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(48));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 1, new Tretja.Stanovanjska(100));
        mesto.postavi(7, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(5));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 21, new Tretja.Stanovanjska(70));
        mesto.postavi(7, 22, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Stanovanjska(86));
        mesto.postavi(8, 20, new Tretja.Poslovna());
        mesto.postavi(5, 16, new Tretja.Poslovna());
        mesto.postavi(13, 16, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 1, new Tretja.Stanovanjska(27));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(94));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 20, new Tretja.Stanovanjska(43));
        mesto.postavi(1, 13, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 23, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Stanovanjska(89));
        mesto.postavi(1, 12, new Tretja.Stanovanjska(37));
        mesto.postavi(10, 12, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 7, new Tretja.Poslovna());
        mesto.postavi(9, 22, new Tretja.Stanovanjska(43));
        mesto.postavi(5, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 16, new Tretja.Stanovanjska(41));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(32));
        mesto.postavi(5, 15, new Tretja.Stanovanjska(35));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 16, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Stanovanjska(11));
        mesto.postavi(13, 18, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 17, new Tretja.Stanovanjska(32));
        mesto.postavi(3, 2, new Tretja.Stanovanjska(74));
        mesto.postavi(12, 22, new Tretja.Stanovanjska(1));
        mesto.postavi(1, 1, new Tretja.Poslovna());
        mesto.postavi(9, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 5, new Tretja.Poslovna());
        mesto.postavi(8, 22, new Tretja.Stanovanjska(100));
        mesto.postavi(2, 20, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(33));
        mesto.postavi(3, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 10, new Tretja.Stanovanjska(46));
        mesto.postavi(3, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(33));
        mesto.postavi(5, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 22, new Tretja.Stanovanjska(96));
        mesto.postavi(11, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 24, new Tretja.Poslovna());
        mesto.postavi(9, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 10, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 20, new Tretja.Stanovanjska(79));
        mesto.postavi(11, 24, new Tretja.Stanovanjska(31));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(11, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 22, new Tretja.Stanovanjska(30));
        mesto.postavi(12, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 13, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Stanovanjska(63));
        mesto.postavi(11, 20, new Tretja.Stanovanjska(30));
        mesto.postavi(12, 23, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 17, new Tretja.Stanovanjska(50));
        mesto.postavi(7, 21, new Tretja.Stanovanjska(61));
        mesto.postavi(13, 17, new Tretja.Stanovanjska(74));
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Poslovna());
        mesto.postavi(12, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(9, 19, new Tretja.Stanovanjska(36));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 4, new Tretja.Poslovna());
        mesto.postavi(0, 16, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Stanovanjska(48));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 21, new Tretja.Stanovanjska(6));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 22, new Tretja.Stanovanjska(62));
        mesto.postavi(7, 21, new Tretja.Poslovna());
        mesto.postavi(11, 8, new Tretja.Stanovanjska(5));
        mesto.postavi(7, 12, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 15, new Tretja.Stanovanjska(59));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 15, new Tretja.Stanovanjska(81));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 14, new Tretja.Stanovanjska(76));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 13, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(7, 21, new Tretja.Stanovanjska(40));
        mesto.postavi(7, 22, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 21, new Tretja.Stanovanjska(38));
        mesto.postavi(3, 0, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 0, new Tretja.Poslovna());
        mesto.postavi(8, 17, new Tretja.Stanovanjska(69));
        mesto.postavi(3, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 22, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Poslovna());
        mesto.postavi(6, 12, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(73));
        mesto.postavi(5, 13, new Tretja.Poslovna());
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(1, 24, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 8, new Tretja.Stanovanjska(99));
        mesto.postavi(7, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 17, new Tretja.Stanovanjska(5));
        mesto.postavi(1, 11, new Tretja.Poslovna());
        mesto.postavi(11, 3, new Tretja.Stanovanjska(41));
        mesto.postavi(6, 19, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(8, 19, new Tretja.Stanovanjska(87));
        mesto.postavi(9, 18, new Tretja.Stanovanjska(100));
        mesto.postavi(2, 15, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 3, new Tretja.Stanovanjska(66));
        mesto.postavi(13, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 13, new Tretja.Stanovanjska(34));
        mesto.postavi(9, 0, new Tretja.Poslovna());
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Poslovna());
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 23, new Tretja.Poslovna());
        mesto.postavi(1, 17, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 19, new Tretja.Stanovanjska(10));
        mesto.postavi(1, 13, new Tretja.Stanovanjska(35));
        mesto.postavi(2, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 21, new Tretja.Stanovanjska(92));
        mesto.postavi(8, 8, new Tretja.Stanovanjska(62));
        mesto.postavi(8, 7, new Tretja.Stanovanjska(83));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 18, new Tretja.Stanovanjska(90));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(3, 22, new Tretja.Stanovanjska(30));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(15));
        mesto.postavi(8, 18, new Tretja.Stanovanjska(39));
        mesto.postavi(2, 12, new Tretja.Stanovanjska(13));
        mesto.postavi(9, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 23, new Tretja.Stanovanjska(88));
        mesto.postavi(3, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(4, 11, new Tretja.Stanovanjska(41));
        mesto.postavi(11, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 1, new Tretja.Stanovanjska(82));
        mesto.postavi(5, 24, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 1, new Tretja.Stanovanjska(96));
        mesto.postavi(7, 23, new Tretja.Poslovna());
        mesto.postavi(11, 19, new Tretja.Stanovanjska(33));
        mesto.postavi(8, 19, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 19, new Tretja.Stanovanjska(12));
        mesto.postavi(12, 21, new Tretja.Stanovanjska(72));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 2, new Tretja.Poslovna());
        mesto.postavi(0, 21, new Tretja.Poslovna());
        mesto.postavi(7, 19, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 24, new Tretja.Stanovanjska(61));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 5, new Tretja.Stanovanjska(61));
        mesto.postavi(5, 7, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 19, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(9));
        mesto.postavi(5, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 3, new Tretja.Poslovna());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(39));
        mesto.postavi(6, 5, new Tretja.Poslovna());
        mesto.postavi(12, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 22, new Tretja.Stanovanjska(37));
        mesto.postavi(4, 3, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 9, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(18));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 24, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(11, 4, new Tretja.Stanovanjska(67));
        mesto.postavi(8, 24, new Tretja.Stanovanjska(33));
        mesto.postavi(3, 23, new Tretja.Stanovanjska(83));
        mesto.postavi(13, 15, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 24, new Tretja.Stanovanjska(34));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(27));
        mesto.postavi(9, 7, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 20, new Tretja.Stanovanjska(98));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 1, new Tretja.Stanovanjska(12));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(37));
        mesto.postavi(7, 23, new Tretja.Poslovna());
        mesto.postavi(2, 16, new Tretja.Poslovna());
        mesto.postavi(1, 12, new Tretja.Stanovanjska(99));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(71));
        mesto.postavi(0, 24, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(91));
        mesto.postavi(7, 3, new Tretja.Stanovanjska(87));
        mesto.postavi(8, 7, new Tretja.Stanovanjska(3));
        mesto.postavi(6, 3, new Tretja.Stanovanjska(18));
        mesto.postavi(1, 22, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 24, new Tretja.Stanovanjska(46));
        mesto.postavi(12, 0, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(4, 1, new Tretja.Stanovanjska(16));
        mesto.postavi(10, 4, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 21, new Tretja.Stanovanjska(41));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(95));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 24, new Tretja.Poslovna());
        mesto.postavi(6, 16, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 21, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Stanovanjska(13));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(80));
        mesto.postavi(6, 23, new Tretja.Stanovanjska(63));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 3, new Tretja.Stanovanjska(44));
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Poslovna());
        mesto.postavi(1, 17, new Tretja.Stanovanjska(7));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(64));
        mesto.postavi(2, 19, new Tretja.Poslovna());
        mesto.postavi(10, 19, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 18, new Tretja.Stanovanjska(51));
        mesto.postavi(12, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 18, new Tretja.Stanovanjska(71));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(43));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 10, new Tretja.Poslovna());
        mesto.postavi(6, 24, new Tretja.Poslovna());
        mesto.postavi(5, 19, new Tretja.Stanovanjska(20));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 1, new Tretja.Stanovanjska(5));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 21, new Tretja.Stanovanjska(54));
        mesto.postavi(7, 9, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 23, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 9, new Tretja.Stanovanjska(99));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(19));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 23, new Tretja.Stanovanjska(82));
        mesto.postavi(3, 10, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 0, new Tretja.Stanovanjska(90));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Stanovanjska(18));
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Stanovanjska(37));
        mesto.postavi(13, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Stanovanjska(65));
        mesto.postavi(3, 4, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(92));
        mesto.postavi(12, 5, new Tretja.Poslovna());
        mesto.postavi(10, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 20, new Tretja.Stanovanjska(77));
        mesto.postavi(10, 23, new Tretja.Stanovanjska(100));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 23, new Tretja.Poslovna());
        mesto.postavi(12, 7, new Tretja.Stanovanjska(13));
        mesto.postavi(11, 2, new Tretja.Stanovanjska(85));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(3, 9, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(2, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
