
import java.util.*;

public class Test30 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(18, 27);

        mesto.postavi(10, 2, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(17, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(87));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(52));
        mesto.postavi(3, 11, new Tretja.Poslovna());
        mesto.postavi(11, 13, new Tretja.Stanovanjska(54));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Stanovanjska(51));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 26, new Tretja.Stanovanjska(7));
        mesto.postavi(14, 0, new Tretja.Stanovanjska(93));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(50));
        mesto.postavi(13, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 7, new Tretja.Stanovanjska(36));
        mesto.postavi(13, 1, new Tretja.Poslovna());
        mesto.postavi(9, 24, new Tretja.Stanovanjska(77));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 18, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(53));
        mesto.postavi(4, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 18, new Tretja.Stanovanjska(51));
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(17, 0, new Tretja.Stanovanjska(48));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(93));
        mesto.postavi(14, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 25, new Tretja.Stanovanjska(60));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 9, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(15, 23, new Tretja.Stanovanjska(37));
        mesto.postavi(1, 7, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(79));
        mesto.postavi(0, 7, new Tretja.Stanovanjska(20));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 22, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Stanovanjska(63));
        mesto.postavi(12, 18, new Tretja.Stanovanjska(84));
        mesto.postavi(10, 5, new Tretja.Stanovanjska(9));
        mesto.postavi(7, 7, new Tretja.Stanovanjska(49));
        mesto.postavi(7, 20, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 24, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(36));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(44));
        mesto.postavi(2, 19, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 3, new Tretja.Stanovanjska(47));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 22, new Tretja.Poslovna());
        mesto.postavi(10, 11, new Tretja.Stanovanjska(86));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(88));
        mesto.postavi(12, 10, new Tretja.Stanovanjska(14));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Stanovanjska(73));
        mesto.postavi(17, 13, new Tretja.Stanovanjska(1));
        mesto.postavi(1, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 9, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Stanovanjska(31));
        mesto.postavi(0, 23, new Tretja.Stanovanjska(18));
        mesto.postavi(16, 23, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 19, new Tretja.Poslovna());
        mesto.postavi(14, 11, new Tretja.Stanovanjska(16));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(8));
        mesto.postavi(16, 20, new Tretja.Poslovna());
        mesto.postavi(9, 24, new Tretja.Stanovanjska(39));
        mesto.postavi(10, 3, new Tretja.Poslovna());
        mesto.postavi(14, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 23, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 13, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 7, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 13, new Tretja.Stanovanjska(74));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(40));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 18, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(2));
        mesto.postavi(7, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 23, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Stanovanjska(40));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 7, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 20, new Tretja.Stanovanjska(62));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 7, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(2, 23, new Tretja.Poslovna());
        mesto.postavi(17, 10, new Tretja.Stanovanjska(82));
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(14, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 24, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 13, new Tretja.Stanovanjska(90));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(16, 22, new Tretja.Stanovanjska(22));
        mesto.postavi(1, 18, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(37));
        mesto.postavi(9, 22, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Stanovanjska(17));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(49));
        mesto.postavi(14, 2, new Tretja.Stanovanjska(84));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 4, new Tretja.Stanovanjska(66));
        mesto.postavi(16, 3, new Tretja.Stanovanjska(96));
        mesto.postavi(9, 13, new Tretja.Stanovanjska(92));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(65));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(93));
        mesto.postavi(17, 18, new Tretja.Stanovanjska(23));
        mesto.postavi(4, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 22, new Tretja.Poslovna());
        mesto.postavi(10, 17, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Stanovanjska(13));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(22));
        mesto.postavi(10, 8, new Tretja.Stanovanjska(46));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 23, new Tretja.Stanovanjska(16));
        mesto.postavi(15, 17, new Tretja.Stanovanjska(50));
        mesto.postavi(10, 1, new Tretja.Stanovanjska(83));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 25, new Tretja.Stanovanjska(69));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Stanovanjska(39));
        mesto.postavi(13, 1, new Tretja.Poslovna());
        mesto.postavi(5, 21, new Tretja.Stanovanjska(90));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(6));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(10, 19, new Tretja.Poslovna());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(8, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 24, new Tretja.Stanovanjska(9));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 15, new Tretja.Poslovna());
        mesto.postavi(3, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 21, new Tretja.Stanovanjska(65));
        mesto.postavi(5, 8, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 20, new Tretja.Stanovanjska(49));
        mesto.postavi(17, 3, new Tretja.Stanovanjska(66));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 10, new Tretja.Stanovanjska(92));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        mesto.postavi(0, 24, new Tretja.Stanovanjska(35));
        mesto.postavi(6, 20, new Tretja.Stanovanjska(94));
        mesto.postavi(2, 18, new Tretja.Stanovanjska(75));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(35));
        mesto.postavi(17, 12, new Tretja.Poslovna());
        mesto.postavi(12, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Poslovna());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 23, new Tretja.Stanovanjska(31));
        mesto.postavi(14, 16, new Tretja.Poslovna());
        mesto.postavi(15, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 12, new Tretja.Stanovanjska(45));
        mesto.postavi(2, 23, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 18, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 15, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 2, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 8, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 10, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Poslovna());
        mesto.postavi(10, 12, new Tretja.Stanovanjska(87));
        mesto.postavi(15, 9, new Tretja.Stanovanjska(36));
        mesto.postavi(13, 12, new Tretja.Stanovanjska(9));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
