
import java.util.*;

public class Test11 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(30, 17);

        mesto.postavi(25, 9, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 15, new Tretja.Poslovna());
        mesto.postavi(25, 7, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 9, new Tretja.Stanovanjska(67));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Stanovanjska(99));
        mesto.postavi(4, 4, new Tretja.Poslovna());
        mesto.postavi(10, 10, new Tretja.Stanovanjska(87));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(13, 14, new Tretja.Poslovna());
        mesto.postavi(14, 15, new Tretja.Stanovanjska(2));
        mesto.postavi(29, 13, new Tretja.Poslovna());
        mesto.postavi(29, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Stanovanjska(91));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 2, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Poslovna());
        mesto.postavi(11, 13, new Tretja.Stanovanjska(80));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(33));
        mesto.postavi(21, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 1, new Tretja.Poslovna());
        mesto.postavi(12, 14, new Tretja.Poslovna());
        mesto.postavi(26, 12, new Tretja.Stanovanjska(71));
        mesto.postavi(23, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 1, new Tretja.Stanovanjska(74));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 1, new Tretja.Stanovanjska(97));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(15));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 10, new Tretja.Poslovna());
        mesto.postavi(18, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 14, new Tretja.Poslovna());
        mesto.postavi(29, 7, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 4, new Tretja.Stanovanjska(98));
        mesto.postavi(10, 3, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 2, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 13, new Tretja.Stanovanjska(72));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(7));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(92));
        mesto.postavi(11, 1, new Tretja.Stanovanjska(36));
        mesto.postavi(8, 10, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 15, new Tretja.Poslovna());
        mesto.postavi(16, 8, new Tretja.Poslovna());
        mesto.postavi(19, 3, new Tretja.Stanovanjska(53));
        mesto.postavi(12, 16, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 3, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Stanovanjska(27));
        mesto.postavi(10, 5, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 15, new Tretja.Stanovanjska(20));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 6, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 3, new Tretja.Poslovna());
        mesto.postavi(26, 14, new Tretja.Stanovanjska(57));
        mesto.postavi(16, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 5, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 4, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(6));
        mesto.postavi(9, 3, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 3, new Tretja.Stanovanjska(53));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 4, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 15, new Tretja.Stanovanjska(38));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(26, 15, new Tretja.Poslovna());
        mesto.postavi(27, 12, new Tretja.Stanovanjska(54));
        mesto.postavi(18, 2, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 5, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(25, 5, new Tretja.Stanovanjska(33));
        mesto.postavi(4, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 3, new Tretja.Poslovna());
        mesto.postavi(18, 12, new Tretja.Poslovna());
        mesto.postavi(29, 2, new Tretja.Stanovanjska(26));
        mesto.postavi(28, 9, new Tretja.Stanovanjska(100));
        mesto.postavi(23, 6, new Tretja.Poslovna());
        mesto.postavi(8, 8, new Tretja.Stanovanjska(2));
        mesto.postavi(29, 11, new Tretja.Stanovanjska(95));
        mesto.postavi(20, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 7, new Tretja.Poslovna());
        mesto.postavi(21, 13, new Tretja.Stanovanjska(35));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 9, new Tretja.Stanovanjska(71));
        mesto.postavi(25, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(18, 16, new Tretja.Poslovna());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(2));
        mesto.postavi(14, 12, new Tretja.Stanovanjska(61));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(15, 9, new Tretja.Stanovanjska(38));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(77));
        mesto.postavi(17, 2, new Tretja.Stanovanjska(27));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(29));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(63));
        mesto.postavi(15, 1, new Tretja.Stanovanjska(21));
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(18, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 4, new Tretja.Poslovna());
        mesto.postavi(12, 3, new Tretja.Poslovna());
        mesto.postavi(26, 10, new Tretja.Poslovna());
        mesto.postavi(29, 16, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 5, new Tretja.Stanovanjska(45));
        mesto.postavi(7, 0, new Tretja.Stanovanjska(7));
        mesto.postavi(11, 15, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 14, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(26, 8, new Tretja.Stanovanjska(74));
        mesto.postavi(7, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(26, 3, new Tretja.Stanovanjska(22));
        mesto.postavi(28, 13, new Tretja.Stanovanjska(35));
        mesto.postavi(6, 14, new Tretja.Stanovanjska(52));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(37));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 13, new Tretja.Stanovanjska(25));
        mesto.postavi(6, 13, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(25, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(28, 8, new Tretja.Poslovna());
        mesto.postavi(10, 16, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 12, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Stanovanjska(85));
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 6, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Poslovna());
        mesto.postavi(14, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 14, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 2, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 14, new Tretja.Stanovanjska(67));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(26, 13, new Tretja.Stanovanjska(54));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 15, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Poslovna());
        mesto.postavi(19, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(54));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 16, new Tretja.Poslovna());
        mesto.postavi(22, 0, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 11, new Tretja.Poslovna());
        mesto.postavi(23, 16, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 1, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 1, new Tretja.Stanovanjska(83));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(31));
        mesto.postavi(25, 11, new Tretja.Poslovna());
        mesto.postavi(16, 16, new Tretja.Stanovanjska(59));
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(17, 5, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Poslovna());
        mesto.postavi(15, 13, new Tretja.Stanovanjska(75));
        mesto.postavi(15, 10, new Tretja.Poslovna());
        mesto.postavi(18, 9, new Tretja.Poslovna());
        mesto.postavi(23, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Stanovanjska(79));
        mesto.postavi(24, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 6, new Tretja.Stanovanjska(12));
        mesto.postavi(17, 9, new Tretja.Stanovanjska(5));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(13, 15, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(84));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 11, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 4, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 10, new Tretja.Stanovanjska(88));
        mesto.postavi(29, 8, new Tretja.Stanovanjska(76));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(67));
        mesto.postavi(5, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 3, new Tretja.Poslovna());
        mesto.postavi(17, 7, new Tretja.Poslovna());
        mesto.postavi(12, 1, new Tretja.Stanovanjska(33));
        mesto.postavi(25, 3, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 2, new Tretja.Stanovanjska(81));
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(24, 13, new Tretja.Poslovna());
        mesto.postavi(6, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(29, 15, new Tretja.Poslovna());
        mesto.postavi(28, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Stanovanjska(77));
        mesto.postavi(14, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 5, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        mesto.postavi(5, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 16, new Tretja.Stanovanjska(24));
        mesto.postavi(13, 3, new Tretja.Stanovanjska(24));
        mesto.postavi(25, 15, new Tretja.Poslovna());
        mesto.postavi(12, 8, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Stanovanjska(94));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 8, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Poslovna());
        mesto.postavi(27, 13, new Tretja.Stanovanjska(66));
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Stanovanjska(8));
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(24, 10, new Tretja.Stanovanjska(99));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(25, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 13, new Tretja.Poslovna());
        mesto.postavi(28, 2, new Tretja.Stanovanjska(38));
        mesto.postavi(27, 6, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(14, 2, new Tretja.Poslovna());
        mesto.postavi(24, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(27, 4, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
    }
}
