
import java.util.*;

public class Test04 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(25, 21);

        mesto.postavi(10, 3, new Tretja.Stanovanjska(52));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(38));
        mesto.postavi(2, 18, new Tretja.Stanovanjska(70));
        mesto.postavi(21, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 17, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 20, new Tretja.Stanovanjska(72));
        mesto.postavi(4, 17, new Tretja.Stanovanjska(24));
        mesto.postavi(19, 12, new Tretja.Poslovna());
        mesto.postavi(20, 7, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(18, 5, new Tretja.Stanovanjska(91));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 5, new Tretja.Stanovanjska(16));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(20, 14, new Tretja.Stanovanjska(76));
        mesto.postavi(11, 10, new Tretja.Stanovanjska(85));
        mesto.postavi(22, 2, new Tretja.Stanovanjska(24));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(99));
        mesto.postavi(24, 14, new Tretja.Poslovna());
        mesto.postavi(3, 8, new Tretja.Stanovanjska(10));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(5, 3, new Tretja.Poslovna());
        mesto.postavi(19, 13, new Tretja.Poslovna());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(7));
        mesto.postavi(6, 18, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(31));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 11, new Tretja.Stanovanjska(74));
        mesto.postavi(9, 10, new Tretja.Stanovanjska(68));
        mesto.postavi(2, 4, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 9, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 16, new Tretja.Stanovanjska(66));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 15, new Tretja.Stanovanjska(15));
        mesto.postavi(18, 5, new Tretja.Stanovanjska(79));
        mesto.postavi(21, 0, new Tretja.Poslovna());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(11));
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Stanovanjska(16));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(13, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 19, new Tretja.Stanovanjska(6));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(9, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 20, new Tretja.Poslovna());
        mesto.postavi(18, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 0, new Tretja.Stanovanjska(22));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(8, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Poslovna());
        mesto.postavi(23, 15, new Tretja.Stanovanjska(88));
        mesto.postavi(2, 3, new Tretja.Stanovanjska(15));
        mesto.postavi(16, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 19, new Tretja.Poslovna());
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(21, 18, new Tretja.Stanovanjska(28));
        mesto.postavi(24, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 18, new Tretja.Poslovna());
        mesto.postavi(14, 5, new Tretja.Stanovanjska(97));
        mesto.postavi(7, 12, new Tretja.Poslovna());
        mesto.postavi(14, 6, new Tretja.Poslovna());
        mesto.postavi(20, 6, new Tretja.Stanovanjska(35));
        mesto.postavi(13, 19, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Poslovna());
        mesto.postavi(17, 9, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 0, new Tretja.Stanovanjska(91));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Poslovna());
        mesto.postavi(24, 17, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 15, new Tretja.Poslovna());
        mesto.postavi(9, 17, new Tretja.Stanovanjska(93));
        mesto.postavi(8, 10, new Tretja.Poslovna());
        mesto.postavi(16, 11, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Stanovanjska(87));
        mesto.postavi(12, 11, new Tretja.Stanovanjska(25));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 0, new Tretja.Stanovanjska(72));
        mesto.postavi(20, 1, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Poslovna());
        mesto.postavi(19, 17, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 1, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 15, new Tretja.Stanovanjska(52));
        mesto.postavi(21, 3, new Tretja.Stanovanjska(91));
        mesto.postavi(8, 2, new Tretja.Poslovna());
        mesto.postavi(19, 17, new Tretja.Stanovanjska(75));
        mesto.postavi(21, 0, new Tretja.Poslovna());
        mesto.postavi(16, 19, new Tretja.Poslovna());
        mesto.postavi(17, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 6, new Tretja.Stanovanjska(2));
        mesto.postavi(9, 11, new Tretja.Poslovna());
        mesto.postavi(9, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 19, new Tretja.Stanovanjska(76));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(33));
        mesto.postavi(3, 8, new Tretja.Stanovanjska(64));
        mesto.postavi(8, 5, new Tretja.Stanovanjska(67));
        mesto.postavi(16, 19, new Tretja.Stanovanjska(82));
        mesto.postavi(17, 18, new Tretja.Poslovna());
        mesto.postavi(21, 18, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 18, new Tretja.Stanovanjska(7));
        mesto.postavi(21, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 5, new Tretja.Poslovna());
        mesto.postavi(19, 5, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 14, new Tretja.Stanovanjska(55));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 15, new Tretja.Poslovna());
        mesto.postavi(21, 16, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 16, new Tretja.Poslovna());
        mesto.postavi(7, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 14, new Tretja.Poslovna());
        mesto.postavi(12, 20, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Stanovanjska(15));
        mesto.postavi(16, 11, new Tretja.Stanovanjska(9));
        mesto.postavi(24, 6, new Tretja.Stanovanjska(74));
        mesto.postavi(14, 17, new Tretja.Stanovanjska(82));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 18, new Tretja.Stanovanjska(29));
        mesto.postavi(23, 0, new Tretja.Poslovna());
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(24, 9, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(24, 6, new Tretja.Stanovanjska(39));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 20, new Tretja.Poslovna());
        mesto.postavi(20, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Stanovanjska(36));
        mesto.postavi(6, 14, new Tretja.Poslovna());
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 18, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 16, new Tretja.Stanovanjska(39));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        mesto.postavi(22, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 4, new Tretja.Stanovanjska(66));
        mesto.postavi(9, 20, new Tretja.Poslovna());
        mesto.postavi(10, 14, new Tretja.Stanovanjska(71));
        mesto.postavi(15, 7, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 10, new Tretja.Stanovanjska(70));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(15, 19, new Tretja.Stanovanjska(15));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 10, new Tretja.Stanovanjska(66));
        mesto.postavi(0, 3, new Tretja.Stanovanjska(43));
        mesto.postavi(14, 7, new Tretja.Stanovanjska(61));
        mesto.postavi(5, 3, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Stanovanjska(88));
        mesto.postavi(22, 6, new Tretja.Stanovanjska(87));
        mesto.postavi(24, 17, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(46));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Stanovanjska(57));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 17, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(25));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 5, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(99));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(3, 4, new Tretja.Stanovanjska(92));
        mesto.postavi(2, 4, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Stanovanjska(12));
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(4, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 0, new Tretja.Stanovanjska(95));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(30));
        mesto.postavi(0, 5, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 19, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 1, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(72));
        mesto.postavi(23, 9, new Tretja.Poslovna());
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(15, 3, new Tretja.Stanovanjska(31));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 17, new Tretja.Stanovanjska(58));
        mesto.postavi(1, 18, new Tretja.Stanovanjska(44));
        mesto.postavi(13, 1, new Tretja.Stanovanjska(97));
        mesto.postavi(8, 14, new Tretja.Stanovanjska(98));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(56));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(33));
        mesto.postavi(21, 12, new Tretja.Poslovna());
        mesto.postavi(0, 14, new Tretja.Stanovanjska(22));
        mesto.postavi(24, 9, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(43));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(65));
        mesto.postavi(12, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 20, new Tretja.Stanovanjska(71));
        mesto.postavi(20, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 13, new Tretja.Poslovna());
        mesto.postavi(16, 15, new Tretja.Stanovanjska(11));
        mesto.postavi(21, 16, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 19, new Tretja.Stanovanjska(84));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Stanovanjska(56));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 15, new Tretja.Stanovanjska(81));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(61));
        mesto.postavi(17, 15, new Tretja.Stanovanjska(86));
        mesto.postavi(8, 20, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Stanovanjska(57));
        mesto.postavi(19, 13, new Tretja.Stanovanjska(80));
        mesto.postavi(23, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Stanovanjska(12));
        mesto.postavi(12, 11, new Tretja.Stanovanjska(26));
        mesto.postavi(24, 13, new Tretja.Poslovna());
        mesto.postavi(4, 20, new Tretja.Poslovna());
        mesto.postavi(5, 15, new Tretja.Stanovanjska(53));
        mesto.postavi(9, 17, new Tretja.Stanovanjska(97));
        mesto.postavi(2, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(69));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 19, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 4, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 11, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(88));
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(15, 4, new Tretja.Poslovna());
        mesto.postavi(21, 3, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Stanovanjska(27));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(23, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 8, new Tretja.Poslovna());
        mesto.postavi(20, 16, new Tretja.Stanovanjska(81));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 14, new Tretja.Stanovanjska(14));
        mesto.postavi(12, 8, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Stanovanjska(39));
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(21, 18, new Tretja.Stanovanjska(69));
        mesto.postavi(20, 14, new Tretja.Stanovanjska(11));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Stanovanjska(60));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 4, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 9, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 9, new Tretja.Stanovanjska(50));
        mesto.postavi(5, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 19, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 6, new Tretja.Stanovanjska(64));
        mesto.postavi(20, 7, new Tretja.Stanovanjska(85));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Stanovanjska(31));
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Stanovanjska(12));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(12, 8, new Tretja.Stanovanjska(68));
        mesto.postavi(20, 15, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 2, new Tretja.Stanovanjska(68));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 20, new Tretja.Poslovna());
        mesto.postavi(16, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 0, new Tretja.Stanovanjska(49));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 5, new Tretja.Poslovna());
        mesto.postavi(24, 14, new Tretja.Stanovanjska(80));
        mesto.postavi(0, 8, new Tretja.Stanovanjska(30));
        mesto.postavi(1, 4, new Tretja.Stanovanjska(63));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 8, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(10, 14, new Tretja.Stanovanjska(3));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(29));
        mesto.postavi(20, 7, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Stanovanjska(22));
        mesto.postavi(21, 18, new Tretja.Stanovanjska(4));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(31));
        mesto.postavi(4, 15, new Tretja.Poslovna());
        mesto.postavi(23, 9, new Tretja.Poslovna());
        mesto.postavi(11, 1, new Tretja.Stanovanjska(77));
        mesto.postavi(8, 14, new Tretja.Stanovanjska(8));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(5));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Poslovna());
        mesto.postavi(13, 8, new Tretja.Stanovanjska(40));
        mesto.postavi(19, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 12, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 20, new Tretja.Stanovanjska(11));
        mesto.postavi(8, 2, new Tretja.Stanovanjska(57));
        mesto.postavi(10, 15, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(86));
        mesto.postavi(10, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 20, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Stanovanjska(23));
        mesto.postavi(10, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Stanovanjska(4));
        mesto.postavi(16, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 9, new Tretja.Stanovanjska(23));
        mesto.postavi(3, 15, new Tretja.Poslovna());
        mesto.postavi(18, 0, new Tretja.Stanovanjska(26));
        mesto.postavi(9, 17, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 11, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(17, 8, new Tretja.Poslovna());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(4, 13, new Tretja.Stanovanjska(77));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(73));
        mesto.postavi(22, 2, new Tretja.Stanovanjska(70));
        mesto.postavi(8, 8, new Tretja.Stanovanjska(58));
        mesto.postavi(19, 0, new Tretja.Stanovanjska(23));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(9));
        mesto.postavi(17, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 13, new Tretja.Poslovna());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 1, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Poslovna());
        mesto.postavi(22, 8, new Tretja.Stanovanjska(73));
        mesto.postavi(16, 14, new Tretja.Stanovanjska(67));
        mesto.postavi(6, 20, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(7, 1, new Tretja.Poslovna());
        mesto.postavi(3, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Stanovanjska(16));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(32));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 11, new Tretja.Stanovanjska(32));
        mesto.postavi(23, 10, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(20, 6, new Tretja.Stanovanjska(66));
        mesto.postavi(19, 2, new Tretja.Stanovanjska(28));
        mesto.postavi(15, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 1, new Tretja.Poslovna());
        mesto.postavi(20, 14, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 12, new Tretja.Stanovanjska(60));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 9, new Tretja.Poslovna());
        mesto.postavi(19, 11, new Tretja.Stanovanjska(59));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 5, new Tretja.Stanovanjska(63));
        mesto.postavi(17, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 3, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 14, new Tretja.Poslovna());
        mesto.postavi(0, 2, new Tretja.Stanovanjska(24));
        mesto.postavi(15, 15, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(14, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(20, 7, new Tretja.Poslovna());
        mesto.postavi(16, 10, new Tretja.Poslovna());
        mesto.postavi(21, 0, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 3, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 15, new Tretja.Poslovna());
        mesto.postavi(14, 17, new Tretja.Stanovanjska(86));
        mesto.postavi(19, 5, new Tretja.Stanovanjska(87));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 10, new Tretja.Poslovna());
        mesto.postavi(23, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(17, 15, new Tretja.Stanovanjska(68));
        mesto.postavi(12, 12, new Tretja.Poslovna());
        mesto.postavi(15, 14, new Tretja.Stanovanjska(16));
        mesto.postavi(24, 18, new Tretja.Stanovanjska(63));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 15, new Tretja.Stanovanjska(31));
        mesto.postavi(21, 10, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 5, new Tretja.Poslovna());
        mesto.postavi(21, 10, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 12, new Tretja.Stanovanjska(96));
        mesto.postavi(8, 12, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 12, new Tretja.Stanovanjska(73));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 12, new Tretja.Stanovanjska(18));
        mesto.postavi(16, 14, new Tretja.Poslovna());
        mesto.postavi(22, 8, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 12, new Tretja.Stanovanjska(85));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 19, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(16, 20, new Tretja.Poslovna());
        mesto.postavi(2, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(16, 5, new Tretja.Stanovanjska(71));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(5, 0, new Tretja.Stanovanjska(73));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(15, 4, new Tretja.Stanovanjska(52));
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Stanovanjska(63));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(47));
        mesto.postavi(16, 15, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 19, new Tretja.Poslovna());
        mesto.postavi(8, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 4, new Tretja.Poslovna());
        mesto.postavi(6, 15, new Tretja.Stanovanjska(26));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Stanovanjska(51));
        mesto.postavi(21, 20, new Tretja.Stanovanjska(97));
        mesto.postavi(16, 14, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(21, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 12, new Tretja.Stanovanjska(38));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(41));
        mesto.postavi(20, 6, new Tretja.Stanovanjska(23));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(71));
        mesto.postavi(6, 19, new Tretja.Stanovanjska(38));
        mesto.postavi(3, 13, new Tretja.Stanovanjska(3));
        mesto.postavi(10, 14, new Tretja.Poslovna());
        mesto.postavi(12, 8, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Stanovanjska(29));
        mesto.postavi(3, 4, new Tretja.Stanovanjska(3));
        mesto.postavi(10, 3, new Tretja.Poslovna());
        mesto.postavi(10, 11, new Tretja.Poslovna());
        mesto.postavi(7, 5, new Tretja.Stanovanjska(11));
        mesto.postavi(20, 14, new Tretja.Stanovanjska(25));
        mesto.postavi(21, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 19, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(24, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(22, 2, new Tretja.Stanovanjska(26));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(22, 8, new Tretja.Poslovna());
        mesto.postavi(18, 10, new Tretja.Stanovanjska(28));
        mesto.postavi(1, 10, new Tretja.Stanovanjska(91));
        mesto.postavi(24, 20, new Tretja.Poslovna());
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(21, 8, new Tretja.Stanovanjska(43));
        mesto.postavi(12, 8, new Tretja.Stanovanjska(24));
        mesto.postavi(21, 20, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(15, 0, new Tretja.Stanovanjska(17));
        mesto.postavi(17, 13, new Tretja.Stanovanjska(43));
        mesto.postavi(11, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Stanovanjska(5));
        mesto.postavi(12, 19, new Tretja.Poslovna());
        mesto.postavi(5, 5, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 16, new Tretja.Poslovna());
        mesto.postavi(21, 20, new Tretja.Poslovna());
        mesto.postavi(12, 6, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 3, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(19, 17, new Tretja.Poslovna());
        mesto.postavi(16, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(42));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(2));
        mesto.postavi(21, 19, new Tretja.Stanovanjska(42));
        mesto.postavi(19, 2, new Tretja.Stanovanjska(49));
        mesto.postavi(1, 13, new Tretja.Stanovanjska(30));
        mesto.postavi(18, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(18, 1, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 16, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(92));
        mesto.postavi(6, 2, new Tretja.Stanovanjska(18));
        mesto.postavi(23, 19, new Tretja.Stanovanjska(54));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(9, 17, new Tretja.Poslovna());
        mesto.postavi(14, 17, new Tretja.Stanovanjska(15));
        mesto.postavi(15, 9, new Tretja.Poslovna());
        mesto.postavi(9, 14, new Tretja.Stanovanjska(58));
        mesto.postavi(12, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(23, 0, new Tretja.Stanovanjska(98));
        mesto.postavi(8, 4, new Tretja.Stanovanjska(76));
        mesto.postavi(15, 19, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Stanovanjska(88));
        mesto.postavi(18, 20, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 2, new Tretja.Poslovna());
        mesto.postavi(19, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
