
import java.util.*;

public class Test14 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(12, 28);

        mesto.postavi(4, 7, new Tretja.Stanovanjska(77));
        mesto.postavi(3, 22, new Tretja.Stanovanjska(15));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 20, new Tretja.Stanovanjska(36));
        mesto.postavi(11, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 25, new Tretja.Stanovanjska(8));
        mesto.postavi(10, 22, new Tretja.Stanovanjska(95));
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Stanovanjska(82));
        mesto.postavi(2, 7, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 8, new Tretja.Poslovna());
        mesto.postavi(10, 12, new Tretja.Stanovanjska(50));
        mesto.postavi(10, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 16, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Stanovanjska(69));
        mesto.postavi(2, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 23, new Tretja.Stanovanjska(2));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(35));
        mesto.postavi(3, 23, new Tretja.Stanovanjska(15));
        mesto.postavi(3, 14, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 7, new Tretja.Stanovanjska(59));
        mesto.postavi(4, 27, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(10, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(32));
        mesto.postavi(7, 25, new Tretja.Poslovna());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(4, 14, new Tretja.Stanovanjska(99));
        mesto.postavi(3, 20, new Tretja.Poslovna());
        mesto.postavi(5, 19, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Stanovanjska(19));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(59));
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(11, 22, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(67));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(10));
        mesto.postavi(7, 5, new Tretja.Stanovanjska(21));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 26, new Tretja.Stanovanjska(37));
        mesto.postavi(8, 1, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 10, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Stanovanjska(8));
        mesto.postavi(4, 26, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 23, new Tretja.Poslovna());
        mesto.postavi(6, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 18, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(33));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(14));
        mesto.postavi(6, 12, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Poslovna());
        mesto.postavi(9, 16, new Tretja.Poslovna());
        mesto.postavi(11, 2, new Tretja.Stanovanjska(68));
        mesto.postavi(7, 17, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(34));
        mesto.postavi(7, 5, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Stanovanjska(36));
        mesto.postavi(8, 13, new Tretja.Stanovanjska(15));
        mesto.postavi(4, 26, new Tretja.Poslovna());
        mesto.postavi(2, 24, new Tretja.Stanovanjska(73));
        mesto.postavi(4, 27, new Tretja.Stanovanjska(73));
        mesto.postavi(10, 1, new Tretja.Stanovanjska(90));
        mesto.postavi(2, 27, new Tretja.Stanovanjska(90));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Stanovanjska(39));
        mesto.postavi(1, 14, new Tretja.Stanovanjska(53));
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 25, new Tretja.Stanovanjska(21));
        mesto.postavi(5, 5, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Stanovanjska(87));
        mesto.postavi(7, 12, new Tretja.Stanovanjska(21));
        mesto.postavi(4, 0, new Tretja.Stanovanjska(93));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(20));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 24, new Tretja.Poslovna());
        mesto.postavi(7, 26, new Tretja.Poslovna());
        mesto.postavi(3, 7, new Tretja.Stanovanjska(75));
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(64));
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(5, 24, new Tretja.Stanovanjska(69));
        mesto.postavi(10, 13, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 23, new Tretja.Stanovanjska(90));
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(53));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(44));
        mesto.postavi(9, 19, new Tretja.Poslovna());
        mesto.postavi(11, 27, new Tretja.Stanovanjska(26));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(84));
        mesto.postavi(9, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 6, new Tretja.Stanovanjska(71));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 12, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 8, new Tretja.Stanovanjska(89));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        mesto.postavi(1, 14, new Tretja.Stanovanjska(3));
        mesto.postavi(8, 18, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 3, new Tretja.Stanovanjska(70));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(5, 21, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 13, new Tretja.Stanovanjska(78));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 14, new Tretja.Stanovanjska(37));
        mesto.postavi(6, 6, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Stanovanjska(81));
        mesto.postavi(7, 19, new Tretja.Poslovna());
        mesto.postavi(3, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 27, new Tretja.Stanovanjska(28));
        mesto.postavi(7, 21, new Tretja.Stanovanjska(33));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(52));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Stanovanjska(46));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(60));
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(7, 17, new Tretja.Stanovanjska(77));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(24));
        mesto.postavi(8, 24, new Tretja.Stanovanjska(3));
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 25, new Tretja.Poslovna());
        mesto.postavi(6, 12, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Stanovanjska(73));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(48));
        mesto.postavi(2, 2, new Tretja.Stanovanjska(50));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 11, new Tretja.Stanovanjska(80));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 23, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Stanovanjska(41));
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(11, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(9, 23, new Tretja.Stanovanjska(63));
        mesto.postavi(3, 8, new Tretja.Stanovanjska(54));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(90));
        mesto.postavi(7, 12, new Tretja.Stanovanjska(82));
        mesto.postavi(0, 25, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 21, new Tretja.Stanovanjska(78));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(72));
        mesto.postavi(5, 19, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Stanovanjska(54));
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Poslovna());
        mesto.postavi(11, 18, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(42));
        mesto.postavi(1, 16, new Tretja.Stanovanjska(64));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Stanovanjska(68));
        mesto.postavi(5, 12, new Tretja.Stanovanjska(54));
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(11, 19, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Stanovanjska(42));
        mesto.postavi(10, 23, new Tretja.Stanovanjska(79));
        mesto.postavi(10, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        mesto.postavi(2, 25, new Tretja.Stanovanjska(61));
        mesto.postavi(11, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 22, new Tretja.Stanovanjska(1));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 14, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(71));
        mesto.postavi(2, 19, new Tretja.Stanovanjska(67));
        mesto.postavi(3, 23, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Stanovanjska(27));
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Stanovanjska(72));
        mesto.postavi(8, 23, new Tretja.Poslovna());
        mesto.postavi(1, 19, new Tretja.Stanovanjska(29));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(1, 20, new Tretja.Stanovanjska(58));
        mesto.postavi(8, 11, new Tretja.Stanovanjska(44));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Stanovanjska(58));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 18, new Tretja.Stanovanjska(84));
        mesto.postavi(0, 6, new Tretja.Stanovanjska(45));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 18, new Tretja.Stanovanjska(10));
        mesto.postavi(8, 24, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Stanovanjska(88));
        mesto.postavi(7, 12, new Tretja.Stanovanjska(14));
        mesto.postavi(4, 14, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 1, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(44));
        mesto.postavi(5, 2, new Tretja.Stanovanjska(6));
        mesto.postavi(10, 12, new Tretja.Stanovanjska(14));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(72));
        mesto.postavi(8, 7, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Poslovna());
        mesto.postavi(2, 27, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 18, new Tretja.Stanovanjska(7));
        mesto.postavi(3, 26, new Tretja.Poslovna());
        mesto.postavi(7, 11, new Tretja.Stanovanjska(8));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(5, 23, new Tretja.Poslovna());
        mesto.postavi(7, 7, new Tretja.Stanovanjska(8));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(1, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(6, 14, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 25, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 9, new Tretja.Stanovanjska(98));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(63));
        mesto.postavi(10, 10, new Tretja.Stanovanjska(74));
        mesto.postavi(6, 17, new Tretja.Poslovna());
        mesto.postavi(7, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 12, new Tretja.Poslovna());
        mesto.postavi(7, 24, new Tretja.Stanovanjska(36));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 16, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Stanovanjska(2));
        mesto.postavi(11, 0, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 18, new Tretja.Stanovanjska(24));
        mesto.postavi(2, 4, new Tretja.Stanovanjska(44));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(69));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(79));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 21, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 13, new Tretja.Stanovanjska(29));
        mesto.postavi(8, 13, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 23, new Tretja.Stanovanjska(59));
        mesto.postavi(10, 3, new Tretja.Stanovanjska(67));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(56));
        mesto.postavi(2, 6, new Tretja.Stanovanjska(16));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 27, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Stanovanjska(9));
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 24, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 10, new Tretja.Stanovanjska(42));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(10, 22, new Tretja.Stanovanjska(41));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(8, 25, new Tretja.Poslovna());
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(1));
        mesto.postavi(4, 7, new Tretja.Stanovanjska(3));
        mesto.postavi(8, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 21, new Tretja.Stanovanjska(19));
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 21, new Tretja.Stanovanjska(32));
        mesto.postavi(11, 3, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 26, new Tretja.Poslovna());
        mesto.postavi(10, 13, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(0, 9, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(12));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 24, new Tretja.Stanovanjska(11));
        mesto.postavi(3, 16, new Tretja.Stanovanjska(32));
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(32));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 22, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 20, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 18, new Tretja.Poslovna());
        mesto.postavi(10, 22, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 24, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 26, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 13, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(7, 25, new Tretja.Stanovanjska(94));
        mesto.postavi(10, 0, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(64));
        mesto.postavi(6, 8, new Tretja.Stanovanjska(19));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 16, new Tretja.Stanovanjska(67));
        mesto.postavi(10, 10, new Tretja.Stanovanjska(56));
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(37));
        mesto.postavi(2, 24, new Tretja.Stanovanjska(56));
        mesto.postavi(8, 1, new Tretja.Stanovanjska(75));
        mesto.postavi(0, 10, new Tretja.Poslovna());
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(11, 12, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(83));
        mesto.postavi(10, 13, new Tretja.Stanovanjska(83));
        mesto.postavi(4, 20, new Tretja.Stanovanjska(62));
        mesto.postavi(10, 3, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 19, new Tretja.Stanovanjska(48));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 17, new Tretja.Stanovanjska(43));
        mesto.postavi(9, 23, new Tretja.Stanovanjska(13));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(36));
        mesto.postavi(8, 25, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(45));
        mesto.postavi(11, 12, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 5, new Tretja.Poslovna());
        mesto.postavi(11, 12, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Poslovna());
        mesto.postavi(6, 18, new Tretja.Stanovanjska(8));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 12, new Tretja.Stanovanjska(88));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 3, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Poslovna());
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(3, 23, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(6, 26, new Tretja.Stanovanjska(43));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 10, new Tretja.Stanovanjska(100));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 8, new Tretja.Stanovanjska(66));
        mesto.postavi(6, 21, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(31));
        mesto.postavi(3, 20, new Tretja.Stanovanjska(77));
        mesto.postavi(2, 25, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(100));
        mesto.postavi(5, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(6, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 17, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 24, new Tretja.Stanovanjska(25));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 18, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Stanovanjska(41));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(74));
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(83));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 10, new Tretja.Stanovanjska(68));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(9, 19, new Tretja.Stanovanjska(96));
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(8, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(28));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 14, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 15, new Tretja.Stanovanjska(40));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 16, new Tretja.Stanovanjska(24));
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(24));
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(4));
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(55));
        mesto.postavi(10, 2, new Tretja.Stanovanjska(76));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 17, new Tretja.Stanovanjska(60));
        mesto.postavi(2, 2, new Tretja.Stanovanjska(42));
        mesto.postavi(7, 19, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Stanovanjska(59));
        mesto.postavi(8, 13, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(2, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 24, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(86));
        mesto.postavi(10, 18, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(2, 19, new Tretja.Stanovanjska(21));
        mesto.postavi(3, 13, new Tretja.Stanovanjska(11));
        mesto.postavi(8, 23, new Tretja.Stanovanjska(87));
        mesto.postavi(0, 18, new Tretja.Stanovanjska(75));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 14, new Tretja.Poslovna());
        mesto.postavi(7, 19, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 19, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
    }
}
