
import java.util.*;

public class Test15 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(14, 12);

        mesto.postavi(4, 11, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(33));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 3, new Tretja.Stanovanjska(14));
        mesto.postavi(13, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 10, new Tretja.Stanovanjska(64));
        mesto.postavi(6, 6, new Tretja.Stanovanjska(7));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 8, new Tretja.Stanovanjska(100));
        mesto.postavi(2, 11, new Tretja.Stanovanjska(44));
        mesto.postavi(11, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 5, new Tretja.Stanovanjska(65));
        mesto.postavi(2, 2, new Tretja.Stanovanjska(75));
        mesto.postavi(5, 4, new Tretja.Stanovanjska(96));
        mesto.postavi(1, 1, new Tretja.Stanovanjska(62));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(3, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 0, new Tretja.Stanovanjska(34));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(27));
        mesto.postavi(9, 4, new Tretja.Stanovanjska(83));
        mesto.postavi(2, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(10));
        mesto.postavi(8, 11, new Tretja.Stanovanjska(89));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 6, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        mesto.postavi(9, 0, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(10, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 3, new Tretja.Stanovanjska(45));
        mesto.postavi(2, 9, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        mesto.postavi(1, 0, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 9, new Tretja.Stanovanjska(22));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(22));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(32));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(88));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 0, new Tretja.Stanovanjska(54));
        mesto.postavi(13, 5, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(86));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(9, 5, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(11, 0, new Tretja.Stanovanjska(14));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 10, new Tretja.Stanovanjska(75));
        mesto.postavi(6, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 3, new Tretja.Stanovanjska(19));
        mesto.postavi(13, 2, new Tretja.Stanovanjska(28));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(2));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 6, new Tretja.Stanovanjska(91));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 5, new Tretja.Stanovanjska(24));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 1, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 6, new Tretja.Stanovanjska(93));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(51));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Stanovanjska(42));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(7, 5, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 0, new Tretja.Stanovanjska(5));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(37));
        mesto.postavi(13, 6, new Tretja.Stanovanjska(14));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(14));
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(6, 9, new Tretja.Poslovna());
        mesto.postavi(0, 7, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Poslovna());
        mesto.postavi(1, 11, new Tretja.Stanovanjska(98));
        mesto.postavi(5, 1, new Tretja.Poslovna());
        mesto.postavi(8, 2, new Tretja.Stanovanjska(9));
        mesto.postavi(13, 7, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 7, new Tretja.Stanovanjska(39));
        mesto.postavi(2, 1, new Tretja.Stanovanjska(26));
        mesto.postavi(9, 1, new Tretja.Stanovanjska(33));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(5, 5, new Tretja.Poslovna());
        mesto.postavi(9, 6, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 7, new Tretja.Stanovanjska(72));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(1, 9, new Tretja.Stanovanjska(79));
        mesto.postavi(4, 6, new Tretja.Stanovanjska(82));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(7, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 9, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Stanovanjska(29));
        mesto.postavi(12, 5, new Tretja.Stanovanjska(35));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(97));
        mesto.postavi(6, 10, new Tretja.Poslovna());
        mesto.postavi(6, 8, new Tretja.Stanovanjska(56));
        mesto.postavi(9, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 1, new Tretja.Stanovanjska(47));
        mesto.postavi(9, 9, new Tretja.Stanovanjska(4));
        mesto.postavi(10, 7, new Tretja.Stanovanjska(51));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 8, new Tretja.Stanovanjska(47));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 3, new Tretja.Stanovanjska(74));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 11, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 1, new Tretja.Stanovanjska(54));
        mesto.postavi(0, 2, new Tretja.Stanovanjska(81));
        mesto.postavi(1, 7, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(78));
        mesto.postavi(11, 11, new Tretja.Stanovanjska(6));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        mesto.postavi(11, 1, new Tretja.Stanovanjska(10));
        mesto.postavi(8, 4, new Tretja.Stanovanjska(23));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(10, 0, new Tretja.Stanovanjska(4));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(8, 1, new Tretja.Stanovanjska(97));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 0, new Tretja.Stanovanjska(65));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 2, new Tretja.Poslovna());
        mesto.postavi(11, 6, new Tretja.Stanovanjska(1));
        mesto.postavi(9, 2, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(34));
        mesto.postavi(4, 9, new Tretja.Stanovanjska(47));
        mesto.postavi(6, 0, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 10, new Tretja.Poslovna());
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(0, 1, new Tretja.Stanovanjska(85));
        mesto.postavi(6, 7, new Tretja.Stanovanjska(6));
        mesto.postavi(5, 2, new Tretja.Poslovna());
        mesto.postavi(3, 4, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(6, 4, new Tretja.Stanovanjska(94));
        mesto.postavi(13, 10, new Tretja.Stanovanjska(57));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(87));
        mesto.postavi(13, 9, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Poslovna());
        mesto.postavi(4, 4, new Tretja.Stanovanjska(66));
        mesto.postavi(12, 8, new Tretja.Poslovna());
        mesto.postavi(13, 4, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(11, 3, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(12, 9, new Tretja.Stanovanjska(49));
        mesto.postavi(2, 3, new Tretja.Stanovanjska(27));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(5, 0, new Tretja.Stanovanjska(8));
        mesto.postavi(12, 1, new Tretja.Poslovna());
        mesto.postavi(12, 10, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(10, 4, new Tretja.Stanovanjska(25));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(92));
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 1, new Tretja.Stanovanjska(65));
        mesto.postavi(2, 5, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(3, 6, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 0, new Tretja.Poslovna());
        mesto.postavi(7, 11, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
        mesto.postavi(13, 8, new Tretja.Poslovna());
        System.out.println(mesto.steviloStanovanj());
    }
}
