
import java.util.*;

public class Test19 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(23, 18);

        mesto.postavi(16, 16, new Tretja.Stanovanjska(50));
        mesto.postavi(2, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 16, new Tretja.Poslovna());
        mesto.postavi(19, 4, new Tretja.Poslovna());
        mesto.postavi(3, 0, new Tretja.Stanovanjska(8));
        mesto.postavi(3, 6, new Tretja.Poslovna());
        mesto.postavi(13, 16, new Tretja.Stanovanjska(95));
        mesto.postavi(11, 1, new Tretja.Poslovna());
        mesto.postavi(22, 14, new Tretja.Stanovanjska(52));
        mesto.postavi(18, 5, new Tretja.Poslovna());
        mesto.postavi(18, 12, new Tretja.Poslovna());
        mesto.postavi(8, 3, new Tretja.Stanovanjska(88));
        mesto.postavi(2, 0, new Tretja.Stanovanjska(49));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 13, new Tretja.Stanovanjska(9));
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(9, 0, new Tretja.Stanovanjska(17));
        mesto.postavi(19, 15, new Tretja.Stanovanjska(5));
        mesto.postavi(22, 15, new Tretja.Poslovna());
        mesto.postavi(6, 16, new Tretja.Poslovna());
        mesto.postavi(17, 11, new Tretja.Stanovanjska(71));
        mesto.postavi(22, 8, new Tretja.Poslovna());
        mesto.postavi(19, 16, new Tretja.Stanovanjska(67));
        mesto.postavi(7, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 3, new Tretja.Stanovanjska(17));
        mesto.postavi(20, 15, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 2, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(9, 15, new Tretja.Stanovanjska(78));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 10, new Tretja.Poslovna());
        mesto.postavi(18, 17, new Tretja.Poslovna());
        mesto.postavi(1, 7, new Tretja.Stanovanjska(90));
        mesto.postavi(18, 9, new Tretja.Poslovna());
        mesto.postavi(6, 0, new Tretja.Stanovanjska(75));
        mesto.postavi(12, 17, new Tretja.Poslovna());
        mesto.postavi(15, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 0, new Tretja.Stanovanjska(16));
        mesto.postavi(4, 7, new Tretja.Stanovanjska(21));
        mesto.postavi(2, 6, new Tretja.Poslovna());
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Poslovna());
        mesto.postavi(7, 2, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(39));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(85));
        mesto.postavi(19, 13, new Tretja.Stanovanjska(54));
        mesto.postavi(21, 11, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 17, new Tretja.Stanovanjska(97));
        mesto.postavi(8, 17, new Tretja.Stanovanjska(88));
        mesto.postavi(3, 3, new Tretja.Stanovanjska(74));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 13, new Tretja.Stanovanjska(3));
        mesto.postavi(4, 3, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 13, new Tretja.Stanovanjska(78));
        mesto.postavi(14, 13, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 6, new Tretja.Stanovanjska(39));
        mesto.postavi(21, 17, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Poslovna());
        mesto.postavi(8, 7, new Tretja.Stanovanjska(79));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(11, 13, new Tretja.Poslovna());
        mesto.postavi(7, 11, new Tretja.Stanovanjska(63));
        mesto.postavi(7, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 0, new Tretja.Stanovanjska(50));
        mesto.postavi(0, 15, new Tretja.Stanovanjska(96));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(13));
        mesto.postavi(18, 8, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 11, new Tretja.Stanovanjska(68));
        mesto.postavi(14, 14, new Tretja.Stanovanjska(20));
        mesto.postavi(13, 13, new Tretja.Stanovanjska(50));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 11, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(19));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 8, new Tretja.Stanovanjska(100));
        mesto.postavi(1, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 7, new Tretja.Stanovanjska(66));
        mesto.postavi(4, 1, new Tretja.Stanovanjska(66));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 14, new Tretja.Stanovanjska(26));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(13, 5, new Tretja.Poslovna());
        mesto.postavi(0, 17, new Tretja.Stanovanjska(89));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 10, new Tretja.Stanovanjska(89));
        mesto.postavi(13, 4, new Tretja.Stanovanjska(32));
        mesto.postavi(21, 3, new Tretja.Stanovanjska(23));
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(10, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 12, new Tretja.Stanovanjska(90));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(5, 14, new Tretja.Stanovanjska(51));
        mesto.postavi(2, 16, new Tretja.Stanovanjska(79));
        mesto.postavi(17, 2, new Tretja.Stanovanjska(88));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 3, new Tretja.Stanovanjska(9));
        mesto.postavi(12, 2, new Tretja.Stanovanjska(48));
        mesto.postavi(21, 4, new Tretja.Stanovanjska(59));
        mesto.postavi(7, 1, new Tretja.Stanovanjska(18));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 5, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(21, 1, new Tretja.Stanovanjska(94));
        mesto.postavi(2, 9, new Tretja.Stanovanjska(43));
        mesto.postavi(8, 8, new Tretja.Stanovanjska(58));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 5, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 6, new Tretja.Poslovna());
        mesto.postavi(9, 14, new Tretja.Poslovna());
        mesto.postavi(10, 11, new Tretja.Poslovna());
        mesto.postavi(0, 11, new Tretja.Stanovanjska(19));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(21, 10, new Tretja.Poslovna());
        mesto.postavi(15, 1, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 3, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 12, new Tretja.Stanovanjska(61));
        mesto.postavi(0, 13, new Tretja.Stanovanjska(5));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 5, new Tretja.Stanovanjska(98));
        mesto.postavi(12, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 4, new Tretja.Poslovna());
        mesto.postavi(18, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 2, new Tretja.Stanovanjska(84));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 14, new Tretja.Stanovanjska(87));
        mesto.postavi(13, 0, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Poslovna());
        mesto.postavi(3, 7, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 13, new Tretja.Poslovna());
        mesto.postavi(13, 11, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 6, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(7, 0, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Stanovanjska(5));
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(20, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 0, new Tretja.Stanovanjska(94));
        mesto.postavi(17, 5, new Tretja.Stanovanjska(91));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 10, new Tretja.Stanovanjska(7));
        mesto.postavi(22, 10, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 17, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Poslovna());
        mesto.postavi(14, 8, new Tretja.Stanovanjska(40));
        mesto.postavi(8, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 9, new Tretja.Stanovanjska(45));
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Stanovanjska(99));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 5, new Tretja.Stanovanjska(88));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(0, 8, new Tretja.Stanovanjska(52));
        mesto.postavi(16, 7, new Tretja.Stanovanjska(32));
        mesto.postavi(18, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 0, new Tretja.Stanovanjska(30));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 15, new Tretja.Stanovanjska(51));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 4, new Tretja.Poslovna());
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(5, 1, new Tretja.Stanovanjska(10));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(18, 4, new Tretja.Poslovna());
        mesto.postavi(18, 6, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(9, 2, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(21, 2, new Tretja.Poslovna());
        mesto.postavi(13, 15, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 12, new Tretja.Stanovanjska(42));
        mesto.postavi(1, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 12, new Tretja.Stanovanjska(46));
        mesto.postavi(9, 5, new Tretja.Stanovanjska(40));
        mesto.postavi(11, 6, new Tretja.Poslovna());
        mesto.postavi(13, 10, new Tretja.Stanovanjska(76));
        mesto.postavi(1, 10, new Tretja.Stanovanjska(42));
        mesto.postavi(8, 5, new Tretja.Stanovanjska(56));
        mesto.postavi(13, 14, new Tretja.Stanovanjska(78));
        mesto.postavi(11, 11, new Tretja.Poslovna());
        mesto.postavi(13, 1, new Tretja.Poslovna());
        mesto.postavi(7, 10, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Stanovanjska(43));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        mesto.postavi(20, 8, new Tretja.Stanovanjska(46));
        mesto.postavi(1, 17, new Tretja.Poslovna());
        mesto.postavi(11, 16, new Tretja.Poslovna());
        mesto.postavi(1, 1, new Tretja.Poslovna());
        mesto.postavi(9, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 6, new Tretja.Poslovna());
        mesto.postavi(11, 9, new Tretja.Stanovanjska(34));
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(22, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 14, new Tretja.Stanovanjska(87));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
