
import java.util.*;

public class Test25 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(22, 17);

        mesto.postavi(18, 5, new Tretja.Stanovanjska(45));
        mesto.postavi(14, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 13, new Tretja.Poslovna());
        mesto.postavi(16, 1, new Tretja.Stanovanjska(3));
        mesto.postavi(12, 2, new Tretja.Stanovanjska(87));
        mesto.postavi(3, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 8, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 8, new Tretja.Stanovanjska(75));
        mesto.postavi(20, 15, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Stanovanjska(36));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 7, new Tretja.Poslovna());
        mesto.postavi(8, 10, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 11, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 0, new Tretja.Stanovanjska(34));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 0, new Tretja.Stanovanjska(16));
        mesto.postavi(11, 1, new Tretja.Poslovna());
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(4, 9, new Tretja.Poslovna());
        mesto.postavi(15, 16, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Stanovanjska(86));
        mesto.postavi(21, 1, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Stanovanjska(30));
        mesto.postavi(6, 14, new Tretja.Stanovanjska(16));
        mesto.postavi(7, 15, new Tretja.Stanovanjska(92));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(55));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 9, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 13, new Tretja.Stanovanjska(3));
        mesto.postavi(13, 8, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(4, 6, new Tretja.Stanovanjska(32));
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(3, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 16, new Tretja.Poslovna());
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Poslovna());
        mesto.postavi(21, 9, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Poslovna());
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 5, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 4, new Tretja.Stanovanjska(16));
        mesto.postavi(20, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 8, new Tretja.Stanovanjska(48));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 9, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(97));
        mesto.postavi(1, 5, new Tretja.Stanovanjska(83));
        mesto.postavi(7, 2, new Tretja.Stanovanjska(38));
        mesto.postavi(10, 6, new Tretja.Poslovna());
        mesto.postavi(21, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 2, new Tretja.Stanovanjska(22));
        mesto.postavi(11, 3, new Tretja.Stanovanjska(59));
        mesto.postavi(8, 1, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        mesto.postavi(6, 5, new Tretja.Stanovanjska(3));
        mesto.postavi(7, 3, new Tretja.Poslovna());
        mesto.postavi(16, 6, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 3, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 9, new Tretja.Poslovna());
        mesto.postavi(19, 1, new Tretja.Poslovna());
        mesto.postavi(0, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 10, new Tretja.Stanovanjska(43));
        mesto.postavi(17, 15, new Tretja.Poslovna());
        mesto.postavi(4, 7, new Tretja.Poslovna());
        mesto.postavi(18, 9, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 1, new Tretja.Stanovanjska(74));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 5, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 11, new Tretja.Poslovna());
        mesto.postavi(16, 5, new Tretja.Stanovanjska(19));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(15, 7, new Tretja.Poslovna());
        mesto.postavi(4, 11, new Tretja.Stanovanjska(59));
        mesto.postavi(9, 15, new Tretja.Stanovanjska(32));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 3, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 4, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 4, new Tretja.Poslovna());
        mesto.postavi(11, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 3, new Tretja.Poslovna());
        mesto.postavi(2, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 16, new Tretja.Stanovanjska(32));
        mesto.postavi(16, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 15, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 4, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(19, 9, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        mesto.postavi(10, 5, new Tretja.Poslovna());
        mesto.postavi(19, 14, new Tretja.Stanovanjska(12));
        mesto.postavi(17, 4, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 8, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Stanovanjska(18));
        mesto.postavi(16, 11, new Tretja.Stanovanjska(82));
        mesto.postavi(21, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 0, new Tretja.Stanovanjska(23));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 13, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 13, new Tretja.Stanovanjska(90));
        mesto.postavi(18, 15, new Tretja.Poslovna());
        mesto.postavi(21, 15, new Tretja.Stanovanjska(64));
        mesto.postavi(17, 8, new Tretja.Stanovanjska(38));
        mesto.postavi(9, 6, new Tretja.Poslovna());
        mesto.postavi(15, 13, new Tretja.Stanovanjska(96));
        mesto.postavi(20, 6, new Tretja.Poslovna());
        mesto.postavi(5, 10, new Tretja.Stanovanjska(75));
        mesto.postavi(12, 16, new Tretja.Poslovna());
        mesto.postavi(17, 6, new Tretja.Stanovanjska(55));
        mesto.postavi(14, 16, new Tretja.Stanovanjska(5));
        mesto.postavi(4, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 10, new Tretja.Poslovna());
        mesto.postavi(11, 2, new Tretja.Stanovanjska(79));
        mesto.postavi(1, 1, new Tretja.Stanovanjska(62));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 12, new Tretja.Stanovanjska(8));
        mesto.postavi(15, 6, new Tretja.Poslovna());
        mesto.postavi(20, 3, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 7, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Poslovna());
        mesto.postavi(13, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 6, new Tretja.Stanovanjska(6));
        mesto.postavi(15, 15, new Tretja.Poslovna());
        mesto.postavi(11, 15, new Tretja.Poslovna());
        mesto.postavi(13, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 0, new Tretja.Stanovanjska(37));
        mesto.postavi(5, 8, new Tretja.Poslovna());
        mesto.postavi(13, 4, new Tretja.Poslovna());
        mesto.postavi(5, 12, new Tretja.Poslovna());
        mesto.postavi(19, 12, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Poslovna());
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(19, 6, new Tretja.Poslovna());
        mesto.postavi(12, 12, new Tretja.Stanovanjska(39));
        mesto.postavi(0, 12, new Tretja.Poslovna());
        mesto.postavi(20, 5, new Tretja.Stanovanjska(26));
        mesto.postavi(20, 12, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 11, new Tretja.Stanovanjska(55));
        mesto.postavi(5, 7, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 0, new Tretja.Poslovna());
        mesto.postavi(15, 2, new Tretja.Poslovna());
        mesto.postavi(7, 6, new Tretja.Poslovna());
        mesto.postavi(1, 4, new Tretja.Poslovna());
        mesto.postavi(6, 6, new Tretja.Stanovanjska(13));
        mesto.postavi(6, 0, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 14, new Tretja.Poslovna());
        mesto.postavi(15, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 9, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 5, new Tretja.Poslovna());
        mesto.postavi(19, 15, new Tretja.Poslovna());
        mesto.postavi(16, 7, new Tretja.Stanovanjska(46));
        mesto.postavi(13, 7, new Tretja.Poslovna());
        mesto.postavi(20, 10, new Tretja.Stanovanjska(77));
        mesto.postavi(1, 13, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 1, new Tretja.Stanovanjska(59));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 3, new Tretja.Poslovna());
        mesto.postavi(17, 5, new Tretja.Poslovna());
        mesto.postavi(8, 9, new Tretja.Stanovanjska(13));
        mesto.postavi(19, 16, new Tretja.Poslovna());
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(5, 15, new Tretja.Poslovna());
        mesto.postavi(9, 4, new Tretja.Stanovanjska(56));
        mesto.postavi(7, 12, new Tretja.Stanovanjska(96));
        mesto.postavi(5, 13, new Tretja.Stanovanjska(29));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 8, new Tretja.Poslovna());
        mesto.postavi(5, 4, new Tretja.Poslovna());
        mesto.postavi(12, 9, new Tretja.Poslovna());
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(18, 2, new Tretja.Poslovna());
        mesto.postavi(16, 14, new Tretja.Poslovna());
        mesto.postavi(10, 9, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 12, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Poslovna());
        mesto.postavi(12, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 5, new Tretja.Stanovanjska(47));
        mesto.postavi(1, 0, new Tretja.Stanovanjska(32));
        mesto.postavi(3, 11, new Tretja.Stanovanjska(1));
        mesto.postavi(18, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 11, new Tretja.Stanovanjska(54));
        mesto.postavi(21, 4, new Tretja.Stanovanjska(60));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(48));
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 12, new Tretja.Stanovanjska(91));
        mesto.postavi(20, 1, new Tretja.Stanovanjska(32));
        mesto.postavi(20, 7, new Tretja.Poslovna());
        mesto.postavi(1, 14, new Tretja.Stanovanjska(56));
        mesto.postavi(12, 14, new Tretja.Poslovna());
        mesto.postavi(16, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 8, new Tretja.Stanovanjska(52));
        mesto.postavi(7, 11, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 13, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 3, new Tretja.Poslovna());
        mesto.postavi(14, 7, new Tretja.Stanovanjska(4));
        mesto.postavi(21, 13, new Tretja.Stanovanjska(37));
        mesto.postavi(13, 5, new Tretja.Poslovna());
        mesto.postavi(21, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 9, new Tretja.Poslovna());
        mesto.postavi(8, 15, new Tretja.Stanovanjska(11));
        mesto.postavi(16, 9, new Tretja.Poslovna());
        mesto.postavi(7, 0, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 3, new Tretja.Poslovna());
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(1, 6, new Tretja.Poslovna());
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(5, 3, new Tretja.Poslovna());
        mesto.postavi(0, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 14, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 14, new Tretja.Stanovanjska(4));
        mesto.postavi(21, 8, new Tretja.Stanovanjska(93));
        mesto.postavi(16, 10, new Tretja.Poslovna());
        mesto.postavi(21, 12, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 16, new Tretja.Poslovna());
        mesto.postavi(18, 7, new Tretja.Stanovanjska(18));
        mesto.postavi(19, 10, new Tretja.Poslovna());
        mesto.postavi(9, 5, new Tretja.Stanovanjska(82));
        mesto.postavi(0, 6, new Tretja.Poslovna());
        mesto.postavi(6, 15, new Tretja.Stanovanjska(62));
        mesto.postavi(6, 2, new Tretja.Stanovanjska(93));
        mesto.postavi(11, 5, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 8, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 1, new Tretja.Stanovanjska(23));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 2, new Tretja.Poslovna());
        mesto.postavi(12, 0, new Tretja.Stanovanjska(80));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 13, new Tretja.Stanovanjska(1));
        mesto.postavi(14, 11, new Tretja.Stanovanjska(53));
        mesto.postavi(15, 4, new Tretja.Poslovna());
        mesto.postavi(20, 2, new Tretja.Stanovanjska(67));
        mesto.postavi(10, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 11, new Tretja.Poslovna());
        mesto.postavi(17, 13, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(21));
        mesto.postavi(20, 16, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 0, new Tretja.Stanovanjska(89));
        mesto.postavi(15, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 12, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Poslovna());
        mesto.postavi(6, 7, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 16, new Tretja.Poslovna());
        mesto.postavi(12, 15, new Tretja.Stanovanjska(46));
        mesto.postavi(14, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 2, new Tretja.Stanovanjska(38));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(46));
        mesto.postavi(11, 14, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(17));
        mesto.postavi(11, 9, new Tretja.Poslovna());
        mesto.postavi(8, 11, new Tretja.Stanovanjska(60));
        mesto.postavi(12, 8, new Tretja.Stanovanjska(56));
        mesto.postavi(17, 14, new Tretja.Stanovanjska(89));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 1, new Tretja.Stanovanjska(19));
        mesto.postavi(16, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        mesto.postavi(6, 16, new Tretja.Poslovna());
        mesto.postavi(0, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 10, new Tretja.Poslovna());
        mesto.postavi(12, 1, new Tretja.Stanovanjska(49));
        mesto.postavi(7, 14, new Tretja.Stanovanjska(35));
        mesto.postavi(10, 15, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(26));
        mesto.postavi(10, 0, new Tretja.Stanovanjska(10));
        mesto.postavi(8, 6, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        mesto.postavi(7, 9, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(11, 12, new Tretja.Stanovanjska(87));
        mesto.postavi(8, 0, new Tretja.Poslovna());
        mesto.postavi(10, 10, new Tretja.Stanovanjska(33));
        mesto.postavi(18, 4, new Tretja.Poslovna());
        mesto.postavi(0, 7, new Tretja.Stanovanjska(38));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 10, new Tretja.Stanovanjska(46));
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(3, 8, new Tretja.Poslovna());
        mesto.postavi(16, 13, new Tretja.Stanovanjska(45));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(14, 4, new Tretja.Poslovna());
        mesto.postavi(21, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 0, new Tretja.Poslovna());
        mesto.postavi(9, 3, new Tretja.Stanovanjska(61));
        mesto.postavi(15, 10, new Tretja.Stanovanjska(8));
        mesto.postavi(8, 16, new Tretja.Poslovna());
        mesto.postavi(14, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 2, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 13, new Tretja.Stanovanjska(64));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 4, new Tretja.Poslovna());
        mesto.postavi(12, 10, new Tretja.Stanovanjska(56));
        mesto.postavi(1, 16, new Tretja.Poslovna());
        mesto.postavi(20, 4, new Tretja.Stanovanjska(66));
        mesto.postavi(8, 7, new Tretja.Stanovanjska(53));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 16, new Tretja.Poslovna());
        mesto.postavi(5, 0, new Tretja.Stanovanjska(9));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 6, new Tretja.Stanovanjska(8));
        mesto.postavi(1, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 3, new Tretja.Stanovanjska(43));
        mesto.postavi(15, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
