
import java.util.*;

public class Test31 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(15, 27);

        mesto.postavi(12, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 8, new Tretja.Poslovna());
        mesto.postavi(3, 12, new Tretja.Poslovna());
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(10, 7, new Tretja.Stanovanjska(51));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 12, new Tretja.Poslovna());
        mesto.postavi(5, 3, new Tretja.Stanovanjska(54));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 24, new Tretja.Poslovna());
        mesto.postavi(14, 15, new Tretja.Poslovna());
        mesto.postavi(0, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 20, new Tretja.Poslovna());
        mesto.postavi(10, 12, new Tretja.Poslovna());
        mesto.postavi(9, 14, new Tretja.Poslovna());
        mesto.postavi(9, 21, new Tretja.Poslovna());
        mesto.postavi(13, 2, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 19, new Tretja.Stanovanjska(48));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(8));
        mesto.postavi(2, 5, new Tretja.Poslovna());
        mesto.postavi(0, 18, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 3, new Tretja.Stanovanjska(86));
        mesto.postavi(10, 18, new Tretja.Stanovanjska(46));
        mesto.postavi(6, 9, new Tretja.Stanovanjska(68));
        mesto.postavi(6, 10, new Tretja.Stanovanjska(43));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 26, new Tretja.Stanovanjska(58));
        mesto.postavi(5, 4, new Tretja.Poslovna());
        mesto.postavi(6, 23, new Tretja.Stanovanjska(9));
        mesto.postavi(1, 5, new Tretja.Poslovna());
        mesto.postavi(9, 18, new Tretja.Stanovanjska(6));
        mesto.postavi(5, 25, new Tretja.Stanovanjska(16));
        mesto.postavi(14, 16, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 21, new Tretja.Poslovna());
        mesto.postavi(8, 5, new Tretja.Stanovanjska(33));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 2, new Tretja.Stanovanjska(55));
        mesto.postavi(14, 25, new Tretja.Poslovna());
        mesto.postavi(8, 17, new Tretja.Poslovna());
        mesto.postavi(2, 14, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(9));
        mesto.postavi(11, 19, new Tretja.Poslovna());
        mesto.postavi(11, 18, new Tretja.Poslovna());
        mesto.postavi(4, 10, new Tretja.Poslovna());
        mesto.postavi(8, 14, new Tretja.Stanovanjska(9));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 17, new Tretja.Stanovanjska(34));
        mesto.postavi(14, 9, new Tretja.Poslovna());
        mesto.postavi(3, 17, new Tretja.Stanovanjska(92));
        mesto.postavi(6, 8, new Tretja.Stanovanjska(6));
        mesto.postavi(7, 15, new Tretja.Poslovna());
        mesto.postavi(9, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 0, new Tretja.Stanovanjska(47));
        mesto.postavi(11, 14, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 21, new Tretja.Poslovna());
        mesto.postavi(6, 17, new Tretja.Stanovanjska(87));
        mesto.postavi(4, 18, new Tretja.Poslovna());
        mesto.postavi(1, 23, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 7, new Tretja.Stanovanjska(80));
        mesto.postavi(10, 4, new Tretja.Stanovanjska(97));
        mesto.postavi(12, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 21, new Tretja.Stanovanjska(86));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 17, new Tretja.Stanovanjska(40));
        mesto.postavi(2, 20, new Tretja.Stanovanjska(88));
        mesto.postavi(11, 7, new Tretja.Poslovna());
        mesto.postavi(3, 1, new Tretja.Poslovna());
        mesto.postavi(13, 4, new Tretja.Stanovanjska(44));
        mesto.postavi(0, 22, new Tretja.Poslovna());
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(13, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 10, new Tretja.Poslovna());
        mesto.postavi(5, 6, new Tretja.Stanovanjska(5));
        mesto.postavi(13, 6, new Tretja.Poslovna());
        mesto.postavi(7, 3, new Tretja.Stanovanjska(41));
        mesto.postavi(2, 6, new Tretja.Stanovanjska(95));
        mesto.postavi(11, 17, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(95));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 21, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 24, new Tretja.Poslovna());
        mesto.postavi(9, 6, new Tretja.Poslovna());
        mesto.postavi(2, 4, new Tretja.Stanovanjska(8));
        mesto.postavi(13, 25, new Tretja.Stanovanjska(77));
        mesto.postavi(8, 0, new Tretja.Stanovanjska(23));
        mesto.postavi(8, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 11, new Tretja.Poslovna());
        mesto.postavi(5, 21, new Tretja.Poslovna());
        mesto.postavi(12, 21, new Tretja.Stanovanjska(72));
        mesto.postavi(6, 11, new Tretja.Poslovna());
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(3, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 13, new Tretja.Stanovanjska(92));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 8, new Tretja.Stanovanjska(24));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 1, new Tretja.Poslovna());
        mesto.postavi(13, 23, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 2, new Tretja.Stanovanjska(63));
        mesto.postavi(1, 7, new Tretja.Poslovna());
        mesto.postavi(5, 26, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Poslovna());
        mesto.postavi(12, 2, new Tretja.Stanovanjska(6));
        mesto.postavi(1, 14, new Tretja.Poslovna());
        mesto.postavi(4, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 21, new Tretja.Poslovna());
        mesto.postavi(2, 15, new Tretja.Stanovanjska(89));
        mesto.postavi(0, 24, new Tretja.Stanovanjska(99));
        mesto.postavi(9, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 21, new Tretja.Stanovanjska(99));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 19, new Tretja.Stanovanjska(60));
        mesto.postavi(6, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 24, new Tretja.Poslovna());
        mesto.postavi(5, 9, new Tretja.Poslovna());
        mesto.postavi(14, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 6, new Tretja.Stanovanjska(30));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(4, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 13, new Tretja.Stanovanjska(28));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 1, new Tretja.Poslovna());
        mesto.postavi(1, 3, new Tretja.Poslovna());
        mesto.postavi(4, 26, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 9, new Tretja.Poslovna());
        mesto.postavi(5, 13, new Tretja.Stanovanjska(95));
        mesto.postavi(3, 25, new Tretja.Poslovna());
        mesto.postavi(12, 16, new Tretja.Poslovna());
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(11, 3, new Tretja.Poslovna());
        mesto.postavi(3, 14, new Tretja.Stanovanjska(42));
        mesto.postavi(6, 26, new Tretja.Poslovna());
        mesto.postavi(6, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 10, new Tretja.Stanovanjska(8));
        mesto.postavi(3, 8, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 5, new Tretja.Stanovanjska(76));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 4, new Tretja.Stanovanjska(4));
        mesto.postavi(11, 20, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 5, new Tretja.Stanovanjska(46));
        mesto.postavi(14, 20, new Tretja.Stanovanjska(24));
        mesto.postavi(7, 9, new Tretja.Poslovna());
        mesto.postavi(2, 26, new Tretja.Poslovna());
        mesto.postavi(13, 10, new Tretja.Poslovna());
        mesto.postavi(5, 2, new Tretja.Stanovanjska(32));
        mesto.postavi(4, 8, new Tretja.Poslovna());
        mesto.postavi(1, 16, new Tretja.Stanovanjska(90));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 19, new Tretja.Poslovna());
        mesto.postavi(4, 15, new Tretja.Stanovanjska(3));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 9, new Tretja.Stanovanjska(70));
        mesto.postavi(5, 10, new Tretja.Stanovanjska(46));
        mesto.postavi(13, 20, new Tretja.Poslovna());
        mesto.postavi(6, 14, new Tretja.Stanovanjska(45));
        mesto.postavi(5, 11, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 9, new Tretja.Stanovanjska(65));
        mesto.postavi(6, 15, new Tretja.Stanovanjska(98));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 10, new Tretja.Stanovanjska(68));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 7, new Tretja.Poslovna());
        mesto.postavi(3, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 25, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 0, new Tretja.Poslovna());
        mesto.postavi(9, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 7, new Tretja.Stanovanjska(26));
        mesto.postavi(9, 11, new Tretja.Stanovanjska(71));
        mesto.postavi(14, 19, new Tretja.Poslovna());
        mesto.postavi(11, 15, new Tretja.Stanovanjska(97));
        mesto.postavi(3, 26, new Tretja.Poslovna());
        mesto.postavi(11, 10, new Tretja.Poslovna());
        mesto.postavi(8, 4, new Tretja.Stanovanjska(8));
        mesto.postavi(3, 9, new Tretja.Poslovna());
        mesto.postavi(0, 15, new Tretja.Poslovna());
        mesto.postavi(10, 25, new Tretja.Poslovna());
        mesto.postavi(10, 5, new Tretja.Poslovna());
        mesto.postavi(0, 20, new Tretja.Stanovanjska(36));
        mesto.postavi(8, 18, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Stanovanjska(16));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(5));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 18, new Tretja.Poslovna());
        mesto.postavi(14, 14, new Tretja.Poslovna());
        mesto.postavi(3, 6, new Tretja.Stanovanjska(50));
        mesto.postavi(3, 7, new Tretja.Stanovanjska(13));
        mesto.postavi(12, 19, new Tretja.Poslovna());
        mesto.postavi(7, 14, new Tretja.Poslovna());
        mesto.postavi(8, 24, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 1, new Tretja.Stanovanjska(44));
        mesto.postavi(7, 8, new Tretja.Poslovna());
        mesto.postavi(2, 1, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Stanovanjska(76));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 14, new Tretja.Stanovanjska(6));
        mesto.postavi(5, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 2, new Tretja.Poslovna());
        mesto.postavi(13, 9, new Tretja.Poslovna());
        mesto.postavi(7, 24, new Tretja.Poslovna());
        mesto.postavi(6, 3, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(4, 20, new Tretja.Stanovanjska(15));
        mesto.postavi(2, 9, new Tretja.Stanovanjska(97));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Stanovanjska(80));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(27));
        mesto.postavi(7, 17, new Tretja.Poslovna());
        mesto.postavi(11, 11, new Tretja.Stanovanjska(9));
        mesto.postavi(13, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 15, new Tretja.Stanovanjska(7));
        mesto.postavi(14, 13, new Tretja.Poslovna());
        mesto.postavi(7, 21, new Tretja.Stanovanjska(6));
        mesto.postavi(1, 11, new Tretja.Stanovanjska(67));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
