
import java.util.*;

public class Test21 {

    public static void main(String[] args) {
        Tretja.Mesto mesto = new Tretja.Mesto(30, 26);

        mesto.postavi(12, 5, new Tretja.Stanovanjska(16));
        mesto.postavi(17, 8, new Tretja.Stanovanjska(45));
        mesto.postavi(24, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 19, new Tretja.Stanovanjska(56));
        mesto.postavi(28, 21, new Tretja.Stanovanjska(21));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 18, new Tretja.Poslovna());
        mesto.postavi(14, 23, new Tretja.Stanovanjska(92));
        mesto.postavi(24, 15, new Tretja.Stanovanjska(2));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(26, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 4, new Tretja.Stanovanjska(57));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(17, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 6, new Tretja.Stanovanjska(91));
        mesto.postavi(12, 11, new Tretja.Poslovna());
        mesto.postavi(27, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 1, new Tretja.Poslovna());
        mesto.postavi(8, 10, new Tretja.Stanovanjska(64));
        mesto.postavi(3, 9, new Tretja.Stanovanjska(100));
        mesto.postavi(8, 2, new Tretja.Stanovanjska(90));
        mesto.postavi(13, 9, new Tretja.Stanovanjska(9));
        mesto.postavi(18, 25, new Tretja.Poslovna());
        mesto.postavi(28, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 15, new Tretja.Stanovanjska(58));
        mesto.postavi(10, 8, new Tretja.Poslovna());
        mesto.postavi(26, 1, new Tretja.Stanovanjska(38));
        mesto.postavi(24, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(26, 6, new Tretja.Poslovna());
        mesto.postavi(29, 17, new Tretja.Stanovanjska(21));
        mesto.postavi(28, 18, new Tretja.Poslovna());
        mesto.postavi(17, 1, new Tretja.Stanovanjska(79));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 18, new Tretja.Poslovna());
        mesto.postavi(4, 16, new Tretja.Poslovna());
        mesto.postavi(14, 10, new Tretja.Poslovna());
        mesto.postavi(22, 10, new Tretja.Stanovanjska(97));
        mesto.postavi(15, 11, new Tretja.Stanovanjska(1));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 11, new Tretja.Stanovanjska(63));
        mesto.postavi(18, 16, new Tretja.Stanovanjska(47));
        mesto.postavi(6, 13, new Tretja.Poslovna());
        mesto.postavi(6, 4, new Tretja.Poslovna());
        mesto.postavi(23, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 6, new Tretja.Stanovanjska(23));
        mesto.postavi(4, 14, new Tretja.Stanovanjska(7));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(26, 4, new Tretja.Stanovanjska(49));
        mesto.postavi(15, 16, new Tretja.Stanovanjska(39));
        mesto.postavi(17, 20, new Tretja.Poslovna());
        mesto.postavi(28, 6, new Tretja.Poslovna());
        mesto.postavi(14, 3, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 21, new Tretja.Stanovanjska(11));
        mesto.postavi(11, 8, new Tretja.Poslovna());
        mesto.postavi(17, 12, new Tretja.Stanovanjska(55));
        mesto.postavi(12, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 16, new Tretja.Stanovanjska(51));
        mesto.postavi(6, 23, new Tretja.Stanovanjska(61));
        mesto.postavi(19, 2, new Tretja.Poslovna());
        mesto.postavi(15, 12, new Tretja.Poslovna());
        mesto.postavi(23, 10, new Tretja.Stanovanjska(37));
        mesto.postavi(4, 4, new Tretja.Stanovanjska(48));
        mesto.postavi(18, 8, new Tretja.Poslovna());
        mesto.postavi(26, 25, new Tretja.Stanovanjska(32));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 22, new Tretja.Stanovanjska(74));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 21, new Tretja.Stanovanjska(72));
        mesto.postavi(4, 11, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 14, new Tretja.Stanovanjska(13));
        mesto.postavi(15, 2, new Tretja.Stanovanjska(18));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 24, new Tretja.Poslovna());
        mesto.postavi(25, 6, new Tretja.Stanovanjska(63));
        mesto.postavi(1, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 14, new Tretja.Stanovanjska(70));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 10, new Tretja.Stanovanjska(7));
        mesto.postavi(7, 13, new Tretja.Poslovna());
        mesto.postavi(25, 10, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 4, new Tretja.Poslovna());
        mesto.postavi(29, 4, new Tretja.Poslovna());
        mesto.postavi(24, 7, new Tretja.Stanovanjska(70));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 0, new Tretja.Stanovanjska(87));
        mesto.postavi(3, 15, new Tretja.Stanovanjska(39));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 5, new Tretja.Poslovna());
        mesto.postavi(2, 10, new Tretja.Stanovanjska(83));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 20, new Tretja.Stanovanjska(50));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 25, new Tretja.Stanovanjska(3));
        mesto.postavi(28, 16, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 2, new Tretja.Poslovna());
        mesto.postavi(4, 5, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 18, new Tretja.Poslovna());
        mesto.postavi(1, 2, new Tretja.Stanovanjska(23));
        mesto.postavi(14, 16, new Tretja.Poslovna());
        mesto.postavi(1, 18, new Tretja.Poslovna());
        mesto.postavi(26, 17, new Tretja.Poslovna());
        mesto.postavi(10, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(26, 11, new Tretja.Stanovanjska(64));
        mesto.postavi(21, 18, new Tretja.Poslovna());
        mesto.postavi(23, 5, new Tretja.Poslovna());
        mesto.postavi(27, 23, new Tretja.Stanovanjska(52));
        mesto.postavi(27, 10, new Tretja.Poslovna());
        mesto.postavi(8, 19, new Tretja.Stanovanjska(46));
        mesto.postavi(23, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 12, new Tretja.Stanovanjska(25));
        mesto.postavi(10, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 16, new Tretja.Stanovanjska(7));
        mesto.postavi(1, 1, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 21, new Tretja.Poslovna());
        mesto.postavi(13, 14, new Tretja.Poslovna());
        mesto.postavi(14, 24, new Tretja.Poslovna());
        mesto.postavi(10, 2, new Tretja.Stanovanjska(52));
        mesto.postavi(13, 22, new Tretja.Stanovanjska(47));
        mesto.postavi(0, 11, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 16, new Tretja.Poslovna());
        mesto.postavi(14, 18, new Tretja.Poslovna());
        mesto.postavi(9, 9, new Tretja.Stanovanjska(21));
        mesto.postavi(11, 20, new Tretja.Poslovna());
        mesto.postavi(4, 17, new Tretja.Poslovna());
        mesto.postavi(6, 15, new Tretja.Poslovna());
        mesto.postavi(1, 17, new Tretja.Poslovna());
        mesto.postavi(21, 19, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 24, new Tretja.Poslovna());
        mesto.postavi(27, 25, new Tretja.Poslovna());
        mesto.postavi(1, 13, new Tretja.Poslovna());
        mesto.postavi(14, 17, new Tretja.Poslovna());
        mesto.postavi(16, 7, new Tretja.Stanovanjska(70));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 16, new Tretja.Stanovanjska(66));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(6, 21, new Tretja.Stanovanjska(47));
        mesto.postavi(1, 3, new Tretja.Stanovanjska(32));
        mesto.postavi(27, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 21, new Tretja.Stanovanjska(90));
        mesto.postavi(26, 0, new Tretja.Poslovna());
        mesto.postavi(24, 12, new Tretja.Stanovanjska(11));
        mesto.postavi(3, 14, new Tretja.Stanovanjska(85));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 15, new Tretja.Poslovna());
        mesto.postavi(13, 12, new Tretja.Stanovanjska(95));
        mesto.postavi(22, 21, new Tretja.Stanovanjska(66));
        mesto.postavi(12, 4, new Tretja.Stanovanjska(56));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 25, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 20, new Tretja.Stanovanjska(54));
        mesto.postavi(3, 5, new Tretja.Stanovanjska(71));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 6, new Tretja.Poslovna());
        mesto.postavi(28, 24, new Tretja.Stanovanjska(89));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 14, new Tretja.Poslovna());
        mesto.postavi(2, 25, new Tretja.Stanovanjska(56));
        mesto.postavi(2, 23, new Tretja.Stanovanjska(75));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 18, new Tretja.Poslovna());
        mesto.postavi(21, 0, new Tretja.Stanovanjska(96));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 13, new Tretja.Stanovanjska(25));
        mesto.postavi(15, 17, new Tretja.Stanovanjska(58));
        mesto.postavi(1, 6, new Tretja.Stanovanjska(69));
        mesto.postavi(10, 10, new Tretja.Stanovanjska(95));
        mesto.postavi(24, 5, new Tretja.Poslovna());
        mesto.postavi(27, 6, new Tretja.Stanovanjska(73));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 13, new Tretja.Poslovna());
        mesto.postavi(25, 20, new Tretja.Stanovanjska(37));
        mesto.postavi(6, 6, new Tretja.Poslovna());
        mesto.postavi(26, 7, new Tretja.Poslovna());
        mesto.postavi(14, 20, new Tretja.Stanovanjska(21));
        mesto.postavi(1, 15, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(2, 22, new Tretja.Poslovna());
        mesto.postavi(15, 5, new Tretja.Stanovanjska(14));
        mesto.postavi(20, 21, new Tretja.Stanovanjska(28));
        mesto.postavi(19, 4, new Tretja.Stanovanjska(63));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 24, new Tretja.Stanovanjska(80));
        mesto.postavi(2, 20, new Tretja.Poslovna());
        mesto.postavi(5, 7, new Tretja.Poslovna());
        mesto.postavi(1, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 4, new Tretja.Stanovanjska(46));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 1, new Tretja.Stanovanjska(82));
        mesto.postavi(27, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 15, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 6, new Tretja.Stanovanjska(24));
        mesto.postavi(18, 18, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(21, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 7, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 23, new Tretja.Stanovanjska(80));
        mesto.postavi(22, 8, new Tretja.Stanovanjska(80));
        mesto.postavi(7, 6, new Tretja.Stanovanjska(11));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(25, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 23, new Tretja.Poslovna());
        mesto.postavi(24, 4, new Tretja.Poslovna());
        mesto.postavi(9, 21, new Tretja.Stanovanjska(12));
        mesto.postavi(8, 23, new Tretja.Poslovna());
        mesto.postavi(23, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(22, 11, new Tretja.Stanovanjska(81));
        mesto.postavi(17, 6, new Tretja.Stanovanjska(76));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(28, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 10, new Tretja.Poslovna());
        mesto.postavi(0, 7, new Tretja.Poslovna());
        mesto.postavi(2, 2, new Tretja.Poslovna());
        mesto.postavi(22, 2, new Tretja.Stanovanjska(99));
        mesto.postavi(7, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 11, new Tretja.Poslovna());
        mesto.postavi(16, 24, new Tretja.Stanovanjska(64));
        mesto.postavi(19, 17, new Tretja.Stanovanjska(24));
        mesto.postavi(17, 18, new Tretja.Poslovna());
        mesto.postavi(29, 25, new Tretja.Stanovanjska(45));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 23, new Tretja.Poslovna());
        mesto.postavi(3, 25, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(23, 0, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(14, 8, new Tretja.Stanovanjska(17));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(5, 3, new Tretja.Poslovna());
        mesto.postavi(6, 20, new Tretja.Stanovanjska(8));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 9, new Tretja.Poslovna());
        mesto.postavi(10, 21, new Tretja.Poslovna());
        mesto.postavi(25, 24, new Tretja.Poslovna());
        mesto.postavi(23, 8, new Tretja.Poslovna());
        mesto.postavi(6, 19, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 21, new Tretja.Poslovna());
        mesto.postavi(6, 2, new Tretja.Poslovna());
        mesto.postavi(0, 5, new Tretja.Poslovna());
        mesto.postavi(21, 20, new Tretja.Stanovanjska(49));
        mesto.postavi(6, 1, new Tretja.Poslovna());
        mesto.postavi(4, 7, new Tretja.Stanovanjska(83));
        mesto.postavi(2, 4, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(12, 10, new Tretja.Poslovna());
        mesto.postavi(22, 12, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 24, new Tretja.Stanovanjska(43));
        mesto.postavi(9, 18, new Tretja.Poslovna());
        mesto.postavi(15, 25, new Tretja.Poslovna());
        mesto.postavi(14, 5, new Tretja.Stanovanjska(93));
        mesto.postavi(29, 2, new Tretja.Stanovanjska(37));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 14, new Tretja.Poslovna());
        mesto.postavi(3, 2, new Tretja.Stanovanjska(1));
        mesto.postavi(18, 9, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(27, 15, new Tretja.Stanovanjska(65));
        mesto.postavi(2, 5, new Tretja.Stanovanjska(25));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 8, new Tretja.Stanovanjska(82));
        mesto.postavi(9, 1, new Tretja.Poslovna());
        mesto.postavi(27, 12, new Tretja.Poslovna());
        mesto.postavi(6, 25, new Tretja.Poslovna());
        mesto.postavi(27, 13, new Tretja.Stanovanjska(47));
        mesto.postavi(28, 10, new Tretja.Poslovna());
        mesto.postavi(20, 22, new Tretja.Stanovanjska(95));
        mesto.postavi(29, 7, new Tretja.Stanovanjska(42));
        mesto.postavi(7, 7, new Tretja.Poslovna());
        mesto.postavi(12, 0, new Tretja.Stanovanjska(67));
        mesto.postavi(0, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(29, 3, new Tretja.Stanovanjska(72));
        mesto.postavi(24, 20, new Tretja.Poslovna());
        mesto.postavi(14, 1, new Tretja.Stanovanjska(23));
        mesto.postavi(22, 25, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(9, 15, new Tretja.Stanovanjska(46));
        mesto.postavi(8, 11, new Tretja.Poslovna());
        mesto.postavi(1, 10, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(11, 22, new Tretja.Stanovanjska(85));
        mesto.postavi(0, 0, new Tretja.Stanovanjska(54));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(3, 20, new Tretja.Poslovna());
        mesto.postavi(6, 7, new Tretja.Poslovna());
        mesto.postavi(0, 6, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 23, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 18, new Tretja.Stanovanjska(63));
        mesto.postavi(5, 0, new Tretja.Stanovanjska(31));
        mesto.postavi(28, 5, new Tretja.Stanovanjska(47));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 8, new Tretja.Stanovanjska(22));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(8, 22, new Tretja.Poslovna());
        mesto.postavi(28, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 11, new Tretja.Poslovna());
        mesto.postavi(13, 13, new Tretja.Stanovanjska(55));
        mesto.postavi(24, 17, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 25, new Tretja.Stanovanjska(43));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(13, 19, new Tretja.Poslovna());
        mesto.postavi(19, 24, new Tretja.Stanovanjska(67));
        mesto.postavi(29, 0, new Tretja.Stanovanjska(10));
        mesto.postavi(26, 14, new Tretja.Stanovanjska(34));
        mesto.postavi(13, 15, new Tretja.Stanovanjska(87));
        mesto.postavi(13, 17, new Tretja.Poslovna());
        mesto.postavi(0, 22, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(0, 21, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 12, new Tretja.Poslovna());
        mesto.postavi(6, 18, new Tretja.Stanovanjska(69));
        mesto.postavi(8, 8, new Tretja.Stanovanjska(39));
        mesto.postavi(21, 8, new Tretja.Stanovanjska(11));
        mesto.postavi(17, 25, new Tretja.Stanovanjska(27));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 1, new Tretja.Poslovna());
        mesto.postavi(15, 23, new Tretja.Poslovna());
        mesto.postavi(26, 13, new Tretja.Poslovna());
        mesto.postavi(15, 15, new Tretja.Stanovanjska(78));
        mesto.postavi(12, 24, new Tretja.Stanovanjska(82));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(7, 23, new Tretja.Poslovna());
        mesto.postavi(18, 4, new Tretja.Stanovanjska(90));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(16, 22, new Tretja.Poslovna());
        mesto.postavi(2, 13, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 3, new Tretja.Stanovanjska(6));
        mesto.postavi(26, 9, new Tretja.Stanovanjska(69));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(10, 7, new Tretja.Poslovna());
        mesto.postavi(9, 12, new Tretja.Stanovanjska(99));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(4, 18, new Tretja.Stanovanjska(49));
        mesto.postavi(28, 2, new Tretja.Stanovanjska(26));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 0, new Tretja.Stanovanjska(89));
        mesto.postavi(7, 3, new Tretja.Stanovanjska(64));
        mesto.postavi(26, 8, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(19, 25, new Tretja.Stanovanjska(12));
        mesto.postavi(27, 4, new Tretja.Poslovna());
        mesto.postavi(2, 7, new Tretja.Stanovanjska(6));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(1, 21, new Tretja.Stanovanjska(23));
        mesto.postavi(8, 15, new Tretja.Poslovna());
        mesto.postavi(11, 14, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(24, 14, new Tretja.Stanovanjska(9));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(18, 3, new Tretja.Stanovanjska(97));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 25, new Tretja.Stanovanjska(22));
        mesto.postavi(0, 12, new Tretja.Stanovanjska(33));
        mesto.postavi(4, 21, new Tretja.Poslovna());
        mesto.postavi(26, 2, new Tretja.Poslovna());
        mesto.postavi(7, 4, new Tretja.Stanovanjska(55));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 24, new Tretja.Poslovna());
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(20, 18, new Tretja.Poslovna());
        mesto.postavi(3, 11, new Tretja.Stanovanjska(12));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
        mesto.postavi(15, 3, new Tretja.Poslovna());
        mesto.postavi(28, 4, new Tretja.Stanovanjska(63));
        System.out.println(mesto.koliko(new Tretja.Stanovanjska(0)));
        System.out.println(mesto.koliko(new Tretja.Poslovna()));
    }
}
