<GGGGGGGGGGGGGGGGGGGRRRKKKKKKKKKKKKKKKKKKiiiiiiiiyyyyyuuuuuuuuuuuuuuuuuullllllllEEEEEEEEEEEEEEEEEEz6622222222222222WWWCCCCCCCUUUUUUUUUUUUUUUUUUUssssssssssssssssiiiiooovvvvvvvvvvvvQQQQQ>
<2222222ssssssssssssssssssyyyyyyyyRRRRRRRRRaaagggggggggggwwwwwwwwwwwwwPPPP_______________DDDIIIIIIIIIIIIIIIIIIgggggggggggggyyyyyyyyyyBBBBBBBBBmmmmmmmmmmmmmmmmmmmk66666_____________fffffffffff>
