<kkkkkkKKKKKKKKGGGGGGGGGkkkkkkkkkkkkkk4444444444444444gggggggggggggggHHHHHHHHHHHHHHHHHHHHggggggggggggggggglllllmmmmmmmmmmmmmmmmmmmmiiiiiihhhhhhhhhhhhhhhbbccccccccYYLLLLLLL>
<ZZZZZZZZZZZZZZZZ_______________MMMMMMMMMMMMMMaaaaassssssssssssssssssssmmmmmmmmmmmmmmmmmlllllllNNNNNNNNNNNNNNNNGGGnnnnnnnnnnnggggggggggggggggggHHHHHHHHHHZZZZZZZZZZZQQQQQQQ00NNNNNNNNNN>
