cbac|cccc|da|aba|da|morda
ba|ccc|ne|abbbc|da|ne
acc|ccc|ne|ab|da|morda
aacb|ccbcb|ne|ab|da|morda
c|ccbc|ne|bcabb|da|da
aa|ccb|da|bbb|morda|da
babc|ccab|da|ccabc|da|ne
bbac|cc|da|bc|morda|morda
a|cc|morda|aacac|ne|ne
ac|cbcba|da|b|morda|da
aca|cbcb|ne|b|morda|ne
bbb|cbcb|morda|baba|ne|ne
acaaa|cbbcb|morda|ba|morda|da
abccc|cbbb|ne|abaaa|morda|da
c|cbbac|da|cbbcc|morda|da
b|cbb|da|ca|da|ne
ba|cbabc|morda|a|da|morda
ba|cbaa|da|bbaa|da|da
ab|cba|morda|a|morda|ne
baac|cb|da|ab|morda|ne
abcbc|cb|morda|ac|morda|morda
aacbc|cb|ne|ccb|da|morda
cc|cacbc|da|cc|da|morda
abbb|cacb|da|a|ne|da
b|cacab|morda|a|da|da
ccbc|cabc|morda|cbb|da|ne
baccc|cab|da|a|ne|ne
ccc|caaac|da|abbcc|ne|morda
bcb|ca|da|cccab|da|da
b|ca|morda|bbb|morda|da
c|ca|da|abaa|ne|da
c|ca|ne|bc|ne|da
acac|c|da|caa|morda|morda
bcaab|c|ne|aabba|da|da
ac|c|ne|ca|ne|ne
bca|c|da|abc|ne|ne
ca|c|da|bca|ne|ne
ccbb|c|morda|aac|ne|da
b|c|morda|cacb|morda|da
cb|c|ne|aa|da|ne
ba|c|ne|b|da|morda
babac|c|da|bca|ne|da
b|c|morda|b|ne|morda
abc|c|ne|cbcb|ne|morda
cbb|bccc|morda|ba|da|ne
abc|bccac|morda|cacbc|da|ne
cba|bcca|da|ccb|morda|morda
babbc|bcbb|morda|bccbb|da|ne
bcaa|bcb|da|b|da|ne
bccc|bcb|morda|cc|morda|ne
aabcc|bca|ne|acc|morda|da
bab|bca|morda|abc|morda|ne
bbbac|bca|ne|bb|ne|da
ba|bc|ne|ca|morda|ne
ccbcb|bc|ne|babc|da|ne
baa|bbcc|morda|c|da|ne
b|bbcbc|morda|ccbb|morda|ne
cabab|bbcb|da|cab|morda|ne
cc|bbca|da|acacb|ne|da
bbcb|bbc|ne|ab|morda|da
ac|bbc|da|cbcba|ne|morda
bb|bbc|da|abaaa|morda|morda
a|bbbca|ne|caa|morda|da
ca|bbbca|morda|a|da|da
abaa|bbb|morda|aabcb|ne|da
cca|bbacb|morda|bbbb|morda|morda
bcb|bbacb|da|cc|ne|morda
a|bbacb|ne|ccb|ne|da
ca|bbacb|ne|b|morda|morda
c|bba|ne|a|morda|morda
cab|bba|ne|bb|da|da
c|bb|da|bb|ne|da
acc|bb|ne|a|da|ne
bab|baccc|morda|bbbb|morda|morda
ccac|baca|ne|acb|ne|ne
cbcab|baacb|morda|bc|morda|ne
bcc|baac|da|bac|ne|da
bb|baaaa|morda|abaaa|morda|morda
bbb|baaa|ne|aaca|da|ne
bacb|ba|ne|c|ne|da
ac|ba|da|bb|da|morda
ccc|ba|da|aca|ne|morda
babbb|b|morda|b|morda|morda
ccbca|b|da|bcbcb|morda|morda
cacab|acbb|da|ccabb|ne|morda
c|acaba|ne|ac|da|morda
cb|ac|da|bbcc|morda|ne
bccaa|ac|da|baaaa|da|morda
abcc|ac|morda|bbccc|da|ne
bba|ac|morda|ba|ne|ne
bacb|ac|ne|cb|da|da
a|abcc|morda|a|morda|morda
cbcb|abcac|morda|cbc|morda|da
cbb|abc|da|caab|morda|ne
cbb|abb|da|bbbb|da|morda
bccbc|abaca|ne|bbab|da|da
bac|abaaa|morda|b|ne|morda
a|aba|morda|c|ne|da
b|ab|ne|bab|ne|da
ca|ab|ne|c|da|morda
ba|ab|da|ba|da|morda
ba|aaccc|ne|babba|morda|ne
a|aac|morda|bbaaa|morda|da
ba|aac|ne|c|ne|da
abab|aabbc|morda|accba|morda|da
a|aabbc|da|bbac|ne|morda
a|aabba|ne|ba|morda|ne
c|aabab|da|acc|ne|morda
cbbc|aab|morda|bba|ne|da
b|aaacc|morda|acc|da|ne
aaca|aaac|ne|c|ne|da
ccc|aaa|morda|a|da|morda
bc|aa|morda|ca|da|da
bcb|aa|morda|b|ne|da
ca|a|morda|c|ne|morda
cc|a|ne|bbbca|ne|ne
bbcbc|a|da|cbcbc|ne|ne
bcacb|a|da|bacbc|ne|da
abcc|a|da|aabb|da|morda
aca|a|morda|cbc|da|da
c|a|da|cbbcb|da|ne
