ne|abc|a|ab|morda|acab|ne|b|ca|morda
da|acb|a|cbcb|da|bbaaa|morda|ab|bb|da
da|caab|a|aa|ne|ccab|ne|bc|ba|da
ne|c|a|acb|da|ccab|da|b|bca|morda
morda|a|a|cc|morda|cb|ne|bbaa|bccac|ne
morda|ac|a|c|da|cbbac|da|a|aac|ne
ne|bcb|a|b|morda|aa|da|aacaa|bbccb|ne
morda|ccc|a|bab|morda|bb|da|ca|a|morda
morda|babac|a|b|da|bbb|morda|a|cc|da
morda|aa|a|a|ne|c|ne|accc|ca|da
morda|a|a|a|ne|bab|ne|acba|ccc|morda
ne|baaaa|a|aa|morda|bb|morda|cacab|aca|da
da|a|a|bccc|da|baa|da|aabb|bcccc|ne
da|bbbb|a|b|da|cbb|morda|ccc|bcca|da
ne|a|a|cbcb|da|bcbca|da|bcb|bcb|da
ne|cacc|a|c|morda|babca|ne|b|cc|da
morda|ac|a|ccb|da|bcab|da|ca|cc|ne
da|c|a|bb|morda|bb|morda|bcccc|babc|da
da|cba|a|bcab|morda|bba|da|aaa|cbcb|da
ne|cbabb|a|b|da|cacb|da|c|babac|da
ne|ccccb|a|b|morda|bba|da|c|bbaac|da
morda|caac|a|b|da|ccac|ne|abb|ccb|morda
da|bcabb|a|ba|ne|bbaaa|da|aa|ac|da
da|acba|a|acb|ne|accc|morda|a|ac|ne
morda|caab|a|b|ne|ca|da|abcbc|bccbb|ne
da|ccb|a|aaa|ne|bcc|morda|acc|cc|da
morda|abc|a|aaca|morda|b|da|bb|cbaca|ne
morda|bccac|a|bb|morda|acc|ne|aaa|aab|ne
da|cb|a|b|ne|ab|da|acc|ab|morda
da|cbcb|a|c|morda|bcb|da|ca|babbb|morda
morda|bcac|a|aa|morda|aacba|morda|cbbca|c|da
morda|acaab|a|abb|ne|a|da|b|a|morda
ne|cbc|a|baab|morda|b|morda|bb|bac|da
ne|aabab|a|ac|da|b|ne|bbcbc|b|morda
da|c|a|bcc|da|cc|morda|b|caba|da
morda|a|aa|bbcb|morda|bcb|morda|bcb|acb|ne
ne|ccc|aa|cacca|ne|ac|da|ca|bb|ne
da|acac|aa|ba|ne|bcbcc|da|c|ac|morda
ne|ccabb|aa|a|morda|bbcac|ne|bcab|b|ne
ne|ccbca|aa|cb|morda|ababa|ne|bbc|ac|morda
morda|bbab|aa|bcb|ne|bcb|morda|a|c|da
da|cbcbc|aa|c|da|cc|morda|bcaa|a|morda
da|c|aa|ba|da|bac|ne|a|cca|ne
ne|aca|aa|aacbc|da|aabac|da|ccb|c|morda
morda|aaabc|aa|ac|ne|bc|morda|ba|c|morda
da|c|aa|a|da|bab|ne|bc|cacab|morda
ne|aacbc|aa|baa|morda|a|ne|cbbac|abc|morda
ne|cbc|aaa|c|morda|bcb|da|ba|bbc|da
da|b|aaa|aaa|da|ba|morda|ab|baab|morda
morda|cbcbc|aaac|bc|da|cba|morda|ca|aacca|morda
morda|ccba|aaac|c|da|caab|da|bbab|cc|ne
ne|bccc|aaaca|bbbaa|ne|ccccb|morda|aba|c|morda
morda|cac|aabab|aa|ne|cab|da|c|cbcb|morda
da|abc|aabac|c|ne|bbbc|ne|ca|cbcb|da
morda|cc|aabb|ab|morda|ccac|da|babb|b|da
morda|aac|aabb|caabb|morda|ca|morda|aba|cbbca|da
morda|cbbcc|aabb|c|da|aaa|ne|babcc|acc|da
morda|aabb|aabba|a|da|ca|da|c|aaac|ne
morda|abca|aac|b|ne|b|da|abaa|cac|morda
morda|bbcc|aac|c|morda|ab|da|bc|bbb|morda
da|cbaa|aaca|ccab|da|a|morda|aca|ac|da
morda|c|aacac|aacb|ne|cc|ne|b|acba|da
morda|abaca|aacac|abcb|morda|ccbcb|ne|cbcbc|cbc|morda
morda|ccaba|aacb|bb|da|bbbb|ne|abcb|aacaa|ne
da|cac|aacb|baabb|ne|b|morda|bacc|acb|morda
morda|c|aacbc|aacaa|morda|abc|morda|abc|b|morda
da|ba|aaccb|c|ne|bc|ne|cb|aacc|morda
morda|cc|ab|bbbb|ne|bac|morda|b|ca|morda
morda|bacaa|ab|ab|morda|cabc|ne|ac|cac|ne
ne|ccac|ab|aaa|ne|cbca|morda|a|aa|morda
morda|ccbc|ab|cbc|da|abba|morda|b|ca|da
da|a|ab|bcb|ne|baaaa|morda|aaa|ca|da
morda|ba|ab|bcbc|morda|cca|ne|aaacc|abaa|da
ne|cca|ab|bbb|da|bcca|ne|abaa|cbc|da
ne|b|ab|ccbca|ne|bbca|da|abaaa|ab|da
da|babca|ab|c|morda|aaabb|ne|acc|bba|ne
ne|bccaa|ab|baa|da|cbc|da|ccba|bab|morda
ne|bc|ab|acbca|ne|bbcb|ne|b|bb|da
ne|c|ab|aaaca|morda|b|morda|c|ba|morda
morda|bb|ab|ba|da|bbccb|morda|ccac|bcb|da
da|abcbc|ab|c|ne|bcaa|morda|abbbb|cc|da
da|c|ab|bab|morda|ccbaa|ne|a|caa|da
da|acac|abaa|aac|da|baa|morda|cbac|bbbcc|ne
morda|bac|abaa|bacba|morda|cabab|morda|ccabc|aabb|morda
da|aaac|abaa|bb|ne|cc|ne|acc|aacba|morda
morda|bbaac|abaaa|aca|da|bcb|morda|aabbb|aaa|ne
da|ccbcb|ababa|bab|da|b|morda|aa|baccc|ne
morda|ccccc|ababc|c|da|ccabc|ne|bb|cacc|da
da|cbc|abaca|abcbb|ne|ccaba|da|b|bba|da
ne|c|abb|bbaac|morda|c|ne|a|aca|ne
ne|ca|abb|bc|ne|a|ne|cba|aa|ne
da|cbbcb|abba|a|da|bbcac|da|ab|bcbc|da
da|c|abbb|a|da|c|da|b|abac|morda
da|ca|abbc|c|da|cacb|ne|caab|aacca|da
ne|aaca|abbcb|c|morda|ccaa|morda|cc|ba|morda
da|aabc|abc|ac|ne|c|morda|abc|c|morda
da|ca|abc|aabbb|da|baab|morda|bbaa|bc|da
da|c|abc|ab|da|bacc|morda|cca|cc|ne
da|cbca|abca|ba|ne|a|da|ac|cab|ne
morda|cba|abcbc|bb|morda|bb|morda|bb|cab|da
da|a|abcc|baba|da|aabcc|da|bc|ccaa|morda
morda|cbcb|ac|ccaba|morda|ca|morda|bbac|ababa|ne
da|c|ac|a|morda|ba|da|ba|bcb|da
da|cbc|ac|aba|morda|b|da|bccc|ababa|da
ne|c|ac|cbcbc|da|b|ne|ac|ac|da
ne|ac|aca|c|morda|cbcb|morda|a|c|ne
morda|bcbcc|acaba|caab|morda|aaacc|da|bbccc|ca|ne
da|aac|acabc|acb|ne|ca|morda|abaaa|ab|morda
da|acaba|acabc|bccbb|ne|bbaa|da|baa|bb|da
da|aaa|acac|aac|da|bba|ne|bcbcc|bbcb|ne
ne|cabc|acac|abaca|ne|a|da|bbab|abbcc|da
da|c|acb|c|da|bb|ne|b|bab|morda
morda|ba|acb|caa|da|acb|ne|bbcac|bba|morda
ne|b|acb|cbcba|da|c|morda|ccbb|cb|da
ne|cccbb|acb|ccabc|morda|abcbb|morda|cabc|a|morda
da|a|acb|c|ne|c|ne|acac|cbcb|da
da|ccab|acb|b|morda|bccbc|ne|a|b|morda
da|cbcba|acbca|cbaca|morda|abbcb|morda|cbc|a|da
morda|acabc|acc|ccb|da|ccbca|morda|cbb|cac|da
morda|ccc|acc|aacca|morda|c|da|ccb|bccba|morda
da|aacb|acc|cacb|da|baab|morda|bbbc|cabab|ne
da|ababa|acca|cab|da|ca|morda|c|bb|ne
morda|bbbb|accb|c|da|bbcb|da|babac|ba|da
morda|baaaa|accba|cab|ne|ab|da|a|b|ne
da|cbbca|accbc|c|da|abc|ne|ca|cccc|da
ne|ba|accc|aba|morda|cbaa|morda|bccaa|a|da
ne|b|accc|aac|da|c|ne|a|b|morda
morda|aca|b|ba|morda|b|morda|ba|bcaab|ne
ne|bc|b|b|ne|c|morda|ab|cb|da
da|abcac|b|cb|morda|aaab|ne|b|bbcb|ne
ne|aac|b|b|da|bc|ne|baaaa|cbc|ne
ne|bb|b|abcc|ne|acb|morda|c|abc|morda
morda|cab|b|ac|da|aab|ne|b|b|ne
da|bba|b|bcca|morda|accc|morda|abaca|ccaa|ne
morda|bcb|b|bcc|ne|bac|da|bbccc|c|ne
morda|caab|b|bbcac|morda|bc|ne|ccc|ba|da
ne|bbc|b|ba|morda|abcac|morda|bbcbb|ccaa|ne
da|aa|b|ab|da|cbab|morda|bcbcb|b|morda
da|a|b|cbabc|da|aaabc|da|bbcc|abbb|morda
da|bc|b|b|morda|ca|morda|b|c|da
ne|bbbb|b|cb|da|aa|da|ab|a|morda
da|a|b|ccab|da|b|da|cc|b|ne
ne|ca|b|c|ne|c|morda|cbaca|acb|da
morda|caa|b|aaa|ne|abb|da|abb|ca|ne
da|ba|b|ca|morda|ba|morda|bbbaa|abcc|ne
ne|ba|ba|bcba|morda|bbbba|ne|aabb|ccccb|morda
da|bb|ba|bcc|da|cbbac|morda|bcbca|c|da
da|bbaaa|ba|bba|da|bc|ne|bbab|aba|ne
morda|b|ba|aaa|ne|acb|morda|baba|a|ne
ne|c|ba|cab|ne|baacb|ne|baac|a|morda
ne|b|ba|a|morda|c|morda|b|bcb|da
morda|ca|ba|bbc|ne|bbbca|ne|a|aaabc|morda
ne|cb|ba|ccb|da|babca|morda|accbc|a|da
morda|aac|ba|ca|ne|bb|morda|b|a|ne
da|aaacc|baaa|baa|morda|acb|morda|baab|c|morda
ne|bc|baaaa|ac|da|bcc|ne|b|bbaac|ne
da|bbbc|baaaa|bbaac|ne|cbb|morda|cbaac|babb|morda
morda|bcaa|baac|bacba|ne|aa|da|abcac|accba|da
da|acacb|baacb|acc|morda|c|da|aa|aa|morda
da|baba|baba|baaaa|ne|cb|morda|bb|a|ne
da|baaaa|babaa|cab|da|cba|morda|aacac|aaa|da
da|b|babaa|acb|da|c|morda|ba|ccc|da
morda|bbaac|babaa|abb|da|cabc|morda|b|aabb|da
morda|b|babac|ab|morda|baaaa|da|acaab|cc|morda
da|babba|babac|acb|da|ca|da|cbc|baaa|ne
ne|cb|babb|aca|morda|baab|morda|a|c|ne
da|a|babba|bbbca|ne|cab|ne|aabcb|cab|ne
ne|babc|babba|b|morda|babcb|morda|cc|aac|da
da|cca|babc|acc|ne|b|morda|ca|baacb|ne
da|bbb|babca|ca|morda|cbcb|morda|bc|bcbcb|da
morda|bab|babcc|cbb|morda|bb|morda|bcab|baaaa|ne
ne|bbc|baca|cbcba|morda|bc|morda|bc|ca|morda
da|bbb|bacbc|caa|da|a|da|bcaa|accba|ne
morda|cb|baccb|bacb|da|ab|ne|bccbb|a|morda
morda|c|baccb|ca|morda|b|da|baaaa|bbaa|da
da|bca|baccc|b|ne|bacc|da|cb|bc|morda
da|ac|bb|cc|ne|cc|da|abc|a|ne
morda|ccbaa|bb|bcb|morda|a|da|ac|aa|da
morda|bccba|bb|ac|morda|cbbca|da|aac|ccac|ne
morda|ba|bb|cbac|morda|bccbb|ne|bcbcb|abc|da
da|cbcb|bb|ba|da|bb|da|accc|bcb|ne
da|ca|bb|bc|da|b|morda|aca|caabb|da
ne|caabb|bb|bc|da|cca|ne|b|b|morda
morda|aa|bb|abc|morda|abcb|da|aaabb|ac|da
morda|bbab|bb|acb|da|ba|da|baccc|bccac|da
da|cb|bb|ba|da|bcca|morda|bcaba|b|da
morda|cbac|bb|bb|ne|c|da|baaa|cbca|morda
morda|aaca|bb|a|morda|caa|ne|cbcbc|ac|morda
da|aa|bb|bbb|morda|b|da|cacc|aa|ne
morda|baaca|bb|c|morda|acc|morda|bbaca|ba|ne
da|cbbcb|bb|b|da|bc|ne|aaa|c|morda
da|baaca|bba|babac|ne|cb|ne|c|ccc|ne
ne|c|bba|b|ne|acaba|da|aa|ac|morda
morda|abcbb|bbaa|ac|ne|b|da|c|cb|ne
ne|c|bbaaa|c|da|bb|da|b|cb|da
da|ac|bbaac|babc|da|bcbbb|da|bbca|c|da
da|ca|bbab|bba|morda|bccc|morda|bbcbc|abbbc|da
morda|cacc|bbab|acaba|ne|ab|ne|cbac|bbc|da
ne|abaca|bbac|b|da|abccc|da|bb|bacba|morda
da|c|bbac|ca|morda|c|morda|a|ca|da
morda|bcca|bbaca|aaacc|morda|ccba|morda|baa|c|da
morda|cc|bbacb|baccb|morda|bcabb|ne|cabb|b|ne
ne|aabba|bbb|ba|morda|ccb|ne|b|bcb|ne
da|baaa|bbb|aac|morda|bcbc|da|ccccc|ccba|morda
da|abbc|bbb|acca|morda|abba|ne|ab|bc|ne
ne|bbbca|bbbaa|bb|da|bbccb|ne|ba|bb|da
morda|ac|bbbb|acac|da|aabb|ne|b|b|morda
ne|ccbb|bbbca|a|da|accba|da|bc|cc|morda
morda|abc|bbbcc|a|da|ccbc|da|bacc|acb|da
da|cbb|bbc|ccb|ne|babc|morda|ccbcb|ba|morda
ne|bcbca|bbc|aa|morda|bbcc|ne|bccba|bcb|da
da|a|bbc|bbcac|da|bbabc|ne|bcaa|accc|ne
ne|bbccc|bbc|bbbb|da|ccbb|ne|c|acb|morda
ne|bbb|bbc|a|morda|ca|morda|a|caaa|morda
da|bc|bbc|cccab|da|bba|ne|ccbb|cca|morda
ne|bb|bbc|a|da|c|ne|abcbc|caa|morda
ne|ba|bbcac|ab|morda|abc|morda|aa|b|morda
morda|a|bbcb|acabc|ne|cb|da|ab|cbcab|da
ne|bca|bbcbc|bbc|morda|acac|morda|bb|cbac|da
da|bbaa|bbcbc|abc|morda|bccaa|da|bc|babbb|ne
ne|abbbb|bbcc|c|morda|bacbc|da|a|b|ne
ne|abcb|bbccc|aabba|da|c|da|c|b|ne
ne|bab|bbccc|cbca|morda|ac|morda|acbc|cbcba|ne
ne|cc|bc|ac|morda|bbbaa|morda|aca|cbabc|ne
morda|aa|bc|abb|ne|bbb|ne|abb|abbc|ne
da|b|bc|bccac|morda|bba|morda|bbb|ca|ne
ne|c|bc|ca|morda|acac|morda|cabc|c|ne
morda|bbb|bc|bb|ne|caab|morda|b|bcc|ne
da|cb|bc|ccab|da|bab|da|c|abac|da
da|bbbb|bc|bcca|morda|aaa|morda|cb|cbaa|ne
morda|cba|bc|aabb|ne|aabbb|morda|cabbc|cbcba|morda
ne|bc|bc|acc|da|ba|da|a|cb|morda
ne|ab|bca|ac|da|aca|morda|abc|bac|da
morda|ac|bca|b|morda|b|ne|b|cab|da
morda|b|bca|bbccb|morda|ab|ne|caa|a|da
ne|baaab|bcaa|ccccb|ne|bbb|morda|c|abc|da
da|bb|bcab|ab|da|baabb|morda|cbca|bcb|morda
da|ab|bcab|baaba|ne|aacac|ne|bbccb|ac|ne
morda|ccab|bcac|ca|da|bbbc|morda|aaa|a|da
da|a|bcacb|a|morda|bbcb|morda|acb|ccabc|ne
da|bba|bcb|abb|da|ab|morda|cbbcb|aabba|morda
ne|cbc|bcba|aacba|morda|c|da|ca|aaa|ne
da|bbccc|bcbb|ccc|da|abbb|da|ba|babbb|ne
da|abcc|bcbbb|bbb|ne|cbc|morda|bbc|bcbcc|morda
ne|a|bcbc|bc|da|cabac|morda|aac|cab|morda
ne|bba|bcbc|b|da|baa|ne|cbbc|baa|ne
ne|bcca|bcc|ab|da|caaba|ne|baab|cb|morda
morda|bbb|bcc|aa|ne|bab|morda|a|cacb|morda
da|bcb|bcca|ba|morda|cab|da|ca|cb|da
ne|a|bcca|aa|ne|bca|morda|ccb|bcbaa|da
da|caaa|bcca|ccac|da|bcba|ne|babbb|cca|da
ne|bbabc|bcca|cbc|da|ba|morda|a|bb|ne
da|c|bcca|acba|morda|ccac|ne|b|cbac|ne
ne|cabc|bccbb|ababc|morda|aac|morda|bb|b|morda
da|c|bccbc|babaa|ne|bbaa|morda|abc|cbabb|ne
ne|bbb|bccbc|bbc|morda|a|morda|ccbca|ccab|morda
ne|bba|bccca|c|da|ccbc|ne|c|ac|da
morda|bccc|bccca|b|morda|a|morda|aa|bbbb|da
ne|aac|bcccb|c|ne|caac|morda|a|ab|da
morda|bac|bcccb|bcbbb|ne|bc|morda|acaac|c|ne
ne|acca|bcccc|bccbc|ne|b|morda|bac|ac|morda
morda|bc|bcccc|baa|da|bbabc|da|a|ab|ne
ne|b|c|abbbb|da|b|morda|b|babac|da
da|babbb|c|cb|ne|a|da|aa|c|da
da|cccc|c|b|morda|cca|da|b|bcaba|morda
ne|bbaa|c|abac|ne|ca|ne|bccc|aa|da
da|ac|c|b|morda|caaac|morda|ab|ba|da
da|cbac|c|c|morda|acbb|morda|babba|aa|morda
ne|abcbc|c|bac|ne|baba|da|abac|bac|ne
morda|ca|c|ac|da|aca|morda|ba|acaab|ne
ne|aba|c|a|ne|aaa|morda|bbaa|ccc|ne
da|cbac|c|aabc|da|a|da|bc|cb|morda
morda|ccc|c|a|morda|ca|ne|c|ca|ne
da|cbcbc|c|b|da|baaaa|ne|bba|bcb|morda
ne|bca|c|cba|morda|cbc|ne|bbaac|c|morda
da|aba|c|b|morda|bbbac|ne|bcca|a|ne
morda|caa|c|ba|ne|bbc|ne|bb|bbbcc|da
morda|abaaa|ca|b|morda|baaca|ne|aaacc|b|morda
ne|cbcbc|ca|a|morda|abc|ne|acb|bbbca|ne
da|ca|ca|bbc|da|b|da|ca|acbca|da
da|ba|ca|cb|da|aa|da|b|bcbc|ne
da|abcac|ca|a|ne|bbc|morda|bccbc|accbc|morda
morda|bb|ca|abc|da|bbc|da|ba|bacc|morda
ne|abbcc|ca|abcac|da|caa|ne|acbca|cbbca|da
ne|ca|ca|ca|ne|bccca|ne|abc|c|ne
morda|a|ca|caac|morda|aaaca|da|ab|bcc|ne
da|a|ca|ac|morda|a|da|bc|ac|da
morda|abaa|ca|a|morda|accc|da|cb|bca|ne
morda|bbc|ca|ca|morda|bbb|morda|aacca|bcc|ne
ne|acbb|ca|bcc|ne|c|da|c|b|ne
da|cc|ca|ab|da|bccca|morda|bcc|aba|ne
da|baba|caa|ab|ne|babc|ne|bcbcc|aabb|ne
ne|aaa|caab|abccc|da|b|morda|abac|ccb|morda
morda|aaacc|caab|ca|morda|bc|da|cbb|a|da
ne|ca|caaba|bbac|ne|ba|morda|ca|bb|da
da|bbc|caaba|aa|morda|cc|morda|acc|b|da
morda|bccbb|caaba|bbcb|morda|aacac|da|bbbaa|b|ne
da|a|caabb|c|da|aabcc|ne|ccb|aa|da
ne|accc|caac|bba|da|a|morda|bcb|bacc|morda
morda|bab|caac|abbb|morda|abcc|da|bb|cacac|ne
ne|abccc|cab|ac|ne|ac|ne|aca|bbaac|ne
da|cb|cab|aaaca|da|bcc|morda|ab|aac|morda
da|bacaa|caba|abcac|morda|aaa|ne|abca|ca|ne
morda|bc|cabab|ccc|da|caa|da|ccc|baccc|ne
ne|abcb|cabab|b|morda|cccab|da|aca|a|morda
morda|cba|cabac|ccc|morda|c|morda|ccabc|baaba|da
morda|ca|cabac|bab|morda|cab|morda|cb|bcaa|ne
da|ab|cabb|ccbb|morda|cb|ne|aabc|bba|ne
da|a|cac|baa|ne|bcac|da|bcaa|aa|da
ne|b|cacab|bca|morda|acb|ne|b|acb|morda
da|cbabc|cacab|cbabc|morda|c|morda|cbab|acabc|ne
ne|bb|cacba|bb|da|aaca|ne|b|cca|ne
da|cb|cacc|acabc|da|cbb|morda|cab|ccaa|da
morda|cca|cb|bb|ne|c|morda|cc|c|ne
morda|cb|cb|a|da|cbc|morda|acb|bacb|morda
morda|bbb|cb|aac|ne|b|da|bbbcc|a|ne
ne|bcabb|cbaa|baba|morda|cba|da|aacac|baacb|ne
ne|cabac|cbab|a|morda|abc|da|ccb|abcb|morda
ne|cab|cbab|a|morda|ababa|morda|c|a|ne
ne|bc|cbac|ca|da|c|da|cbcba|acacb|ne
morda|bab|cbac|ab|da|cabcc|ne|ca|bcbcb|da
da|c|cbac|bba|da|bb|da|a|cbcb|morda
da|baa|cbac|abcac|ne|a|ne|cca|aaa|da
morda|c|cbac|bcba|da|ba|da|cabab|ba|morda
morda|bb|cbb|cac|ne|cc|morda|ca|bacb|morda
ne|bbc|cbbac|a|morda|c|morda|cbc|caaa|da
ne|abaaa|cbbca|cbc|ne|cab|morda|cb|a|morda
da|ab|cbbca|ccabc|morda|cabc|da|b|baa|da
morda|b|cbbcc|bbac|morda|a|da|ab|a|morda
morda|b|cbc|abb|da|bc|morda|bc|acc|ne
morda|ca|cbc|bbacb|morda|bacc|da|cab|accc|ne
morda|cbb|cbc|cbaab|morda|cc|morda|c|ba|ne
ne|babcb|cbc|baaba|da|bcbc|da|bba|c|da
morda|ca|cbc|ac|ne|ca|morda|c|cab|morda
morda|c|cbca|ab|morda|bba|ne|baa|a|da
ne|ccaa|cbcb|bbb|da|cacc|ne|cbbca|abc|morda
da|aa|cbcb|baaaa|ne|ca|morda|aabc|ab|morda
da|bbc|cbcba|acbb|ne|baaaa|ne|abaa|ababc|morda
ne|b|cbcbc|abc|ne|c|da|caa|ba|da
morda|bb|cbcbc|aca|da|cba|da|bca|baaba|ne
morda|b|cc|aaca|ne|c|morda|aabac|aaab|da
morda|accc|cc|ba|da|abab|morda|bc|abbbc|ne
da|ba|cc|abbaa|morda|c|ne|c|cabb|morda
ne|aa|cc|bc|ne|ca|da|bbcbc|b|da
da|baa|cc|a|ne|bb|morda|ccabb|c|morda
morda|bab|cc|aa|ne|ac|morda|bbaa|a|da
morda|c|cc|bacba|ne|a|ne|cabab|bbab|da
ne|abbcc|cc|a|da|aa|ne|cbc|bcabb|ne
ne|ca|cc|c|da|ccc|morda|bacba|acaab|ne
morda|bbca|cc|cacab|da|a|da|b|cba|da
ne|cba|cc|cab|da|ca|ne|bcccb|ca|morda
da|ba|cc|acb|da|ccac|da|baac|aaacc|da
ne|cb|cca|aaca|ne|ca|da|bcaa|ababc|morda
da|ccac|ccaa|bbaa|morda|b|da|caa|c|morda
da|bcc|ccab|cbabc|da|bab|ne|ccccb|aacca|ne
ne|cca|ccabc|ccb|ne|b|ne|bba|ba|ne
morda|ca|ccac|cb|da|babbb|morda|a|ca|da
morda|bbb|ccac|bca|da|accbc|morda|bbccc|ca|ne
morda|bca|ccb|acca|ne|ab|morda|ababa|b|morda
da|aacac|ccb|acba|da|aa|morda|b|bb|ne
ne|ca|ccb|bb|morda|bcaab|da|ba|cc|da
morda|ca|ccba|abc|da|bcca|morda|bbac|bba|da
da|cbb|ccbac|c|ne|a|ne|ab|a|ne
morda|c|ccbb|cca|da|ab|ne|baba|c|morda
da|a|ccbc|ca|ne|abc|da|bbcbb|caa|morda
da|ccb|ccbca|c|ne|abaaa|ne|a|bb|ne
morda|bac|ccbcb|ccc|ne|cacc|morda|aac|ac|ne
da|bba|ccc|aa|da|bbc|ne|bacb|a|morda
ne|bbcc|cccbb|caa|da|bcabb|da|cb|cbbb|morda
morda|abbcc|ccccb|bbcc|da|b|ne|caac|b|da
