cca|da|baba|da|abca|da|bcabb|morda
b|morda|baba|morda|bbcbc|da|bcabb|morda
c|da|baba|ne|ccbc|da|bcabb|morda
ba|morda|baba|ne|bc|da|bcabb|morda
bba|ne|baba|ne|ba|da|bcabb|morda
b|morda|baba|ne|cab|da|bcabb|morda
bcaab|da|baba|morda|cbcb|da|bcabb|morda
aac|morda|baba|da|bbc|da|bcabb|morda
bcb|morda|baba|da|bacb|da|bcabb|morda
bbccc|ne|baba|da|b|da|bcabb|morda
abaca|ne|baba|ne|abc|da|bcabb|morda
aac|morda|baba|da|aabbc|da|bcabb|morda
a|da|baba|ne|cbcb|da|bcabb|morda
b|da|acc|ne|cb|da|bcabb|morda
c|morda|acc|morda|aaca|da|bcabb|morda
bbcb|da|acc|morda|c|da|bcabb|morda
a|morda|acc|ne|abc|da|bcabb|morda
cb|ne|acc|morda|ca|da|bcabb|morda
bcacb|da|acc|da|cbc|da|bcabb|morda
cbc|morda|acc|morda|acb|da|bcabb|morda
a|morda|acc|morda|cacab|da|bcabb|morda
abbcb|da|acc|da|cb|da|bcabb|morda
a|morda|acc|morda|bcb|da|bcabb|morda
aacca|da|acc|da|ca|da|bcabb|morda
abcbc|da|acc|morda|bcaa|da|bcabb|morda
b|da|acc|morda|caba|da|bcabb|morda
ccaba|da|acc|morda|c|da|bcabb|morda
baab|ne|acc|da|b|da|bcabb|morda
a|ne|acc|ne|abaaa|da|bcabb|morda
cbbca|morda|acc|da|ca|da|bcabb|morda
caac|morda|acc|da|aacba|da|bcabb|morda
cabb|ne|baba|ne|bbc|da|bcabb|ne
cb|da|baba|morda|ca|da|bcabb|ne
bbcac|da|baba|morda|cbca|da|bcabb|ne
bab|morda|baba|da|cbabb|da|bcabb|ne
b|da|baba|da|accba|da|bcabb|ne
cac|ne|baba|morda|b|da|bcabb|ne
ba|da|baba|ne|ca|da|bcabb|ne
aabbc|ne|baba|morda|caa|da|bcabb|ne
ca|ne|baba|morda|bacba|da|bcabb|ne
bab|da|baba|ne|ccabb|da|bcabb|ne
c|da|baba|da|a|da|bcabb|ne
bab|ne|baba|ne|cbab|da|bcabb|ne
babac|ne|baba|morda|bcb|da|bcabb|ne
bbc|morda|baba|morda|a|da|bcabb|ne
ccabc|ne|baba|da|aca|da|bcabb|ne
ca|da|baba|ne|aa|da|bcabb|ne
aaca|morda|acc|ne|cacab|da|bcabb|ne
bcca|da|acc|ne|a|da|bcabb|ne
bb|morda|acc|da|b|da|bcabb|ne
cc|morda|acc|morda|abaa|da|bcabb|ne
c|da|acc|morda|bcb|da|bcabb|ne
b|ne|acc|da|aa|da|bcabb|ne
cabb|morda|acc|morda|a|da|bcabb|ne
ca|ne|acc|ne|ca|da|bcabb|ne
bb|morda|acc|morda|b|da|bcabb|ne
aca|da|acc|da|caabb|da|bcabb|ne
bcc|morda|acc|da|cb|da|bcabb|ne
bcabb|morda|acc|ne|bbb|da|bcabb|ne
baaa|ne|acc|da|b|da|bcabb|ne
caa|ne|baba|ne|cbb|da|bcabb|da
bbb|ne|baba|morda|aaa|da|bcabb|da
cbaab|ne|baba|morda|cbbcc|da|bcabb|da
ac|da|baba|morda|cca|da|bcabb|da
abcac|da|baba|ne|ccbcb|da|bcabb|da
abc|da|baba|morda|ac|da|bcabb|da
abcb|da|baba|ne|bbc|da|bcabb|da
b|da|baba|da|bc|da|bcabb|da
aaacc|da|baba|ne|ababc|da|bcabb|da
bb|morda|baba|morda|b|da|bcabb|da
ac|da|baba|ne|cb|da|bcabb|da
bcb|ne|baba|morda|bbcbc|da|bcabb|da
baaca|ne|acc|morda|baaaa|da|bcabb|da
bba|da|acc|morda|caa|da|bcabb|da
c|ne|acc|morda|bba|da|bcabb|da
cbc|ne|acc|morda|b|da|bcabb|da
acaaa|ne|acc|ne|bbaac|da|bcabb|da
cc|ne|acc|ne|bbb|da|bcabb|da
ca|da|acc|ne|a|da|bcabb|da
babaa|morda|acc|ne|ba|da|bcabb|da
abcac|da|acc|ne|accba|da|bcabb|da
aab|da|acc|da|bac|da|bcabb|da
cabcc|morda|acc|morda|aa|da|bcabb|da
bcca|ne|acc|da|bbcb|da|bcabb|da
bab|ne|acc|morda|b|da|bcabb|da
bcbc|ne|baba|morda|aa|morda|bcabb|morda
ca|da|baba|da|cccc|morda|bcabb|morda
a|ne|baba|ne|ac|morda|bcabb|morda
bb|da|baba|morda|caa|morda|bcabb|morda
bcab|morda|baba|morda|bbacb|morda|bcabb|morda
bca|ne|baba|ne|accc|morda|bcabb|morda
acccc|da|baba|morda|a|morda|bcabb|morda
bbb|morda|baba|da|b|morda|bcabb|morda
b|ne|baba|ne|bbaa|morda|bcabb|morda
cabcc|morda|baba|da|bac|morda|bcabb|morda
b|ne|baba|morda|bca|morda|bcabb|morda
b|da|baba|ne|cba|morda|bcabb|morda
aaacc|morda|baba|da|bac|morda|bcabb|morda
cc|ne|baba|ne|caa|morda|bcabb|morda
babba|da|baba|ne|ab|morda|bcabb|morda
c|da|baba|morda|bbc|morda|bcabb|morda
ca|da|baba|morda|ccac|morda|bcabb|morda
abc|da|baba|da|bbc|morda|bcabb|morda
bca|ne|acc|morda|ba|morda|bcabb|morda
cccc|morda|acc|ne|acba|morda|bcabb|morda
caab|morda|acc|da|cabc|morda|bcabb|morda
bb|da|acc|da|c|morda|bcabb|morda
abcac|morda|acc|da|bcab|morda|bcabb|morda
cc|morda|acc|morda|aaa|morda|bcabb|morda
a|ne|acc|da|ccaa|morda|bcabb|morda
abcac|morda|acc|ne|ca|morda|bcabb|morda
cc|ne|acc|ne|cacb|morda|bcabb|morda
acbb|da|acc|da|accb|morda|bcabb|morda
abcb|da|acc|da|aaab|morda|bcabb|morda
c|ne|acc|morda|a|morda|bcabb|morda
bcab|da|acc|ne|ab|morda|bcabb|morda
cbabb|da|acc|da|ba|morda|bcabb|morda
bcca|morda|acc|morda|acca|morda|bcabb|morda
cab|morda|acc|ne|caa|morda|bcabb|morda
cacab|morda|baba|ne|bc|morda|bcabb|ne
baa|morda|baba|da|bbccb|morda|bcabb|ne
a|da|baba|morda|aaabb|morda|bcabb|ne
ba|morda|baba|ne|bca|morda|bcabb|ne
babc|morda|baba|ne|a|morda|bcabb|ne
aca|morda|baba|da|ca|morda|bcabb|ne
ba|da|baba|da|ccab|morda|bcabb|ne
a|ne|baba|morda|bccbb|morda|bcabb|ne
a|ne|baba|ne|ba|morda|bcabb|ne
bcb|morda|baba|ne|babca|morda|bcabb|ne
abc|ne|baba|da|cc|morda|bcabb|ne
bbc|morda|baba|ne|aabba|morda|bcabb|ne
ab|ne|baba|morda|a|morda|bcabb|ne
c|ne|baba|morda|ac|morda|bcabb|ne
aba|da|acc|ne|cbaa|morda|bcabb|ne
ccb|da|acc|morda|bbc|morda|bcabb|ne
baaaa|morda|acc|da|ca|morda|bcabb|ne
ab|morda|acc|ne|ca|morda|bcabb|ne
cac|morda|acc|ne|ab|morda|bcabb|ne
bacba|ne|acc|ne|abc|morda|bcabb|ne
c|ne|acc|da|aacbc|morda|bcabb|ne
aba|morda|acc|ne|cbb|morda|bcabb|ne
b|morda|acc|ne|acaab|morda|bcabb|ne
bba|ne|acc|ne|a|morda|bcabb|ne
b|da|acc|da|accc|morda|bcabb|ne
aba|morda|baba|ne|acb|morda|bcabb|da
bb|ne|baba|morda|ba|morda|bcabb|da
ccaba|ne|baba|ne|bcca|morda|bcabb|da
c|morda|baba|morda|aa|morda|bcabb|da
babc|morda|baba|ne|acaab|morda|bcabb|da
ab|da|baba|morda|baa|morda|bcabb|da
acccc|ne|baba|ne|c|morda|bcabb|da
aa|ne|baba|da|aaacc|morda|bcabb|da
babc|da|baba|ne|babc|morda|bcabb|da
bbabc|morda|baba|da|a|morda|bcabb|da
ca|da|baba|morda|bccbc|morda|bcabb|da
aabba|morda|acc|ne|ccac|morda|bcabb|da
abc|da|acc|morda|acc|morda|bcabb|da
b|ne|acc|da|abc|morda|bcabb|da
bb|da|acc|morda|abbcc|morda|bcabb|da
cb|ne|acc|ne|abc|morda|bcabb|da
ba|ne|acc|da|b|morda|bcabb|da
aa|ne|acc|ne|bcabb|morda|bcabb|da
aca|da|acc|ne|bbbb|morda|bcabb|da
bacc|ne|acc|ne|cc|morda|bcabb|da
bcabb|ne|acc|ne|babac|morda|bcabb|da
bc|morda|acc|morda|cbabb|morda|bcabb|da
ccb|ne|acc|morda|baaca|morda|bcabb|da
a|da|acc|ne|a|morda|bcabb|da
ac|da|acc|da|b|morda|bcabb|da
bb|morda|acc|da|bcb|morda|bcabb|da
bcba|morda|acc|morda|cb|morda|bcabb|da
cccab|ne|acc|morda|bccc|morda|bcabb|da
cc|morda|acc|ne|acac|morda|bcabb|da
c|ne|acc|da|ab|morda|bcabb|da
abbbc|morda|baba|morda|b|da|bbbc|morda
bab|morda|baba|morda|cc|da|bbbc|morda
ba|morda|baba|da|cca|da|bbbc|morda
a|da|baba|morda|bccbb|da|bbbc|morda
ba|ne|baba|ne|bccbb|da|bbbc|morda
ca|ne|baba|ne|ba|da|bbbc|morda
aabc|da|baba|da|cbaa|da|bbbc|morda
ba|da|baba|ne|a|da|bbbc|morda
c|morda|baba|da|c|da|bbbc|morda
caca|da|baba|da|b|da|bbbc|morda
bbcbc|da|baba|da|aaab|da|bbbc|morda
bc|morda|baba|da|abac|da|bbbc|morda
cc|morda|baba|morda|aabc|da|bbbc|morda
ca|da|baba|morda|ccbca|da|bbbc|morda
cbbcc|ne|baba|ne|cbab|da|bbbc|morda
ab|da|baba|morda|accbc|da|bbbc|morda
babbc|da|baba|ne|c|da|bbbc|morda
abc|da|baba|morda|c|da|bbbc|morda
cabcc|morda|acc|ne|cabac|da|bbbc|morda
ccab|morda|acc|da|bcab|da|bbbc|morda
c|morda|acc|ne|ba|da|bbbc|morda
ac|morda|acc|ne|ab|da|bbbc|morda
acc|ne|acc|ne|cbcb|da|bbbc|morda
b|morda|acc|da|bb|da|bbbc|morda
aacbc|morda|acc|morda|cb|da|bbbc|morda
aaacc|morda|acc|morda|acaba|da|bbbc|morda
acb|da|acc|ne|a|da|bbbc|morda
ab|ne|acc|da|ca|da|bbbc|morda
a|morda|acc|ne|ab|da|bbbc|morda
acabc|morda|acc|ne|bbabc|da|bbbc|morda
ab|morda|baba|morda|bbbca|da|bbbc|ne
bc|da|baba|da|ccc|da|bbbc|ne
bc|ne|baba|da|b|da|bbbc|ne
a|da|baba|ne|c|da|bbbc|ne
acc|morda|baba|da|abba|da|bbbc|ne
acac|morda|baba|morda|ababc|da|bbbc|ne
c|morda|baba|da|bcca|da|bbbc|ne
bcca|morda|baba|da|baaab|da|bbbc|ne
cba|ne|baba|ne|aaa|da|bbbc|ne
ca|da|baba|morda|bbb|da|bbbc|ne
bbbb|da|baba|da|b|da|bbbc|ne
ababc|morda|baba|da|bb|da|bbbc|ne
a|morda|baba|morda|cccab|da|bbbc|ne
aabb|da|baba|morda|cbcb|da|bbbc|ne
abaca|ne|baba|ne|bcaa|da|bbbc|ne
bba|ne|acc|ne|bccba|da|bbbc|ne
ab|ne|acc|da|bbbc|da|bbbc|ne
aaa|morda|acc|morda|bac|da|bbbc|ne
c|morda|acc|da|bbc|da|bbbc|ne
bccbb|morda|acc|morda|bcbc|da|bbbc|ne
aabab|da|acc|morda|ccb|da|bbbc|ne
abccc|morda|acc|morda|c|da|bbbc|ne
bbcc|morda|acc|ne|ccac|da|bbbc|ne
bba|da|acc|morda|bcb|da|bbbc|ne
bbb|da|acc|ne|aacaa|da|bbbc|ne
b|da|acc|da|cab|da|bbbc|ne
bcbaa|ne|acc|morda|acb|da|bbbc|ne
aa|morda|baba|da|cb|da|bbbc|da
cc|ne|baba|morda|bacc|da|bbbc|da
bbb|ne|baba|da|ab|da|bbbc|da
b|ne|baba|da|bccbb|da|bbbc|da
abc|ne|baba|da|bca|da|bbbc|da
ac|morda|baba|da|bccaa|da|bbbc|da
c|da|baba|ne|cbcbc|da|bbbc|da
ccbac|morda|baba|morda|abc|da|bbbc|da
bc|ne|baba|ne|ac|da|bbbc|da
aaaca|ne|baba|morda|bcc|da|bbbc|da
b|da|baba|ne|aaccc|da|bbbc|da
acc|da|baba|ne|b|da|bbbc|da
c|ne|baba|morda|b|da|bbbc|da
c|morda|baba|da|ac|da|bbbc|da
cb|morda|acc|morda|a|da|bbbc|da
baaaa|morda|acc|morda|ba|da|bbbc|da
bb|da|acc|da|cc|da|bbbc|da
ccc|da|acc|ne|cb|da|bbbc|da
b|ne|acc|ne|c|da|bbbc|da
bab|morda|acc|ne|a|da|bbbc|da
aabbb|da|acc|ne|b|da|bbbc|da
bbaca|ne|acc|ne|ccac|da|bbbc|da
aa|ne|acc|da|aa|da|bbbc|da
b|da|acc|morda|ccba|da|bbbc|da
ba|ne|acc|ne|c|da|bbbc|da
cbcb|ne|acc|morda|cbcb|da|bbbc|da
ccba|morda|acc|da|cbc|da|bbbc|da
caaa|da|acc|morda|b|da|bbbc|da
cabb|morda|acc|morda|aacb|da|bbbc|da
ca|ne|acc|da|caaba|da|bbbc|da
bc|ne|acc|ne|b|da|bbbc|da
b|da|acc|ne|baab|da|bbbc|da
abc|da|acc|ne|bcc|da|bbbc|da
bbbc|ne|baba|ne|abc|morda|bbbc|morda
cbbc|ne|baba|morda|babbb|morda|bbbc|morda
cba|ne|baba|ne|b|morda|bbbc|morda
c|morda|baba|ne|abcac|morda|bbbc|morda
c|da|baba|da|c|morda|bbbc|morda
aa|da|baba|ne|a|morda|bbbc|morda
bccbb|morda|baba|da|ccac|morda|bbbc|morda
aa|da|baba|morda|bba|morda|bbbc|morda
bcca|da|baba|ne|bac|morda|bbbc|morda
bcacb|ne|baba|morda|a|morda|bbbc|morda
a|da|baba|morda|b|morda|bbbc|morda
cabc|morda|baba|ne|babc|morda|bbbc|morda
bbcac|ne|baba|da|bbcb|morda|bbbc|morda
ca|da|baba|da|ba|morda|bbbc|morda
ccac|morda|baba|morda|ccc|morda|bbbc|morda
bcb|ne|acc|morda|ccbc|morda|bbbc|morda
abb|ne|acc|ne|cbaa|morda|bbbc|morda
bcab|ne|acc|morda|cbcbc|morda|bbbc|morda
accba|ne|acc|da|abbaa|morda|bbbc|morda
bbccc|ne|acc|ne|ba|morda|bbbc|morda
cbc|ne|acc|ne|b|morda|bbbc|morda
aacbc|ne|acc|da|aacac|morda|bbbc|morda
abc|da|acc|da|caba|morda|bbbc|morda
bbbc|morda|acc|da|aacc|morda|bbbc|morda
acac|da|acc|morda|ccb|morda|bbbc|morda
b|ne|acc|ne|caab|morda|bbbc|morda
b|ne|acc|ne|ccb|morda|bbbc|morda
ab|morda|acc|morda|bb|morda|bbbc|morda
bbbc|da|acc|ne|bc|morda|bbbc|morda
a|morda|acc|morda|abccc|morda|bbbc|morda
ba|morda|baba|da|c|morda|bbbc|ne
bac|morda|baba|morda|cbab|morda|bbbc|ne
abbb|da|baba|morda|cbaab|morda|bbbc|ne
bccbb|ne|baba|da|baaaa|morda|bbbc|ne
bcc|da|baba|da|baa|morda|bbbc|ne
b|morda|baba|da|aca|morda|bbbc|ne
bcabb|morda|baba|da|abaaa|morda|bbbc|ne
cbc|da|baba|ne|aba|morda|bbbc|ne
ba|ne|baba|ne|a|morda|bbbc|ne
bb|da|baba|da|bbc|morda|bbbc|ne
a|ne|baba|ne|ca|morda|bbbc|ne
bcbab|morda|acc|da|aaa|morda|bbbc|ne
abcc|da|acc|da|bcc|morda|bbbc|ne
bcac|da|acc|ne|c|morda|bbbc|ne
baab|ne|acc|da|baa|morda|bbbc|ne
bbccc|da|acc|morda|acaaa|morda|bbbc|ne
b|ne|acc|morda|c|morda|bbbc|ne
ab|morda|acc|da|ab|morda|bbbc|ne
ccaa|morda|acc|ne|bcba|morda|bbbc|ne
aa|da|acc|morda|cb|morda|bbbc|ne
acbca|da|acc|ne|accba|morda|bbbc|ne
acba|da|acc|ne|b|morda|bbbc|ne
aabbb|da|acc|ne|baaab|morda|bbbc|ne
bacaa|morda|acc|da|bbb|morda|bbbc|ne
accba|da|acc|ne|aa|morda|bbbc|ne
caaa|ne|acc|da|b|morda|bbbc|ne
aba|ne|acc|ne|bcbc|morda|bbbc|ne
a|ne|acc|da|abc|morda|bbbc|ne
ca|da|acc|ne|bbac|morda|bbbc|ne
a|da|acc|ne|cc|morda|bbbc|ne
b|ne|acc|ne|cb|morda|bbbc|ne
bbb|morda|acc|ne|babca|morda|bbbc|ne
cbb|da|baba|morda|c|morda|bbbc|da
bb|morda|baba|ne|cc|morda|bbbc|da
cbbac|ne|baba|ne|aaa|morda|bbbc|da
acc|ne|baba|da|bc|morda|bbbc|da
bccac|morda|baba|da|a|morda|bbbc|da
a|morda|baba|da|caa|morda|bbbc|da
abbcc|ne|baba|ne|abbb|morda|bbbc|da
aa|da|baba|ne|cca|morda|bbbc|da
abc|ne|baba|morda|bcc|morda|bbbc|da
cc|da|baba|ne|caa|morda|bbbc|da
ca|morda|baba|ne|acac|morda|bbbc|da
abaca|da|baba|ne|aac|morda|bbbc|da
aa|da|baba|da|bcb|morda|bbbc|da
cbcbc|da|baba|morda|acc|morda|bbbc|da
b|da|baba|da|bcaca|morda|bbbc|da
a|ne|baba|ne|acac|morda|bbbc|da
bcabb|ne|baba|morda|ccac|morda|bbbc|da
b|ne|baba|morda|acc|morda|bbbc|da
c|ne|baba|morda|bcba|morda|bbbc|da
b|da|acc|morda|cbcab|morda|bbbc|da
aa|ne|acc|morda|bccba|morda|bbbc|da
b|da|acc|da|c|morda|bbbc|da
cacbc|da|acc|da|bbab|morda|bbbc|da
ac|da|acc|ne|cacac|morda|bbbc|da
a|da|acc|ne|aaaca|morda|bbbc|da
caab|ne|acc|da|cabc|morda|bbbc|da
bcbaa|ne|acc|morda|cbc|morda|bbbc|da
a|morda|acc|morda|bbac|morda|bbbc|da
cccc|da|acc|ne|aba|morda|bbbc|da
bca|da|acc|ne|aabcb|morda|bbbc|da
accba|morda|acc|morda|bb|morda|bbbc|da
caab|ne|acc|da|a|morda|bbbc|da
bba|morda|acc|da|a|morda|bbbc|da
a|ne|acc|morda|abac|morda|bbbc|da
bab|morda|acc|ne|baaca|morda|bbbc|da
abaaa|morda|acc|da|bbaca|morda|bbbc|da
bb|da|acc|ne|a|morda|bbbc|da
ab|morda|acc|morda|bcbc|morda|bbbc|da
cacb|ne|acc|da|cca|morda|bbbc|da
